/**
 * Style Dictionary build for the vaultspec-dashboard color framework (plan W01.P02).
 *
 * Reads the DTCG token source (primitives + semantic + per-theme overrides) declared by
 * `tokens/resolver.json`, uses Style Dictionary to parse and merge each theme mode, and
 * emits `src/styles.generated.css` — the candidate that the parity script
 * (`scripts/token-parity.ts`) diffs against the committed `src/styles.css` color tier
 * before the canonical flip (W01.P03).
 *
 * Run: `node style-dictionary.config.ts` (Node 22.6+ strips the TS types at runtime).
 *
 * Output shape mirrors styles.css:
 *   :root { primitives + semantic(default) + public(default) }   == @theme static
 *   [data-theme="light"|"dark"|"high-contrast"] { themed subset }
 * where the "themed subset" is exactly the set of token paths the override files carry
 * (the semantic tier plus the diverging public tokens and the scene-read hex) — the same
 * subset styles.css restates per [data-theme] block.
 */

import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readFileSync, writeFileSync } from "node:fs";
import StyleDictionary from "style-dictionary";
import { cssValue, defaultCssVar, type DtcgColorValue } from "./build/sd-transforms.ts";

const here = dirname(fileURLToPath(import.meta.url));
const tokensDir = join(here, "tokens");
const outFile = join(here, "src", "styles.generated.css");

type Leaf = { path: string[]; original: { $value: DtcgColorValue }; $extensions?: any };

const PRIMITIVES = join(tokensDir, "primitives.tokens.json");
const SEMANTIC = join(tokensDir, "semantic.tokens.json");
const DARK = join(tokensDir, "themes", "dark.tokens.json");
const HC = join(tokensDir, "themes", "high-contrast.tokens.json");

/** Collect leaf token dotted-paths from a raw DTCG file (paths that have a $value). */
function leafPaths(obj: any, prefix: string[] = [], acc = new Set<string>()): Set<string> {
  for (const k of Object.keys(obj)) {
    if (k.startsWith("$")) continue;
    const v = obj[k];
    if (v && typeof v === "object" && "$value" in v) acc.add([...prefix, k].join("."));
    else if (v && typeof v === "object") leafPaths(v, [...prefix, k], acc);
  }
  return acc;
}

/** The set of token paths that appear in a [data-theme] block (== the override files). */
const THEMED = leafPaths(JSON.parse(readFileSync(DARK, "utf8")));

/** Build the path -> css-var-name map from the base definitions (primitives + semantic). */
function buildVarMap(): Map<string, string> {
  const map = new Map<string, string>();
  for (const file of [PRIMITIVES, SEMANTIC]) {
    walkVars(JSON.parse(readFileSync(file, "utf8")), [], map);
  }
  return map;
}
function walkVars(obj: any, prefix: string[], map: Map<string, string>): void {
  for (const k of Object.keys(obj)) {
    if (k.startsWith("$")) continue;
    const v = obj[k];
    const path = [...prefix, k];
    if (v && typeof v === "object" && "$value" in v) {
      const pinned = v.$extensions?.["com.vaultspec.css"]?.var;
      map.set(path.join("."), pinned ?? defaultCssVar(path.join(".")));
    } else if (v && typeof v === "object") {
      walkVars(v, path, map);
    }
  }
}

const VAR_OF = buildVarMap();
const varForPath = (p: string): string => {
  const v = VAR_OF.get(p);
  if (!v) throw new Error(`no css var known for token path ${p}`);
  return v;
};

/** Parse + merge a mode's sources via Style Dictionary, returning leaf tokens. */
async function tokensFor(sources: string[]): Promise<Leaf[]> {
  const sd = new StyleDictionary({
    source: sources,
    // We emit ourselves; give SD a no-op platform so it only parses + merges.
    platforms: { noop: { transformGroup: "css", files: [] } },
    log: { verbosity: "silent", warnings: "disabled" },
  });
  const dict = await sd.getPlatformTokens("noop");
  return dict.allTokens as unknown as Leaf[];
}

/** Emit a CSS declaration block body for the given tokens, filtered by predicate. */
function emitBlock(tokens: Leaf[], keep: (path: string) => boolean): string {
  const lines: string[] = [];
  for (const t of tokens) {
    const path = t.path.join(".");
    if (!keep(path)) continue;
    const name = VAR_OF.get(path) ?? defaultCssVar(path);
    lines.push(`  ${name}: ${cssValue(t.original.$value, varForPath)};`);
  }
  return lines.join("\n");
}

/** Generate the full color CSS string from the DTCG source (no file write). */
export async function generateCss(): Promise<string> {
  const base = await tokensFor([PRIMITIVES, SEMANTIC]);
  const dark = await tokensFor([PRIMITIVES, SEMANTIC, DARK]);
  const hc = await tokensFor([PRIMITIVES, SEMANTIC, HC]);

  const header =
    "/* GENERATED by style-dictionary.config.ts from tokens/*.tokens.json. DO NOT EDIT.\n" +
    "   Canonical source: frontend/tokens/ (DTCG). Regenerate: `npm run tokens:build`.\n" +
    "   Parity-checked against src/styles.css by scripts/token-parity.ts (plan W01.P02). */\n";

  return (
    header +
    "\n:root {\n" +
    emitBlock(base, () => true) +
    "\n}\n" +
    `\n[data-theme="light"] {\n` +
    emitBlock(base, (p) => THEMED.has(p)) +
    "\n}\n" +
    `\n[data-theme="dark"] {\n` +
    emitBlock(dark, (p) => THEMED.has(p)) +
    "\n}\n" +
    `\n[data-theme="high-contrast"] {\n` +
    emitBlock(hc, (p) => THEMED.has(p)) +
    "\n}\n"
  );
}

export const OUT_FILE = outFile;
export const THEMED_COUNT = THEMED.size;

async function build(): Promise<void> {
  const css = await generateCss();
  writeFileSync(outFile, css, "utf8");
  console.log(`wrote ${outFile}`);
  console.log(`  themed per mode: ${THEMED.size}`);
}

// Run the writer only when invoked directly (not when imported by the drift check).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  build().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
