// The shared language registry for all highlighted viewer/editor surfaces.
//
// Maps the engine's `language_hint` (and a markdown code-fence `language-*` info
// string) onto Shiki's bundled grammar registry, so the code viewer, markdown
// fenced blocks, document editor overlay, and review snippets share ONE tokenizer
// and ONE language vocabulary. Grammars still load lazily through Shiki's dynamic
// import registry: this file imports metadata and import thunks, not every grammar.
//
// An unknown/absent hint resolves to `null`: the viewer renders the text as plain
// (no grammar) rather than guessing -- an honest degradation, not a broken render.

import type { LanguageRegistration } from "shiki/core";
import {
  bundledLanguages,
  bundledLanguagesInfo,
  type BundledLanguage,
} from "shiki/langs";
import type { MessageDescriptor } from "../../platform/localization/message";

export const CANONICAL_LANGUAGE_IDS = [
  "abap",
  "actionscript-3",
  "ada",
  "angular-html",
  "angular-ts",
  "apache",
  "apex",
  "apl",
  "applescript",
  "ara",
  "asciidoc",
  "asm",
  "astro",
  "awk",
  "ballerina",
  "bat",
  "beancount",
  "berry",
  "bibtex",
  "bicep",
  "bird2",
  "blade",
  "bsl",
  "c",
  "c3",
  "cadence",
  "cairo",
  "clarity",
  "clojure",
  "cmake",
  "cobol",
  "codeowners",
  "codeql",
  "coffee",
  "common-lisp",
  "coq",
  "cpp",
  "crystal",
  "csharp",
  "css",
  "csv",
  "cue",
  "cypher",
  "d",
  "dart",
  "dax",
  "desktop",
  "diff",
  "docker",
  "dotenv",
  "dream-maker",
  "edge",
  "elixir",
  "elm",
  "emacs-lisp",
  "erb",
  "erlang",
  "fennel",
  "fish",
  "fluent",
  "fortran-fixed-form",
  "fortran-free-form",
  "fsharp",
  "gdresource",
  "gdscript",
  "gdshader",
  "genie",
  "gherkin",
  "git-commit",
  "git-rebase",
  "gleam",
  "glimmer-js",
  "glimmer-ts",
  "glsl",
  "gn",
  "gnuplot",
  "go",
  "graphql",
  "groovy",
  "hack",
  "haml",
  "handlebars",
  "haskell",
  "haxe",
  "hcl",
  "hjson",
  "hlsl",
  "html",
  "html-derivative",
  "http",
  "hurl",
  "hxml",
  "hy",
  "imba",
  "ini",
  "java",
  "javascript",
  "jinja",
  "jison",
  "json",
  "json5",
  "jsonc",
  "jsonl",
  "jsonnet",
  "jssm",
  "jsx",
  "julia",
  "just",
  "kdl",
  "kotlin",
  "kusto",
  "latex",
  "lean",
  "less",
  "liquid",
  "llvm",
  "log",
  "logo",
  "lua",
  "luau",
  "make",
  "markdown",
  "marko",
  "matlab",
  "mdc",
  "mdx",
  "mermaid",
  "mipsasm",
  "mojo",
  "moonbit",
  "move",
  "narrat",
  "nextflow",
  "nextflow-groovy",
  "nginx",
  "nim",
  "nix",
  "nushell",
  "objective-c",
  "objective-cpp",
  "ocaml",
  "odin",
  "openscad",
  "pascal",
  "perl",
  "php",
  "pkl",
  "plsql",
  "po",
  "polar",
  "postcss",
  "powerquery",
  "powershell",
  "prisma",
  "prolog",
  "proto",
  "pug",
  "puppet",
  "purescript",
  "python",
  "qml",
  "qmldir",
  "qss",
  "r",
  "racket",
  "raku",
  "razor",
  "reg",
  "regexp",
  "rel",
  "riscv",
  "ron",
  "rosmsg",
  "rst",
  "ruby",
  "rust",
  "sas",
  "sass",
  "scala",
  "scheme",
  "scss",
  "sdbl",
  "shaderlab",
  "shellscript",
  "shellsession",
  "smalltalk",
  "solidity",
  "soy",
  "sparql",
  "splunk",
  "sql",
  "ssh-config",
  "stata",
  "stylus",
  "surrealql",
  "svelte",
  "swift",
  "system-verilog",
  "systemd",
  "talonscript",
  "tasl",
  "tcl",
  "templ",
  "terraform",
  "tex",
  "toml",
  "ts-tags",
  "tsv",
  "tsx",
  "turtle",
  "twig",
  "typescript",
  "typespec",
  "typst",
  "v",
  "vala",
  "vb",
  "verilog",
  "vhdl",
  "viml",
  "vue",
  "vue-html",
  "vue-vine",
  "vyper",
  "wasm",
  "wenyan",
  "wgsl",
  "wikitext",
  "wit",
  "wolfram",
  "xml",
  "xsl",
  "yaml",
  "zenscript",
  "zig",
] as const satisfies readonly BundledLanguage[];

export const BUNDLED_LANGUAGE_ALIAS_IDS = [
  "adoc",
  "batch",
  "be",
  "bird",
  "1c",
  "cdc",
  "clj",
  "ql",
  "coffeescript",
  "lisp",
  "c++",
  "c#",
  "cs",
  "cql",
  "dockerfile",
  "elisp",
  "erl",
  "ftl",
  "f",
  "for",
  "f77",
  "f90",
  "f95",
  "f03",
  "f08",
  "f18",
  "f#",
  "fs",
  "tscn",
  "tres",
  "gd",
  "gjs",
  "gts",
  "gql",
  "hbs",
  "hs",
  "properties",
  "js",
  "cjs",
  "mjs",
  "fsl",
  "jl",
  "kt",
  "kts",
  "kql",
  "lean4",
  "makefile",
  "md",
  "mmd",
  "mips",
  "mbt",
  "mbti",
  "nar",
  "nf",
  "nu",
  "objc",
  "scad",
  "pot",
  "potx",
  "ps",
  "ps1",
  "protobuf",
  "jade",
  "py",
  "perl6",
  "regex",
  "rb",
  "rs",
  "1c-query",
  "shader",
  "bash",
  "sh",
  "shell",
  "zsh",
  "console",
  "closure-templates",
  "spl",
  "styl",
  "surql",
  "talon",
  "tf",
  "tfvars",
  "lit",
  "ts",
  "cts",
  "mts",
  "tsp",
  "typ",
  "cmd",
  "vim",
  "vimscript",
  "vy",
  "文言",
  "mediawiki",
  "wiki",
  "wl",
  "yml",
] as const satisfies readonly BundledLanguage[];

export type CanonicalLanguageId = (typeof CANONICAL_LANGUAGE_IDS)[number];
type ClassifiedBundledLanguage =
  | CanonicalLanguageId
  | (typeof BUNDLED_LANGUAGE_ALIAS_IDS)[number];
type MissingBundledLanguage = Exclude<BundledLanguage, ClassifiedBundledLanguage>;
const BUNDLED_LANGUAGE_CLASSIFICATION: Record<MissingBundledLanguage, never> = {};
void BUNDLED_LANGUAGE_CLASSIFICATION;

export const LANGUAGE_DISPLAY_MESSAGES = {
  code: { key: "documents:viewer.languages.code" },
  text: { key: "documents:viewer.languages.text" },
  names: {
    abap: { key: "documents:viewer.languages.names.abap" },
    "actionscript-3": { key: "documents:viewer.languages.names.actionscript3" },
    ada: { key: "documents:viewer.languages.names.ada" },
    "angular-html": { key: "documents:viewer.languages.names.angularHtml" },
    "angular-ts": { key: "documents:viewer.languages.names.angularTs" },
    apache: { key: "documents:viewer.languages.names.apache" },
    apex: { key: "documents:viewer.languages.names.apex" },
    apl: { key: "documents:viewer.languages.names.apl" },
    applescript: { key: "documents:viewer.languages.names.applescript" },
    ara: { key: "documents:viewer.languages.names.ara" },
    asciidoc: { key: "documents:viewer.languages.names.asciidoc" },
    asm: { key: "documents:viewer.languages.names.asm" },
    astro: { key: "documents:viewer.languages.names.astro" },
    awk: { key: "documents:viewer.languages.names.awk" },
    ballerina: { key: "documents:viewer.languages.names.ballerina" },
    bat: { key: "documents:viewer.languages.names.bat" },
    beancount: { key: "documents:viewer.languages.names.beancount" },
    berry: { key: "documents:viewer.languages.names.berry" },
    bibtex: { key: "documents:viewer.languages.names.bibtex" },
    bicep: { key: "documents:viewer.languages.names.bicep" },
    bird2: { key: "documents:viewer.languages.names.bird2" },
    blade: { key: "documents:viewer.languages.names.blade" },
    bsl: { key: "documents:viewer.languages.names.bsl" },
    c: { key: "documents:viewer.languages.names.c" },
    c3: { key: "documents:viewer.languages.names.c3" },
    cadence: { key: "documents:viewer.languages.names.cadence" },
    cairo: { key: "documents:viewer.languages.names.cairo" },
    clarity: { key: "documents:viewer.languages.names.clarity" },
    clojure: { key: "documents:viewer.languages.names.clojure" },
    cmake: { key: "documents:viewer.languages.names.cmake" },
    cobol: { key: "documents:viewer.languages.names.cobol" },
    codeowners: { key: "documents:viewer.languages.names.codeowners" },
    codeql: { key: "documents:viewer.languages.names.codeql" },
    coffee: { key: "documents:viewer.languages.names.coffee" },
    "common-lisp": { key: "documents:viewer.languages.names.commonLisp" },
    coq: { key: "documents:viewer.languages.names.coq" },
    cpp: { key: "documents:viewer.languages.names.cpp" },
    crystal: { key: "documents:viewer.languages.names.crystal" },
    csharp: { key: "documents:viewer.languages.names.csharp" },
    css: { key: "documents:viewer.languages.names.css" },
    csv: { key: "documents:viewer.languages.names.csv" },
    cue: { key: "documents:viewer.languages.names.cue" },
    cypher: { key: "documents:viewer.languages.names.cypher" },
    d: { key: "documents:viewer.languages.names.d" },
    dart: { key: "documents:viewer.languages.names.dart" },
    dax: { key: "documents:viewer.languages.names.dax" },
    desktop: { key: "documents:viewer.languages.names.desktop" },
    diff: { key: "documents:viewer.languages.names.diff" },
    docker: { key: "documents:viewer.languages.names.docker" },
    dotenv: { key: "documents:viewer.languages.names.dotenv" },
    "dream-maker": { key: "documents:viewer.languages.names.dreamMaker" },
    edge: { key: "documents:viewer.languages.names.edge" },
    elixir: { key: "documents:viewer.languages.names.elixir" },
    elm: { key: "documents:viewer.languages.names.elm" },
    "emacs-lisp": { key: "documents:viewer.languages.names.emacsLisp" },
    erb: { key: "documents:viewer.languages.names.erb" },
    erlang: { key: "documents:viewer.languages.names.erlang" },
    fennel: { key: "documents:viewer.languages.names.fennel" },
    fish: { key: "documents:viewer.languages.names.fish" },
    fluent: { key: "documents:viewer.languages.names.fluent" },
    "fortran-fixed-form": {
      key: "documents:viewer.languages.names.fortranFixedForm",
    },
    "fortran-free-form": { key: "documents:viewer.languages.names.fortranFreeForm" },
    fsharp: { key: "documents:viewer.languages.names.fsharp" },
    gdresource: { key: "documents:viewer.languages.names.gdresource" },
    gdscript: { key: "documents:viewer.languages.names.gdscript" },
    gdshader: { key: "documents:viewer.languages.names.gdshader" },
    genie: { key: "documents:viewer.languages.names.genie" },
    gherkin: { key: "documents:viewer.languages.names.gherkin" },
    "git-commit": { key: "documents:viewer.languages.names.gitCommit" },
    "git-rebase": { key: "documents:viewer.languages.names.gitRebase" },
    gleam: { key: "documents:viewer.languages.names.gleam" },
    "glimmer-js": { key: "documents:viewer.languages.names.glimmerJs" },
    "glimmer-ts": { key: "documents:viewer.languages.names.glimmerTs" },
    glsl: { key: "documents:viewer.languages.names.glsl" },
    gn: { key: "documents:viewer.languages.names.gn" },
    gnuplot: { key: "documents:viewer.languages.names.gnuplot" },
    go: { key: "documents:viewer.languages.names.go" },
    graphql: { key: "documents:viewer.languages.names.graphql" },
    groovy: { key: "documents:viewer.languages.names.groovy" },
    hack: { key: "documents:viewer.languages.names.hack" },
    haml: { key: "documents:viewer.languages.names.haml" },
    handlebars: { key: "documents:viewer.languages.names.handlebars" },
    haskell: { key: "documents:viewer.languages.names.haskell" },
    haxe: { key: "documents:viewer.languages.names.haxe" },
    hcl: { key: "documents:viewer.languages.names.hcl" },
    hjson: { key: "documents:viewer.languages.names.hjson" },
    hlsl: { key: "documents:viewer.languages.names.hlsl" },
    html: { key: "documents:viewer.languages.names.html" },
    "html-derivative": { key: "documents:viewer.languages.names.htmlDerivative" },
    http: { key: "documents:viewer.languages.names.http" },
    hurl: { key: "documents:viewer.languages.names.hurl" },
    hxml: { key: "documents:viewer.languages.names.hxml" },
    hy: { key: "documents:viewer.languages.names.hy" },
    imba: { key: "documents:viewer.languages.names.imba" },
    ini: { key: "documents:viewer.languages.names.ini" },
    java: { key: "documents:viewer.languages.names.java" },
    javascript: { key: "documents:viewer.languages.names.javascript" },
    jinja: { key: "documents:viewer.languages.names.jinja" },
    jison: { key: "documents:viewer.languages.names.jison" },
    json: { key: "documents:viewer.languages.names.json" },
    json5: { key: "documents:viewer.languages.names.json5" },
    jsonc: { key: "documents:viewer.languages.names.jsonc" },
    jsonl: { key: "documents:viewer.languages.names.jsonl" },
    jsonnet: { key: "documents:viewer.languages.names.jsonnet" },
    jssm: { key: "documents:viewer.languages.names.jssm" },
    jsx: { key: "documents:viewer.languages.names.jsx" },
    julia: { key: "documents:viewer.languages.names.julia" },
    just: { key: "documents:viewer.languages.names.just" },
    kdl: { key: "documents:viewer.languages.names.kdl" },
    kotlin: { key: "documents:viewer.languages.names.kotlin" },
    kusto: { key: "documents:viewer.languages.names.kusto" },
    latex: { key: "documents:viewer.languages.names.latex" },
    lean: { key: "documents:viewer.languages.names.lean" },
    less: { key: "documents:viewer.languages.names.less" },
    liquid: { key: "documents:viewer.languages.names.liquid" },
    llvm: { key: "documents:viewer.languages.names.llvm" },
    log: { key: "documents:viewer.languages.names.log" },
    logo: { key: "documents:viewer.languages.names.logo" },
    lua: { key: "documents:viewer.languages.names.lua" },
    luau: { key: "documents:viewer.languages.names.luau" },
    make: { key: "documents:viewer.languages.names.make" },
    markdown: { key: "documents:viewer.languages.names.markdown" },
    marko: { key: "documents:viewer.languages.names.marko" },
    matlab: { key: "documents:viewer.languages.names.matlab" },
    mdc: { key: "documents:viewer.languages.names.mdc" },
    mdx: { key: "documents:viewer.languages.names.mdx" },
    mermaid: { key: "documents:viewer.languages.names.mermaid" },
    mipsasm: { key: "documents:viewer.languages.names.mipsasm" },
    mojo: { key: "documents:viewer.languages.names.mojo" },
    moonbit: { key: "documents:viewer.languages.names.moonbit" },
    move: { key: "documents:viewer.languages.names.move" },
    narrat: { key: "documents:viewer.languages.names.narrat" },
    nextflow: { key: "documents:viewer.languages.names.nextflow" },
    "nextflow-groovy": { key: "documents:viewer.languages.names.nextflowGroovy" },
    nginx: { key: "documents:viewer.languages.names.nginx" },
    nim: { key: "documents:viewer.languages.names.nim" },
    nix: { key: "documents:viewer.languages.names.nix" },
    nushell: { key: "documents:viewer.languages.names.nushell" },
    "objective-c": { key: "documents:viewer.languages.names.objectiveC" },
    "objective-cpp": { key: "documents:viewer.languages.names.objectiveCpp" },
    ocaml: { key: "documents:viewer.languages.names.ocaml" },
    odin: { key: "documents:viewer.languages.names.odin" },
    openscad: { key: "documents:viewer.languages.names.openscad" },
    pascal: { key: "documents:viewer.languages.names.pascal" },
    perl: { key: "documents:viewer.languages.names.perl" },
    php: { key: "documents:viewer.languages.names.php" },
    pkl: { key: "documents:viewer.languages.names.pkl" },
    plsql: { key: "documents:viewer.languages.names.plsql" },
    po: { key: "documents:viewer.languages.names.po" },
    polar: { key: "documents:viewer.languages.names.polar" },
    postcss: { key: "documents:viewer.languages.names.postcss" },
    powerquery: { key: "documents:viewer.languages.names.powerquery" },
    powershell: { key: "documents:viewer.languages.names.powershell" },
    prisma: { key: "documents:viewer.languages.names.prisma" },
    prolog: { key: "documents:viewer.languages.names.prolog" },
    proto: { key: "documents:viewer.languages.names.proto" },
    pug: { key: "documents:viewer.languages.names.pug" },
    puppet: { key: "documents:viewer.languages.names.puppet" },
    purescript: { key: "documents:viewer.languages.names.purescript" },
    python: { key: "documents:viewer.languages.names.python" },
    qml: { key: "documents:viewer.languages.names.qml" },
    qmldir: { key: "documents:viewer.languages.names.qmldir" },
    qss: { key: "documents:viewer.languages.names.qss" },
    r: { key: "documents:viewer.languages.names.r" },
    racket: { key: "documents:viewer.languages.names.racket" },
    raku: { key: "documents:viewer.languages.names.raku" },
    razor: { key: "documents:viewer.languages.names.razor" },
    reg: { key: "documents:viewer.languages.names.reg" },
    regexp: { key: "documents:viewer.languages.names.regexp" },
    rel: { key: "documents:viewer.languages.names.rel" },
    riscv: { key: "documents:viewer.languages.names.riscv" },
    ron: { key: "documents:viewer.languages.names.ron" },
    rosmsg: { key: "documents:viewer.languages.names.rosmsg" },
    rst: { key: "documents:viewer.languages.names.rst" },
    ruby: { key: "documents:viewer.languages.names.ruby" },
    rust: { key: "documents:viewer.languages.names.rust" },
    sas: { key: "documents:viewer.languages.names.sas" },
    sass: { key: "documents:viewer.languages.names.sass" },
    scala: { key: "documents:viewer.languages.names.scala" },
    scheme: { key: "documents:viewer.languages.names.scheme" },
    scss: { key: "documents:viewer.languages.names.scss" },
    sdbl: { key: "documents:viewer.languages.names.sdbl" },
    shaderlab: { key: "documents:viewer.languages.names.shaderlab" },
    shellscript: { key: "documents:viewer.languages.names.shellscript" },
    shellsession: { key: "documents:viewer.languages.names.shellsession" },
    smalltalk: { key: "documents:viewer.languages.names.smalltalk" },
    solidity: { key: "documents:viewer.languages.names.solidity" },
    soy: { key: "documents:viewer.languages.names.soy" },
    sparql: { key: "documents:viewer.languages.names.sparql" },
    splunk: { key: "documents:viewer.languages.names.splunk" },
    sql: { key: "documents:viewer.languages.names.sql" },
    "ssh-config": { key: "documents:viewer.languages.names.sshConfig" },
    stata: { key: "documents:viewer.languages.names.stata" },
    stylus: { key: "documents:viewer.languages.names.stylus" },
    surrealql: { key: "documents:viewer.languages.names.surrealql" },
    svelte: { key: "documents:viewer.languages.names.svelte" },
    swift: { key: "documents:viewer.languages.names.swift" },
    "system-verilog": { key: "documents:viewer.languages.names.systemVerilog" },
    systemd: { key: "documents:viewer.languages.names.systemd" },
    talonscript: { key: "documents:viewer.languages.names.talonscript" },
    tasl: { key: "documents:viewer.languages.names.tasl" },
    tcl: { key: "documents:viewer.languages.names.tcl" },
    templ: { key: "documents:viewer.languages.names.templ" },
    terraform: { key: "documents:viewer.languages.names.terraform" },
    tex: { key: "documents:viewer.languages.names.tex" },
    toml: { key: "documents:viewer.languages.names.toml" },
    "ts-tags": { key: "documents:viewer.languages.names.tsTags" },
    tsv: { key: "documents:viewer.languages.names.tsv" },
    tsx: { key: "documents:viewer.languages.names.tsx" },
    turtle: { key: "documents:viewer.languages.names.turtle" },
    twig: { key: "documents:viewer.languages.names.twig" },
    typescript: { key: "documents:viewer.languages.names.typescript" },
    typespec: { key: "documents:viewer.languages.names.typespec" },
    typst: { key: "documents:viewer.languages.names.typst" },
    v: { key: "documents:viewer.languages.names.v" },
    vala: { key: "documents:viewer.languages.names.vala" },
    vb: { key: "documents:viewer.languages.names.vb" },
    verilog: { key: "documents:viewer.languages.names.verilog" },
    vhdl: { key: "documents:viewer.languages.names.vhdl" },
    viml: { key: "documents:viewer.languages.names.viml" },
    vue: { key: "documents:viewer.languages.names.vue" },
    "vue-html": { key: "documents:viewer.languages.names.vueHtml" },
    "vue-vine": { key: "documents:viewer.languages.names.vueVine" },
    vyper: { key: "documents:viewer.languages.names.vyper" },
    wasm: { key: "documents:viewer.languages.names.wasm" },
    wenyan: { key: "documents:viewer.languages.names.wenyan" },
    wgsl: { key: "documents:viewer.languages.names.wgsl" },
    wikitext: { key: "documents:viewer.languages.names.wikitext" },
    wit: { key: "documents:viewer.languages.names.wit" },
    wolfram: { key: "documents:viewer.languages.names.wolfram" },
    xml: { key: "documents:viewer.languages.names.xml" },
    xsl: { key: "documents:viewer.languages.names.xsl" },
    yaml: { key: "documents:viewer.languages.names.yaml" },
    zenscript: { key: "documents:viewer.languages.names.zenscript" },
    zig: { key: "documents:viewer.languages.names.zig" },
  },
} as const satisfies {
  code: MessageDescriptor;
  text: MessageDescriptor;
  names: Record<CanonicalLanguageId, MessageDescriptor>;
};

/** A lazily-imported grammar module: the Shiki import thunk's default export is
 *  the grammar registration array Shiki's `loadLanguage` accepts. */
type GrammarModule = { default: LanguageRegistration[] };
type BundledLanguageId = keyof typeof bundledLanguages;

/** A resolved grammar: the Shiki language id and its lazy loader. */
export interface GrammarSpec {
  /** The Shiki grammar id (the registered language name). */
  id: CanonicalLanguageId;
  /** The lazy Shiki import producing the grammar registration. */
  load: () => Promise<GrammarModule>;
}

const BUNDLED_LANGUAGE_KEYS = new Set(Object.keys(bundledLanguages));

const HINT_ALIASES: Record<string, string> = Object.fromEntries(
  bundledLanguagesInfo.flatMap((info) => [
    [info.id, info.id],
    ...(info.aliases ?? []).map((alias) => [alias, info.id]),
  ]),
);

const EXTENSION_HINTS: Record<string, string> = {
  rs: "rust",
  py: "python",
  pyi: "python",
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  jsx: "jsx",
  tsx: "tsx",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "fish",
  bat: "batch",
  cmd: "batch",
  ps1: "powershell",
  psm1: "powershell",
  psd1: "powershell",
  c: "c",
  h: "c",
  cc: "cpp",
  cpp: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hxx: "cpp",
  cs: "csharp",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  go: "go",
  rb: "ruby",
  php: "php",
  lua: "lua",
  pl: "perl",
  pm: "perl",
  r: "r",
  swift: "swift",
  zig: "zig",
  dart: "dart",
  ex: "elixir",
  exs: "elixir",
  scala: "scala",
  json: "json",
  jsonc: "jsonc",
  json5: "json5",
  jsonl: "jsonl",
  toml: "toml",
  yml: "yaml",
  yaml: "yaml",
  md: "markdown",
  markdown: "markdown",
  mdx: "mdx",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  html: "html",
  htm: "html",
  xml: "xml",
  svg: "xml",
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  dockerfile: "dockerfile",
  env: "dotenv",
  ini: "ini",
  cfg: "ini",
  conf: "ini",
  properties: "properties",
  csv: "csv",
  tsv: "tsv",
  diff: "diff",
  patch: "diff",
  hcl: "hcl",
  tf: "terraform",
  tfvars: "terraform",
  proto: "proto",
  protobuf: "proto",
  rsx: "rust",
};

const BASENAME_HINTS: Record<string, string> = {
  dockerfile: "dockerfile",
  makefile: "makefile",
  justfile: "just",
  "cargo.lock": "toml",
  "uv.lock": "toml",
  "poetry.lock": "toml",
  gemfile: "ruby",
  rakefile: "ruby",
  jenkinsfile: "groovy",
  "cmakelists.txt": "cmake",
};

function normalizeHint(hint: string): string | null {
  const normalized = hint
    .trim()
    .toLowerCase()
    .replace(/^language-/, "")
    .split(/\s+/, 1)[0];
  if (!normalized) return null;
  return HINT_ALIASES[normalized] ?? normalized;
}

function bundledLoader(id: CanonicalLanguageId): (() => Promise<GrammarModule>) | null {
  if (!BUNDLED_LANGUAGE_KEYS.has(id)) return null;
  return bundledLanguages[id as BundledLanguageId] as () => Promise<GrammarModule>;
}

/**
 * Resolve a `language_hint` (engine wire) or a code-fence info string to a
 * grammar spec, applying Shiki's alias normalization. Returns null for an
 * unknown/absent hint so the viewer renders plain text.
 */
export function resolveGrammar(hint: string | null | undefined): GrammarSpec | null {
  if (!hint) return null;
  const id = normalizeHint(hint);
  if (!id) return null;
  if (!CANONICAL_LANGUAGE_IDS.includes(id as CanonicalLanguageId)) return null;
  const canonicalId = id as CanonicalLanguageId;
  const load = bundledLoader(canonicalId);
  return load ? { id: canonicalId, load } : null;
}

/** Derive a highlighter hint from a served path or review-snippet label. */
export function languageHintFromPath(path: string | null | undefined): string | null {
  if (!path) return null;
  const clean = path.split(/[?#]/, 1)[0]?.trim().toLowerCase();
  if (!clean) return null;
  const leaf = clean.split(/[\\/]/).pop() ?? clean;
  const basenameHint = BASENAME_HINTS[leaf];
  if (basenameHint) return basenameHint;
  const dot = leaf.lastIndexOf(".");
  if (dot < 0 || dot === leaf.length - 1) return null;
  return EXTENSION_HINTS[leaf.slice(dot + 1)] ?? null;
}

export function languageDisplayDescriptor(
  hint: string | null | undefined,
  fallback: "code" | "text",
): MessageDescriptor {
  const grammar = resolveGrammar(hint);
  return grammar === null
    ? LANGUAGE_DISPLAY_MESSAGES[fallback]
    : LANGUAGE_DISPLAY_MESSAGES.names[grammar.id];
}

export function supportedLanguageIds(): BundledLanguage[] {
  return [...CANONICAL_LANGUAGE_IDS, ...BUNDLED_LANGUAGE_ALIAS_IDS];
}
