export const ltrAgentResources = {
  sendComment: "Envoyer à l’assistant",
  autonomy: {
    label: "Autonomie",
    reviewEach: "Vérifier chaque modification",
    applyAutomatically: "Appliquer automatiquement",
  },
  actions: {
    openPanel: "Ouvrir le panneau de l’assistant",
    closePanel: "Fermer le panneau de l’assistant",
    togglePanel: "Ouvrir ou fermer le panneau de l’assistant",
    stopRun: "Terminer la conversation",
    newSession: "Démarrer une nouvelle session de l’assistant",
  },
  autonomyBanner: {
    dismiss: "Masquer l’avertissement d’autonomie",
    warning:
      "L’application automatique est active. Les modifications sont appliquées sans révision.",
  },
  begin: {
    headline: "Que devons-nous exécuter sur {{workspace}} ?",
    headlineUnbound: "Que devons-nous exécuter ?",
    recentsLabel: "Conversations récentes",
    seeds: {
      build: "Construire ",
      explore: "Explorer ",
      review: "Réviser ",
    },
    starters: {
      build: "Construire",
      explore: "Explorer",
      review: "Réviser",
    },
    startersLabel: "Manières de commencer",
  },
  clarification: {
    answerPlaceholder: "Saisissez votre réponse",
    failed: "La réponse n’a pas pu être envoyée. Réessayez.",
    recapTitle: "RÉPONDU",
    region: "Question de l’exécution",
    required: "Obligatoire",
    submit: "Envoyer la réponse",
    title: "L’exécution attend une décision",
  },
  runHeader: {
    elapsed: "Écoulé {{elapsed}}",
    mixedProvider: "Fournisseurs mixtes",
    phase: "Phase : {{phase}}",
    region: "État de l’exécution",
    roster: "AGENTS",
  },
  pending: {
    hide: "Masquer les modifications en attente",
    label: "Modifications en attente",
    show: "Afficher les modifications en attente",
    unavailable: "Modifications en attente indisponibles",
  },
  panel: {
    region: "Assistant",
    sessionsMenu: "Sessions",
    newSession: "Nouvelle session",
    recentSessions: "Sessions récentes",
    untitledSession: "Session sans titre",
    close: "Fermer le panneau de l’assistant",
  },
  transcript: {
    loading: "Chargement de la conversation…",
    empty: "Aucun message pour l’instant.",
    error:
      "Cette conversation n’a pas pu être chargée. Elle a peut-être expiré. Ouvrez une nouvelle session.",
    showingRecent: "Affichage des messages les plus récents.",
    timeline: "Chronologie du travail",
    usedTools_many: "{{count, number}} outils utilisés",
    usedTools_one: "{{count, number}} outil utilisé",
    usedTools_other: "{{count, number}} outils utilisés",
    workedFor: "Travail pendant {{elapsed}}",
    thinking: "Réflexion",
    thinkingDuration: "Réflexion ({{seconds, number}} s)",
    toolInput: "Entrée",
    toolResult: "Résultat",
    toolStatus: {
      done: "Terminé",
      needsPermission: "Autorisation requise",
      allowed: "Autorisé",
      denied: "Refusé",
      notAllowed: "Non autorisé",
    },
    turnStatus: {
      working: "En cours…",
      stopping: "Arrêt en cours…",
      done: "Terminé",
      stopped: "Arrêté",
      failed: "Échec",
    },
    permissionQuestion: "Autoriser {{tool}} à s’exécuter ?",
    allow: "Autoriser",
    deny: "Refuser",
    permissionFailed: "La décision n’a pas pu être enregistrée. Réessayez.",
  },
  composer: {
    placeholder: "Écrire à l’assistant",
    clarificationParked: "Répondez à la question ci-dessus pour continuer",
    steerPlaceholder: "Répondez pour orienter l’assistant en cours",
    send: "Envoyer",
    sendFailed: "Le message n’a pas pu être envoyé. Réessayez.",
    attachContext: "Ajouter une fonctionnalité ou un document",
    attachedContext: "Contexte joint",
    evidenceAria: "Joindre un fichier comme preuve",
    evidenceEmpty: "Aucun fichier correspondant.",
    evidencePlaceholder: "Rechercher des fichiers par chemin",
    queuedChip: "Prochain message",
    removeQueued: "Retirer le message en attente",
    mentionPlaceholder: "Rechercher des fonctionnalités et des documents",
    mentionAria: "Joindre une fonctionnalité ou un document",
    mentionEmpty: "Aucune fonctionnalité ni aucun document correspondant.",
    removeMention: "Retirer {{label}}",
    commentBatch_many: "{{count, number}} commentaires",
    commentBatch_one: "{{count, number}} commentaire",
    commentBatch_other: "{{count, number}} commentaires",
    removeComments: "Retirer les commentaires joints",
    slashAria: "Commandes",
    slashEmpty: "Aucune commande correspondante.",
    selectorValue: "{{selector}} : {{value}}",
    selectorDisabled: "{{selector}} : {{value}}. {{reason}}",
    model: "Modèle",
    modelDefault: "Par défaut",
    modelUnavailable: "Utilisation du modèle par défaut.",
    team: "Équipe",
    teamDefault: "Assistant seul",
    teamUnavailable: "Utilisation d’un seul assistant.",
    feature: "Fonctionnalité",
    featureUnset: "Non défini",
    featureUnbound: "Choisissez une fonctionnalité avant de démarrer cette exécution.",
    featureFromDocument: "D’après le document ouvert : {{feature}}",
    featurePlaceholder: "Rechercher des fonctionnalités",
    featureEmpty: "Aucune fonctionnalité correspondante.",
    featureMenuAria: "Sélectionner la fonctionnalité de cette exécution",
    modelMenuAria: "Sélectionner un profil de modèle",
    teamMenuAria: "Sélectionner une équipe d’assistants",
    teamPresetUnavailable: "Cette équipe ne peut pas être chargée.",
    startTeamRun: "Démarrer l’équipe",
    cancelTeamRun: "Arrêter l’exécution de l’équipe",
    teamRunPhase: "Exécution de l’équipe : {{phase}}",
    teamRunRefused:
      "L’exécution de l’équipe n’a pas pu démarrer. Vérifiez l’état de l’équipe, puis réessayez.",
    teamRunDegraded: "Récupération de l’état de l’exécution…",
    teamRunDismiss: "Fermer",
    teamRunLocked: "Une exécution est en cours.",
  },
  chip: {
    working: "Assistant en cours",
    label: "Assistant en cours, {{state}}",
    status: {
      active: "En cours",
      cancelRequested: "Arrêt en cours",
    },
  },
  pendingBridge: {
    count_many: "{{count, number}} autres modifications en attente",
    count_one: "{{count, number}} autre modification en attente",
    count_other: "{{count, number}} autres modifications en attente",
    more: "Plus de modifications en attente",
  },
} as const;

export const rtlAgentResources = {
  sendComment: "إرسال إلى المساعد",
  autonomy: {
    label: "الاستقلالية",
    reviewEach: "مراجعة كل تغيير",
    applyAutomatically: "تطبيق تلقائي",
  },
  actions: {
    openPanel: "فتح لوحة المساعد",
    closePanel: "إغلاق لوحة المساعد",
    togglePanel: "فتح أو إغلاق لوحة المساعد",
    stopRun: "إنهاء المحادثة",
    newSession: "بدء جلسة مساعد جديدة",
  },
  autonomyBanner: {
    dismiss: "تجاهل تحذير الاستقلالية",
    warning: "التطبيق التلقائي مفعّل. يطبّق المساعد تغييراته دون سؤالك.",
  },
  begin: {
    headline: "ما الذي ينبغي تشغيله على {{workspace}}؟",
    headlineUnbound: "ما الذي ينبغي تشغيله؟",
    recentsLabel: "المحادثات الأخيرة",
    seeds: {
      build: "ابنِ ",
      explore: "استكشف ",
      review: "راجع ",
    },
    starters: {
      build: "ابنِ",
      explore: "استكشف",
      review: "راجع",
    },
    startersLabel: "طرق البدء",
  },
  clarification: {
    answerPlaceholder: "اكتب إجابتك",
    failed: "تعذّر إرسال الإجابة. حاول مرة أخرى.",
    recapTitle: "تمت الإجابة",
    region: "سؤال من التشغيل",
    required: "مطلوب",
    submit: "إرسال الإجابة",
    title: "التشغيل بحاجة إلى قرار",
  },
  runHeader: {
    elapsed: "المنقضي {{elapsed}}",
    mixedProvider: "مزودون مختلطون",
    phase: "المرحلة: {{phase}}",
    region: "حالة التشغيل",
    roster: "الوكلاء",
  },
  pending: {
    hide: "إخفاء التغييرات المعلقة",
    label: "التغييرات المعلقة",
    show: "إظهار التغييرات المعلقة",
    unavailable: "التغييرات المعلقة غير متاحة",
  },
  panel: {
    region: "المساعد",
    sessionsMenu: "الجلسات",
    newSession: "جلسة جديدة",
    recentSessions: "الجلسات الأخيرة",
    untitledSession: "جلسة بلا عنوان",
    close: "إغلاق لوحة المساعد",
  },
  transcript: {
    loading: "جارٍ تحميل المحادثة…",
    empty: "لا توجد رسائل بعد.",
    error: "تعذّر تحميل هذه المحادثة. ربما انتهت صلاحيتها. افتح جلسة جديدة.",
    showingRecent: "عرض أحدث الرسائل.",
    timeline: "الجدول الزمني للعمل",
    usedTools_few: "استُخدمت {{count, number}} أدوات",
    usedTools_many: "استُخدمت {{count, number}} أداة",
    usedTools_one: "استُخدمت {{count, number}} أداة",
    usedTools_other: "استُخدمت {{count, number}} أداة",
    usedTools_two: "استُخدمت {{count, number}} أداتان",
    usedTools_zero: "استُخدمت {{count, number}} أداة",
    workedFor: "عمل لمدة {{elapsed}}",
    thinking: "تفكير",
    thinkingDuration: "تفكير ({{seconds, number}} ث)",
    toolInput: "الإدخال",
    toolResult: "النتيجة",
    toolStatus: {
      done: "تم",
      needsPermission: "يتطلب إذنًا",
      allowed: "مسموح",
      denied: "مرفوض",
      notAllowed: "غير مسموح",
    },
    turnStatus: {
      working: "جارٍ العمل…",
      stopping: "جارٍ الإيقاف…",
      done: "تم",
      stopped: "متوقف",
      failed: "فشل",
    },
    permissionQuestion: "السماح لـ {{tool}} بالتشغيل؟",
    allow: "سماح",
    deny: "رفض",
    permissionFailed: "تعذّر حفظ القرار. حاول مرة أخرى.",
  },
  composer: {
    placeholder: "راسل المساعد",
    clarificationParked: "أجب عن السؤال أعلاه لمتابعة التشغيل",
    steerPlaceholder: "أجب لتوجيه المساعد أثناء عمله",
    send: "إرسال",
    sendFailed: "تعذّر إرسال الرسالة. حاول مرة أخرى.",
    attachContext: "إضافة ميزة أو مستند",
    attachedContext: "السياق المرفق",
    evidenceAria: "إرفاق ملف كدليل",
    evidenceEmpty: "لا توجد ملفات مطابقة.",
    evidencePlaceholder: "ابحث عن الملفات بالمسار",
    queuedChip: "الرسالة التالية",
    removeQueued: "إزالة الرسالة المنتظرة",
    mentionPlaceholder: "البحث في الميزات والمستندات",
    mentionAria: "إرفاق ميزة أو مستند",
    mentionEmpty: "لا توجد ميزات أو مستندات مطابقة.",
    removeMention: "إزالة {{label}}",
    commentBatch_few: "{{count, number}} تعليقات",
    commentBatch_many: "{{count, number}} تعليقًا",
    commentBatch_one: "{{count, number}} تعليق",
    commentBatch_other: "{{count, number}} تعليق",
    commentBatch_two: "{{count, number}} تعليقان",
    commentBatch_zero: "{{count, number}} تعليق",
    removeComments: "إزالة التعليقات المرفقة",
    slashAria: "الأوامر",
    slashEmpty: "لا توجد أوامر مطابقة.",
    selectorValue: "{{selector}}: {{value}}",
    selectorDisabled: "{{selector}}: {{value}}. {{reason}}",
    model: "النموذج",
    modelDefault: "افتراضي",
    modelUnavailable: "استخدام النموذج الافتراضي.",
    team: "الفريق",
    teamDefault: "مساعد واحد",
    teamUnavailable: "استخدام مساعد واحد.",
    feature: "الميزة",
    featureUnset: "غير محدد",
    featureUnbound: "اختر ميزة قبل بدء هذا التشغيل.",
    featureFromDocument: "من المستند المفتوح: {{feature}}",
    featurePlaceholder: "ابحث في الميزات",
    featureEmpty: "لا توجد ميزات مطابقة.",
    featureMenuAria: "اختر الميزة التي يعمل عليها هذا التشغيل",
    modelMenuAria: "اختر ملف نموذج",
    teamMenuAria: "اختر فريق مساعدين",
    teamPresetUnavailable: "تعذّر تحميل هذا الفريق.",
    startTeamRun: "بدء الفريق",
    cancelTeamRun: "إيقاف تشغيل الفريق",
    teamRunPhase: "تشغيل الفريق: {{phase}}",
    teamRunRefused: "تعذّر بدء تشغيل الفريق. تحقّق من حالة الفريق ثم أعد المحاولة.",
    teamRunDegraded: "جارٍ استرداد حالة التشغيل…",
    teamRunDismiss: "إغلاق",
    teamRunLocked: "هناك تشغيل قيد التنفيذ.",
  },
  chip: {
    working: "المساعد يعمل",
    label: "المساعد يعمل، {{state}}",
    status: {
      active: "قيد التشغيل",
      cancelRequested: "جارٍ الإيقاف",
    },
  },
  pendingBridge: {
    count_few: "{{count, number}} تغييرات معلقة أخرى",
    count_many: "{{count, number}} تغييرًا معلقًا آخر",
    count_one: "{{count, number}} تغيير معلق آخر",
    count_other: "{{count, number}} تغيير معلق آخر",
    count_two: "{{count, number}} تغييران معلقان آخران",
    count_zero: "{{count, number}} تغيير معلق",
    more: "المزيد من التغييرات المعلقة",
  },
} as const;
