export const ltrAgentResources = {
  actions: {
    openPanel: "Ouvrir le panneau de l’assistant",
    closePanel: "Fermer le panneau de l’assistant",
    togglePanel: "Ouvrir ou fermer le panneau de l’assistant",
    stopRun: "Terminer la conversation",
    newSession: "Démarrer une nouvelle session de l’assistant",
  },
  panel: {
    region: "Assistant",
    sessionsMenu: "Sessions",
    newSession: "Nouvelle session",
    recentSessions: "Sessions récentes",
    untitledSession: "Session sans titre",
    close: "Fermer le panneau de l’assistant",
  },
  transcript: {
    loading: "Chargement de la conversation…",
    empty: "Aucun message pour l’instant.",
    noSession: "Écrivez à l’assistant pour démarrer une conversation.",
    error:
      "Cette conversation n’a pas pu être chargée. Elle a peut-être expiré. Ouvrez une nouvelle session.",
  },
  composer: {
    placeholder: "Écrire à l’assistant",
    steerPlaceholder: "Répondez pour orienter l’assistant en cours",
    send: "Envoyer",
    stop: "Terminer la conversation",
    sendFailed: "Le message n’a pas pu être envoyé. Réessayez.",
    attachedContext: "Contexte joint",
    queuedChip: "Prochain message",
    removeQueued: "Retirer le message en attente",
    mentionPlaceholder: "Rechercher des fonctionnalités et des documents",
    mentionAria: "Joindre une fonctionnalité ou un document",
    mentionEmpty: "Aucune fonctionnalité ni aucun document correspondant.",
    removeMention: "Retirer {{label}}",
    commentBatch_many: "{{count, number}} commentaires",
    commentBatch_one: "{{count, number}} commentaire",
    commentBatch_other: "{{count, number}} commentaires",
    removeComments: "Retirer les commentaires joints",
    slashAria: "Commandes",
    slashEmpty: "Aucune commande correspondante.",
    selectorValue: "{{selector}} : {{value}}",
    selectorDisabled: "{{selector}} : {{value}}. {{reason}}",
    model: "Modèle",
    modelDefault: "Par défaut",
    modelUnavailable: "Utilisation du modèle par défaut.",
    team: "Équipe",
    teamDefault: "Assistant seul",
    teamUnavailable: "Utilisation d’un seul assistant.",
  },
  chip: {
    working: "Assistant en cours",
    label: "Assistant en cours, {{state}}",
    status: {
      active: "En cours",
      cancelRequested: "Arrêt en cours",
    },
  },
} as const;

export const rtlAgentResources = {
  actions: {
    openPanel: "فتح لوحة المساعد",
    closePanel: "إغلاق لوحة المساعد",
    togglePanel: "فتح أو إغلاق لوحة المساعد",
    stopRun: "إنهاء المحادثة",
    newSession: "بدء جلسة مساعد جديدة",
  },
  panel: {
    region: "المساعد",
    sessionsMenu: "الجلسات",
    newSession: "جلسة جديدة",
    recentSessions: "الجلسات الأخيرة",
    untitledSession: "جلسة بلا عنوان",
    close: "إغلاق لوحة المساعد",
  },
  transcript: {
    loading: "جارٍ تحميل المحادثة…",
    empty: "لا توجد رسائل بعد.",
    noSession: "راسل المساعد لبدء محادثة.",
    error: "تعذّر تحميل هذه المحادثة. ربما انتهت صلاحيتها. افتح جلسة جديدة.",
  },
  composer: {
    placeholder: "راسل المساعد",
    steerPlaceholder: "أجب لتوجيه المساعد أثناء عمله",
    send: "إرسال",
    stop: "إنهاء المحادثة",
    sendFailed: "تعذّر إرسال الرسالة. حاول مرة أخرى.",
    attachedContext: "السياق المرفق",
    queuedChip: "الرسالة التالية",
    removeQueued: "إزالة الرسالة المنتظرة",
    mentionPlaceholder: "البحث في الميزات والمستندات",
    mentionAria: "إرفاق ميزة أو مستند",
    mentionEmpty: "لا توجد ميزات أو مستندات مطابقة.",
    removeMention: "إزالة {{label}}",
    commentBatch_few: "{{count, number}} تعليقات",
    commentBatch_many: "{{count, number}} تعليقًا",
    commentBatch_one: "{{count, number}} تعليق",
    commentBatch_other: "{{count, number}} تعليق",
    commentBatch_two: "{{count, number}} تعليقان",
    commentBatch_zero: "{{count, number}} تعليق",
    removeComments: "إزالة التعليقات المرفقة",
    slashAria: "الأوامر",
    slashEmpty: "لا توجد أوامر مطابقة.",
    selectorValue: "{{selector}}: {{value}}",
    selectorDisabled: "{{selector}}: {{value}}. {{reason}}",
    model: "النموذج",
    modelDefault: "افتراضي",
    modelUnavailable: "استخدام النموذج الافتراضي.",
    team: "الفريق",
    teamDefault: "مساعد واحد",
    teamUnavailable: "استخدام مساعد واحد.",
  },
  chip: {
    working: "المساعد يعمل",
    label: "المساعد يعمل، {{state}}",
    status: {
      active: "قيد التشغيل",
      cancelRequested: "جارٍ الإيقاف",
    },
  },
} as const;
