import { ltrCanvasResources, rtlCanvasResources } from "./canvasStateResources";
import { ltrThreeLabResources, rtlThreeLabResources } from "./threeLabResources";

export const ltrGraphResources = {
  accessibility: {
    canvas:
      "Canevas du graphe. Utilisez les flèches pour vous déplacer, Entrée pour ouvrir et E pour développer.",
    selectedItem: "Élément sélectionné : {{item}}.",
    selectedItemGeneric: "Élément sélectionné.",
    workingSet: "Ensemble de travail",
    workingSetCount_many: "{{count, number}} éléments dans l’ensemble de travail",
    workingSetCount_one: "{{count, number}} élément dans l’ensemble de travail",
    workingSetCount_other: "{{count, number}} éléments dans l’ensemble de travail",
    hiddenByActiveFilter: "Masqué par le filtre actif",
    namedWorkingSetItemHidden: "{{item}} est masqué par le filtre actif.",
    workingSetItemHidden: "L’élément est masqué par le filtre actif.",
  },
  actions: {
    addItemToWorkingSet: "Ajouter l’élément à l’ensemble de travail",
    addSelectedItemToWorkingSet:
      "Ajouter l’élément sélectionné à l’ensemble de travail",
    clearSelection: "Effacer la sélection du graphe",
    clearWorkingSet: "Effacer l’ensemble de travail",
    expandFocusedItem: "Développer l’élément actif dans l’espace de travail",
    fitToView: "Adapter le graphe à la vue",
    keepInView: "Garder le graphe visible",
    moveToNextConnectedItem: "Passer à l’élément connecté suivant",
    moveToPreviousConnectedItem: "Passer à l’élément connecté précédent",
    openFocusedItem: "Ouvrir l’élément actif",
    pauseMovement: "Suspendre le mouvement du graphe",
    pinItem: "Épingler l’élément",
    resetSettings: "Réinitialiser les paramètres du graphe",
    resetView: "Réinitialiser la vue du graphe",
    rearrangeAfterFiltering: "Réorganiser après le filtrage",
    removeItemFromWorkingSet: "Retirer l’élément de l’ensemble de travail",
    removeNamedItemFromWorkingSet: "Retirer {{item}} de l’ensemble de travail",
    removeLastItemFromWorkingSet: "Retirer le dernier élément de l’ensemble de travail",
    resumeMovement: "Reprendre le mouvement du graphe",
    showRelatedItem: "Afficher l’élément associé",
    showStartingItem: "Afficher l’élément de départ",
    unpinItem: "Désépingler l’élément",
    zoomIn: "Agrandir",
    zoomOut: "Réduire",
  },
  controls: {
    accessibility: {
      edgeColorMode: "Mode de couleur des liens",
      navigation: "Parcourir le graphe",
      nodeColorMode: "Mode de couleur des éléments",
      nodeLevel: "Détail du graphe",
      showNodeIcons: "Afficher les icônes des éléments",
    },
    descriptions: {
      charge: "Augmentez ou réduisez l’espace entre les éléments.",
      documentLevel: "Affichez chaque document comme un élément distinct.",
      edgeColorMode: "Choisissez comment les liens utilisent la couleur.",
      edgeOpacityMax: "Modifiez la visibilité des liens les plus forts.",
      edgeWidthMax: "Modifiez l’épaisseur des liens les plus forts.",
      featureLevel: "Regroupez les documents associés par fonctionnalité.",
      granularity:
        "Regroupez les documents associés par fonctionnalité ou affichez chaque document.",
      keepInView: "Gardez le graphe visible pendant ses changements.",
      keepLayoutFixed: "Empêchez les éléments de bouger.",
      linkDistance: "Modifiez la distance entre les éléments connectés.",
      linkStrength: "Modifiez la proximité des éléments connectés.",
      nodeColorMode: "Choisissez comment les éléments utilisent la couleur.",
      nodeIcons: "Affichez une icône de document pour chaque élément.",
      nodeSalienceScale: "Mettez en valeur les éléments les plus connectés.",
      nodeSizeScale: "Modifiez la taille de chaque élément.",
      rearrangeAfterFiltering: "Réorganisez les éléments restants après le filtrage.",
      settingUnavailableInHistory:
        "Ce paramètre est indisponible pendant la consultation de l’historique.",
    },
    labels: {
      charge: "Espacement",
      edgeColorMode: "Couleur des liens",
      edgeOpacityMax: "Opacité des liens",
      edgeWidthMax: "Épaisseur des liens",
      keepLayoutFixed: "Garder la disposition fixe",
      linkDistance: "Longueur des liens",
      linkStrength: "Regroupement",
      nodeColorMode: "Couleur des éléments",
      nodeIcons: "Afficher les icônes",
      nodeSalienceScale: "Importance",
      nodeSizeScale: "Taille des éléments",
    },
    options: {
      blended: "Dégradé",
      category: "Catégorie",
      documents: "Documents",
      features: "Fonctionnalités",
      recency: "Récence",
      solid: "Uni",
    },
    sections: { appearance: "Apparence", layout: "Disposition", show: "Afficher" },
    title: "Commandes du graphe",
  },
  canvas: ltrCanvasResources,
  filters: {
    accessibility: { panel: "Filtres de documents" },
    actions: {
      clearAll: "Tout effacer",
      reset: "Réinitialiser les filtres",
      showResults: "Afficher les résultats",
    },
    edited: {
      any: "À tout moment",
      lastSevenDays: "7 derniers jours",
      lastThirtyDays: "30 derniers jours",
      thisYear: "Cette année",
    },
    health: {
      dangling: "Destination manquante",
      emptyScaffold: "Document vide",
      invalid: "Détails incomplets",
      orphaned: "Non lié",
    },
    options: {
      adr: "Décisions",
      audit: "Revues",
      exec: "Étapes",
      plan: "Plans",
      reference: "Références",
      research: "Recherche",
      summary: "Résumés",
    },
    search: { features: "Rechercher des fonctionnalités" },
    sections: {
      decisionStatus: "État de la décision",
      edited: "Modifié",
      feature: "Fonctionnalité",
      health: "Santé",
      kind: "Type",
      planStatus: "État du plan",
    },
    states: {
      empty: "Aucun choix de filtre disponible.",
      loading: "Chargement des choix de filtre…",
    },
    statuses: {
      accepted: "Accepté",
      active: "Actif",
      archived: "Archivé",
      complete: "Terminé",
      deprecated: "Obsolète",
      draft: "Brouillon",
      finished: "Terminé",
      inProgress: "En cours",
      notStarted: "Non commencé",
      proposed: "Proposé",
      rejected: "Rejeté",
    },
    compactTitle: "Filtres",
    title: "Filtrer les documents",
  },
  lab: ltrThreeLabResources,
  disabledReasons: {
    chooseConnectionWithSummary: "Choisissez une connexion avec un résumé à copier.",
    chooseItemWithTitle: "Choisissez un élément avec un titre à copier.",
    relatedItemUnavailable:
      "Actualisez les données, puis réessayez d’afficher l’élément associé.",
    startingItemUnavailable:
      "Actualisez les données, puis réessayez d’afficher l’élément de départ.",
  },
  legend: {
    accessibility: {
      documentTypeFilters: "Filtres par type de document",
      moduleColors: "Couleurs des modules de code",
      recencyScale: "Échelle de récence du code",
    },
    actions: {
      addDocumentTypeFilter: "Ajouter le filtre {{documentType}}",
      clearDocumentTypeFilters: "Effacer les filtres",
      hideDocumentTypeLabels: "Masquer les libellés des types de document",
      hideModuleLabels: "Masquer les libellés des modules",
      removeDocumentTypeFilter: "Retirer le filtre {{documentType}}",
      showDocumentTypeLabels: "Afficher les libellés des types de document",
      showModuleLabels: "Afficher les libellés des modules",
    },
    labels: {
      older: "Plus ancien",
      recent: "Récent",
    },
  },
  islands: {
    labels: { status: "État", type: "Type" },
    progress: {
      stepsComplete_many: "{{done, number}} étapes sur {{count, number}} terminées",
      stepsComplete_one: "{{done, number}} étape sur {{count, number}} terminée",
      stepsComplete_other: "{{done, number}} étapes sur {{count, number}} terminées",
    },
    states: {
      active: "Actif",
      archived: "Archivé",
      broken: "Attention requise",
      complete: "Terminé",
      featureLoading: "Chargement des documents associés…",
      loading: "Chargement des détails…",
      stale: "Obsolète",
      unavailable:
        "Les détails sont indisponibles. Actualisez les données, puis réessayez.",
    },
  },
  hover: {
    accessibility: {
      detailsFor: "Détails de {{title}}",
      open: "Ouvrir {{title}}",
    },
    evidence: {
      codeLocations_many: "{{count, number}} emplacements de code",
      codeLocations_one: "{{count, number}} emplacement de code",
      codeLocations_other: "{{count, number}} emplacements de code",
      commits_many: "{{count, number}} modifications associées",
      commits_one: "{{count, number}} modification associée",
      commits_other: "{{count, number}} modifications associées",
      documents_many: "{{count, number}} documents associés",
      documents_one: "{{count, number}} document associé",
      documents_other: "{{count, number}} documents associés",
    },
    types: { feature: "Fonctionnalité" },
  },
  shortcutGroups: {
    workingSet: "Ensemble de travail",
  },
  labels: {
    graph: "Graphe",
    item: "Élément",
  },
} as const;

export const rtlGraphResources = {
  accessibility: {
    canvas: "لوحة الرسم البياني. استخدم مفاتيح الأسهم للتنقل وEnter للفتح وE للتوسيع.",
    selectedItem: "تم تحديد {{item}}.",
    selectedItemGeneric: "تم تحديد العنصر.",
    workingSet: "مجموعة العمل",
    workingSetCount_zero: "{{count, number}} عنصر في مجموعة العمل",
    workingSetCount_one: "{{count, number}} عنصر في مجموعة العمل",
    workingSetCount_two: "{{count, number}} من العناصر في مجموعة العمل",
    workingSetCount_few: "{{count, number}} عناصر في مجموعة العمل",
    workingSetCount_many: "{{count, number}} عنصرًا في مجموعة العمل",
    workingSetCount_other: "{{count, number}} عنصر في مجموعة العمل",
    hiddenByActiveFilter: "مخفي بواسطة عامل التصفية النشط",
    namedWorkingSetItemHidden: "{{item}} مخفي بواسطة عامل التصفية النشط.",
    workingSetItemHidden: "العنصر مخفي بواسطة عامل التصفية النشط.",
  },
  actions: {
    addItemToWorkingSet: "إضافة العنصر إلى مجموعة العمل",
    addSelectedItemToWorkingSet: "إضافة العنصر المحدد إلى مجموعة العمل",
    clearSelection: "مسح تحديد الرسم البياني",
    clearWorkingSet: "مسح مجموعة العمل",
    expandFocusedItem: "توسيع العنصر المحدد ضمن مساحة العمل",
    fitToView: "ملاءمة الرسم البياني للعرض",
    keepInView: "إبقاء الرسم البياني ظاهرًا",
    moveToNextConnectedItem: "الانتقال إلى العنصر المتصل التالي",
    moveToPreviousConnectedItem: "الانتقال إلى العنصر المتصل السابق",
    openFocusedItem: "فتح العنصر المحدد",
    pauseMovement: "إيقاف حركة الرسم البياني مؤقتًا",
    pinItem: "تثبيت العنصر",
    resetSettings: "إعادة تعيين إعدادات الرسم البياني",
    resetView: "إعادة تعيين عرض الرسم البياني",
    rearrangeAfterFiltering: "إعادة الترتيب بعد التصفية",
    removeItemFromWorkingSet: "إزالة العنصر من مجموعة العمل",
    removeNamedItemFromWorkingSet: "إزالة {{item}} من مجموعة العمل",
    removeLastItemFromWorkingSet: "إزالة العنصر الأخير من مجموعة العمل",
    resumeMovement: "استئناف حركة الرسم البياني",
    showRelatedItem: "إظهار العنصر المرتبط",
    showStartingItem: "إظهار عنصر البداية",
    unpinItem: "إلغاء تثبيت العنصر",
    zoomIn: "تكبير",
    zoomOut: "تصغير",
  },
  controls: {
    accessibility: {
      edgeColorMode: "نمط ألوان الروابط",
      navigation: "التنقل في الرسم البياني",
      nodeColorMode: "نمط ألوان العناصر",
      nodeLevel: "تفاصيل الرسم البياني",
      showNodeIcons: "إظهار أيقونات العناصر",
    },
    descriptions: {
      charge: "زِد المسافة بين العناصر أو قللها.",
      documentLevel: "اعرض كل مستند كعنصر منفصل.",
      edgeColorMode: "اختر كيفية استخدام الألوان في الروابط.",
      edgeOpacityMax: "غيّر وضوح أقوى الروابط.",
      edgeWidthMax: "غيّر سُمك أقوى الروابط.",
      featureLevel: "اجمع المستندات المرتبطة ضمن ميزات.",
      granularity: "اجمع المستندات المرتبطة ضمن ميزات أو اعرض كل مستند.",
      keepInView: "أبقِ الرسم البياني ظاهرًا أثناء تغيّره.",
      keepLayoutFixed: "امنع العناصر من الحركة.",
      linkDistance: "غيّر المسافة بين العناصر المتصلة.",
      linkStrength: "غيّر مدى تقارب العناصر المتصلة.",
      nodeColorMode: "اختر كيفية استخدام الألوان في العناصر.",
      nodeIcons: "اعرض أيقونة مستند لكل عنصر.",
      nodeSalienceScale: "أبرز العناصر ذات الاتصالات الأكثر.",
      nodeSizeScale: "غيّر حجم كل عنصر.",
      rearrangeAfterFiltering: "أعد ترتيب العناصر المتبقية بعد التصفية.",
      settingUnavailableInHistory: "هذا الإعداد غير متاح أثناء عرض السجل.",
    },
    labels: {
      charge: "التباعد",
      edgeColorMode: "لون الروابط",
      edgeOpacityMax: "وضوح الروابط",
      edgeWidthMax: "سُمك الروابط",
      keepLayoutFixed: "إبقاء التخطيط ثابتًا",
      linkDistance: "طول الروابط",
      linkStrength: "التجميع",
      nodeColorMode: "لون العناصر",
      nodeIcons: "إظهار الأيقونات",
      nodeSalienceScale: "الأهمية",
      nodeSizeScale: "حجم العناصر",
    },
    options: {
      blended: "متدرج",
      category: "الفئة",
      documents: "المستندات",
      features: "الميزات",
      recency: "الأحدث",
      solid: "موحد",
    },
    sections: { appearance: "المظهر", layout: "التخطيط", show: "إظهار" },
    title: "عناصر تحكم الرسم البياني",
  },
  canvas: rtlCanvasResources,
  filters: {
    accessibility: { panel: "عوامل تصفية المستندات" },
    actions: {
      clearAll: "مسح الكل",
      reset: "إعادة تعيين عوامل التصفية",
      showResults: "إظهار النتائج",
    },
    edited: {
      any: "أي وقت",
      lastSevenDays: "آخر 7 أيام",
      lastThirtyDays: "آخر 30 يومًا",
      thisYear: "هذا العام",
    },
    health: {
      dangling: "وجهة مفقودة",
      emptyScaffold: "مستند فارغ",
      invalid: "تفاصيل غير مكتملة",
      orphaned: "غير مرتبط",
    },
    options: {
      adr: "القرارات",
      audit: "المراجعات",
      exec: "الخطوات",
      plan: "الخطط",
      reference: "المراجع",
      research: "البحث",
      summary: "الملخصات",
    },
    search: { features: "البحث عن الميزات" },
    sections: {
      decisionStatus: "حالة القرار",
      edited: "تم التعديل",
      feature: "الميزة",
      health: "السلامة",
      kind: "النوع",
      planStatus: "حالة الخطة",
    },
    states: {
      empty: "لا تتوفر خيارات تصفية.",
      loading: "جارٍ تحميل خيارات التصفية…",
    },
    statuses: {
      accepted: "مقبول",
      active: "نشط",
      archived: "مؤرشف",
      complete: "مكتمل",
      deprecated: "قديم",
      draft: "مسودة",
      finished: "منتهٍ",
      inProgress: "قيد التقدم",
      notStarted: "لم يبدأ",
      proposed: "مقترح",
      rejected: "مرفوض",
    },
    compactTitle: "عوامل التصفية",
    title: "تصفية المستندات",
  },
  lab: rtlThreeLabResources,
  disabledReasons: {
    chooseConnectionWithSummary: "اختر اتصالًا له ملخص لنسخه.",
    chooseItemWithTitle: "اختر عنصرًا له عنوان لنسخه.",
    relatedItemUnavailable: "حدّث البيانات، ثم حاول إظهار العنصر المرتبط مرة أخرى.",
    startingItemUnavailable: "حدّث البيانات، ثم حاول إظهار عنصر البداية مرة أخرى.",
  },
  legend: {
    accessibility: {
      documentTypeFilters: "عوامل التصفية حسب نوع المستند",
      moduleColors: "ألوان وحدات التعليمات البرمجية",
      recencyScale: "مقياس حداثة التعليمات البرمجية",
    },
    actions: {
      addDocumentTypeFilter: "إضافة عامل تصفية {{documentType}}",
      clearDocumentTypeFilters: "مسح عوامل التصفية",
      hideDocumentTypeLabels: "إخفاء تسميات أنواع المستندات",
      hideModuleLabels: "إخفاء تسميات الوحدات",
      removeDocumentTypeFilter: "إزالة عامل تصفية {{documentType}}",
      showDocumentTypeLabels: "إظهار تسميات أنواع المستندات",
      showModuleLabels: "إظهار تسميات الوحدات",
    },
    labels: {
      older: "أقدم",
      recent: "حديث",
    },
  },
  islands: {
    labels: { status: "الحالة", type: "النوع" },
    progress: {
      stepsComplete_zero: "اكتملت {{done, number}} من {{count, number}} خطوة",
      stepsComplete_one: "اكتملت {{done, number}} من {{count, number}} خطوة",
      stepsComplete_two: "اكتملت {{done, number}} من {{count, number}} خطوتين",
      stepsComplete_few: "اكتملت {{done, number}} من {{count, number}} خطوات",
      stepsComplete_many: "اكتملت {{done, number}} من {{count, number}} خطوة",
      stepsComplete_other: "اكتملت {{done, number}} من {{count, number}} خطوة",
    },
    states: {
      active: "نشط",
      archived: "مؤرشف",
      broken: "يحتاج إلى اهتمام",
      complete: "مكتمل",
      featureLoading: "جارٍ تحميل المستندات المرتبطة…",
      loading: "جارٍ تحميل التفاصيل…",
      stale: "قديم",
      unavailable: "التفاصيل غير متاحة. حدّث البيانات، ثم حاول مرة أخرى.",
    },
  },
  hover: {
    accessibility: {
      detailsFor: "تفاصيل {{title}}",
      open: "فتح {{title}}",
    },
    evidence: {
      codeLocations_zero: "{{count, number}} موقع تعليمات برمجية",
      codeLocations_one: "{{count, number}} موقع تعليمات برمجية",
      codeLocations_two: "{{count, number}} موقعا تعليمات برمجية",
      codeLocations_few: "{{count, number}} مواقع تعليمات برمجية",
      codeLocations_many: "{{count, number}} موقع تعليمات برمجية",
      codeLocations_other: "{{count, number}} موقع تعليمات برمجية",
      commits_zero: "{{count, number}} تغيير مرتبط",
      commits_one: "{{count, number}} تغيير مرتبط",
      commits_two: "{{count, number}} تغييران مرتبطان",
      commits_few: "{{count, number}} تغييرات مرتبطة",
      commits_many: "{{count, number}} تغييرًا مرتبطًا",
      commits_other: "{{count, number}} تغيير مرتبط",
      documents_zero: "{{count, number}} مستند مرتبط",
      documents_one: "{{count, number}} مستند مرتبط",
      documents_two: "{{count, number}} مستندان مرتبطان",
      documents_few: "{{count, number}} مستندات مرتبطة",
      documents_many: "{{count, number}} مستندًا مرتبطًا",
      documents_other: "{{count, number}} مستند مرتبط",
    },
    types: { feature: "ميزة" },
  },
  shortcutGroups: {
    workingSet: "مجموعة العمل",
  },
  labels: {
    graph: "الرسم البياني",
    item: "عنصر",
  },
} as const;
