import { en, sourceLocale } from "../../locales/en";

export const ltrTestLocale = "fr" as const;
export const rtlTestLocale = "ar" as const;

export const ltrTestResources = {
  common: {
    accessibility: {
      ...en.common.accessibility,
      back: "Retour",
      recordShortcut: "Enregistrer un raccourci pour {{action}}",
      resizeActivityPanel: "Redimensionner le panneau d’activité",
      resizeNavigationPanel: "Redimensionner le panneau de navigation",
      resizeTimeline: "Redimensionner la chronologie",
      resetShortcut: "Réinitialiser le raccourci pour {{action}}",
      skipToContent: "Aller au contenu",
      switchWorkspace: "Changer d’espace de travail depuis {{workspace}}",
    },
    actions: {
      ...en.common.actions,
      cancel: "Annuler",
      close: "Fermer",
      collapseNavigationPanel: "Réduire le panneau de navigation",
      copyCategoryName: "Copier le nom de la catégorie",
      copyFeatureTag: "Copier l’étiquette de la fonctionnalité",
      hideActivityPanel: "Masquer le panneau d’activité",
      hideNavigationPanel: "Masquer le panneau de navigation",
      hideTimeline: "Masquer la chronologie",
      moveToNextPanel: "Passer au panneau suivant",
      moveToPreviousPanel: "Passer au panneau précédent",
      openCommandPalette: "Ouvrir la palette de commandes…",
      refreshData: "Actualiser les données",
      reloadPage: "Recharger la page",
      reset: "Réinitialiser",
      resetLayout: "Réinitialiser la disposition",
      retry: "Réessayer",
      expandNavigationPanel: "Développer le panneau de navigation",
      searchDocumentsAndCode: "Rechercher dans les documents et le code…",
      showActivityPanel: "Afficher le panneau d’activité",
      showNavigationPanel: "Afficher le panneau de navigation",
      showTimeline: "Afficher la chronologie",
      showChanges: "Afficher les modifications",
      showKeyboardShortcuts: "Afficher les raccourcis clavier",
      showOnCanvas: "Afficher sur le canevas",
      showOrHideGraph: "Afficher ou masquer le graphe",
      showStatus: "Afficher l’état",
    },
    activityTabs: {
      changes: "Modifications",
      status: "État",
    },
    commandFamilies: {
      editing: "Modification",
      filters: "Filtres",
      focus: "Focus",
      general: "Général",
      help: "Aide",
      layout: "Disposition",
      navigation: "Navigation",
      refresh: "Actualisation",
      search: "Recherche",
      searchMaintenance: "Maintenance de la recherche",
      settings: "Paramètres",
      workspaceMaintenance: "Maintenance de l’espace de travail",
    },
    commandPalette: {
      dialogLabel: "Palette de commandes",
      inputPlaceholder: "Rechercher des commandes",
      listboxLabel: "Commandes",
      noMatches: "Aucune commande correspondante",
      loading: "Chargement des commandes…",
      selectionAnnouncement_many: "{{count, number}} commandes. {{command}}",
      selectionAnnouncement_one: "{{count, number}} commande. {{command}}",
      selectionAnnouncement_other: "{{count, number}} commandes. {{command}}",
      footer: {
        navigate: "Naviguer",
        open: "Ouvrir",
        close: "Fermer",
      },
    },
    palette: {
      commandCount_many: "{{count, number}} commandes",
      commandCount_one: "{{count, number}} commande",
      commandCount_other: "{{count, number}} commandes",
    },
    disabledReasons: {
      ...en.common.disabledReasons,
      itemUnavailableOnCanvas:
        "Actualisez les données, puis réessayez d’afficher cet élément sur le canevas.",
    },
    feedback: {
      actionUnavailable:
        "Impossible de terminer l’action. Rechargez la page et réessayez.",
      copyFailed: "Impossible de copier. Réessayez.",
      copySucceeded: "Copié.",
    },
    destructiveActions: {
      discardChanges: "Ignorer les modifications",
    },
    shortcutDialog: {
      description: "Consultez les raccourcis clavier disponibles.",
      title: "Raccourcis clavier",
    },
    shortcutSettings: {
      conflict:
        "Ce raccourci est déjà attribué à {{action}}. Choisissez un autre raccourci.",
      empty: "Aucun raccourci clavier disponible",
      recording: "Appuyez sur une touche…",
    },
    shortcutGroups: {
      general: "Général",
      graph: "Graphe",
      navigation: "Navigation",
      window: "Fenêtre",
    },
    keycaps: {
      ...en.common.keycaps,
      arrowDown: "Flèche vers le bas",
      arrowLeft: "Flèche vers la gauche",
      arrowRight: "Flèche vers la droite",
      arrowUp: "Flèche vers le haut",
      backspace: "Retour arrière",
      delete: "Supprimer",
      escape: "Échap",
      pageDown: "Page suivante",
      pageUp: "Page précédente",
      shift: "Maj",
      space: "Espace",
    },
    statuses: en.common.statuses,
  },
  documents: {
    ...en.documents,
    accessibility: {
      browserView: "Vue du navigateur",
      switchReadingAndEditingShortcut:
        "Basculer entre la lecture et la modification ({{accelerator}})",
      treeOptionsSortedByLatestActivity:
        "Options de l’arborescence, triées par activité récente",
      treeOptionsSortedByDocumentCount:
        "Options de l’arborescence, triées par nombre de documents",
      treeOptionsSortedByName: "Options de l’arborescence, triées par nom",
      treeOptionsSortedByCreationDate:
        "Options de l’arborescence, triées par date de création",
      treeOptionsSortedByEditDate:
        "Options de l’arborescence, triées par date de modification",
      treeOptionsSortedByLength: "Options de l’arborescence, triées par longueur",
      treeOptionsSortedByWorkspaceShare:
        "Options de l’arborescence, triées par part de l’espace de travail",
    },
    actions: {
      ...en.documents.actions,
      addToFeature: "Ajouter à une fonctionnalité…",
      browseDocuments: "Parcourir les documents",
      browseFiles: "Parcourir les fichiers",
      closeAllDocuments: "Fermer tous les documents",
      closeDocument: "Fermer le document",
      clearFilter: "Effacer le filtre des documents",
      closeActiveTab: "Fermer l’onglet du document actif",
      collapseCategory: "Réduire la catégorie",
      collapseTree: "Réduire l’arborescence des documents",
      expandTree: "Développer l’arborescence des documents",
      expandCategory: "Développer la catégorie",
      findByName: "Rechercher un document par nom…",
      finishEditing: "Terminer la modification",
      focusFilter: "Activer le filtre des documents",
      keepDocumentOpen: "Garder le document ouvert",
      nextTab: "Aller à l’onglet de document suivant",
      previousTab: "Aller à l’onglet de document précédent",
      resetFilters: "Réinitialiser les filtres",
      resetSorting: "Réinitialiser le tri",
      reloadDocument: "Recharger le document",
      save: "Enregistrer le document",
      sortByLatestActivity: "Trier par activité récente",
      sortByDocumentCount: "Trier par nombre de documents",
      sortByName: "Trier par nom",
      sortByCreationDate: "Trier par date de création",
      sortByEditDate: "Trier par date de modification",
      sortByLength: "Trier par longueur",
      sortByWorkspaceShare: "Trier par part de l’espace de travail",
      showOrHideChanges: "Afficher ou masquer les modifications",
      showOrHideFilterOptions: "Afficher ou masquer les options de filtre",
      filterByDocumentType: "Filtrer par ce type de document",
      switchReadingAndEditing: "Basculer entre la lecture et la modification",
      switchView: "Basculer entre les documents et les fichiers",
    },
    browserModes: {
      documents: "Documents",
      files: "Fichiers",
    },
    categories: {
      code: "Code",
    },
    documentTypes: {
      research: "Recherche",
      adr: "Décisions",
      plan: "Plans",
      exec: "Étapes",
      audit: "Audits",
      reference: "Références",
    },
    disabledReasons: {
      ...en.documents.disabledReasons,
      copyChangesBeforeReopening:
        "Copiez vos modifications, puis rouvrez le document avant d’enregistrer.",
      openForEditing: "Ouvrez un document à modifier.",
      openDocument: "Ouvrez d’abord un document.",
      tryAfterSaving: "Réessayez une fois l’enregistrement terminé.",
      updateBeforeSaving: "Modifiez le document avant d’enregistrer.",
    },
    feedback: {
      alreadyLinked: "Ces documents sont déjà liés.",
      linkConflict:
        "Le document a été modifié avant de pouvoir être lié. Ouvrez-le, puis réessayez.",
      linkFailed: "Impossible de lier les documents. Réessayez.",
      linkInProgress: "Liaison des documents…",
      linkSucceeded: "Documents liés.",
    },
    labels: {
      document: "Document",
      vault: "Coffre",
    },
    sortOptions: {
      latestActivity: "Activité récente",
      documentCount: "Nombre de documents",
      name: "Nom",
      creationDate: "Date de création",
      editDate: "Date de modification",
      length: "Longueur",
      workspaceShare: "Part de l’espace de travail",
    },
    shortcutGroups: {
      documents: "Documents",
      editing: "Modification du document",
    },
  },
  errors: {
    fallback: {
      contentUnavailable:
        "Ce contenu est indisponible. Rechargez la page et réessayez.",
    },
    unexpectedApplication: {
      message: "Rechargez la page et réessayez.",
      title: "Un problème est survenu",
    },
    unexpectedSection: {
      message: "Réessayez {{section}}.",
      title: "Cette section ne peut pas être affichée",
    },
  },
  features: {
    ...en.features,
    actions: {
      collapse: "Réduire la fonctionnalité",
      expand: "Développer la fonctionnalité",
      moveToNextFeature: "Passer à la fonctionnalité suivante",
      moveToPreviousFeature: "Passer à la fonctionnalité précédente",
      filterByFeature: "Filtrer par cette fonctionnalité",
    },
    feedback: {
      archiveRejected:
        "La fonctionnalité n’a pas été archivée. Vérifiez-la, puis réessayez.",
      archiveSucceeded: "Fonctionnalité archivée.",
      archiveUnavailable: "Impossible d’archiver la fonctionnalité. Réessayez.",
      repairRejected:
        "La fonctionnalité n’a pas été réparée. Vérifiez-la, puis réessayez.",
      repairSucceeded: "Fonctionnalité réparée.",
      repairUnavailable: "Impossible de réparer la fonctionnalité. Réessayez.",
    },
    labels: {
      feature: "Fonctionnalités",
    },
  },
  graph: {
    accessibility: {
      selectedItem: "Élément sélectionné : {{item}}.",
      selectedItemGeneric: "Élément sélectionné.",
      workingSet: "Ensemble de travail",
      workingSetCount_many: "{{count, number}} éléments dans l’ensemble de travail",
      workingSetCount_one: "{{count, number}} élément dans l’ensemble de travail",
      workingSetCount_other: "{{count, number}} éléments dans l’ensemble de travail",
      hiddenByActiveFilter: "Masqué par le filtre actif",
      namedWorkingSetItemHidden: "{{item}} est masqué par le filtre actif.",
      workingSetItemHidden: "L’élément est masqué par le filtre actif.",
    },
    actions: {
      addItemToWorkingSet: "Ajouter l’élément à l’ensemble de travail",
      addSelectedItemToWorkingSet:
        "Ajouter l’élément sélectionné à l’ensemble de travail",
      clearSelection: "Effacer la sélection du graphe",
      clearWorkingSet: "Effacer l’ensemble de travail",
      expandFocusedItem: "Développer l’élément actif dans l’espace de travail",
      fitToView: "Adapter le graphe à la vue",
      moveToNextConnectedItem: "Passer à l’élément connecté suivant",
      moveToPreviousConnectedItem: "Passer à l’élément connecté précédent",
      openFocusedItem: "Ouvrir l’élément actif",
      pauseMovement: "Suspendre le mouvement du graphe",
      pinItem: "Épingler l’élément",
      resetSettings: "Réinitialiser les paramètres du graphe",
      resetView: "Réinitialiser la vue du graphe",
      removeItemFromWorkingSet: "Retirer l’élément de l’ensemble de travail",
      removeNamedItemFromWorkingSet: "Retirer {{item}} de l’ensemble de travail",
      removeLastItemFromWorkingSet:
        "Retirer le dernier élément de l’ensemble de travail",
      resumeMovement: "Reprendre le mouvement du graphe",
      showRelatedItem: "Afficher l’élément associé",
      showStartingItem: "Afficher l’élément de départ",
      unpinItem: "Désépingler l’élément",
      zoomIn: "Agrandir",
      zoomOut: "Réduire",
    },
    disabledReasons: {
      chooseConnectionWithSummary: "Choisissez une connexion avec un résumé à copier.",
      chooseItemWithTitle: "Choisissez un élément avec un titre à copier.",
      relatedItemUnavailable:
        "Actualisez les données, puis réessayez d’afficher l’élément associé.",
      startingItemUnavailable:
        "Actualisez les données, puis réessayez d’afficher l’élément de départ.",
    },
    shortcutGroups: {
      workingSet: "Ensemble de travail",
    },
    labels: {
      item: "Élément",
    },
  },
  operations: {
    actions: {
      applySearchSettings: "Appliquer les paramètres de recherche",
      checkWorkspace: "Vérifier l’espace de travail",
      disableSearch: "Désactiver la recherche",
      enableSearch: "Activer la recherche",
      refreshSearch: "Actualiser la recherche",
      showWorkspaceDetails: "Afficher les détails de l’espace de travail",
    },
    feedback: {
      applySearchSettings: {
        failed: "Impossible d’appliquer les paramètres de recherche. Réessayez.",
        running: "Application des paramètres de recherche…",
        succeeded: "Paramètres de recherche appliqués.",
        unavailable: "La recherche est indisponible. Activez-la, puis réessayez.",
      },
      checkWorkspace: {
        failed: "Impossible de vérifier l’espace de travail. Réessayez.",
        running: "Vérification de l’espace de travail…",
        succeeded: "Vérification de l’espace de travail terminée.",
      },
      disableSearch: {
        failed: "Impossible de désactiver la recherche. Réessayez.",
        running: "Désactivation de la recherche…",
        succeeded: "Recherche désactivée.",
      },
      enableSearch: {
        failed: "Impossible d’activer la recherche. Réessayez.",
        running: "Activation de la recherche…",
        succeeded: "Recherche activée.",
        unavailable: "La recherche reste indisponible. Réessayez.",
      },
      refreshSearch: {
        failed: "Impossible d’actualiser la recherche. Réessayez.",
        running: "Actualisation de la recherche…",
        succeeded: "Actualisation de la recherche lancée.",
        unavailable: "La recherche est indisponible. Activez-la, puis réessayez.",
      },
      showWorkspaceDetails: {
        failed: "Impossible de charger les détails de l’espace de travail. Réessayez.",
        running: "Chargement des détails de l’espace de travail…",
        succeeded: "Détails de l’espace de travail chargés.",
      },
    },
  },
  projects: {
    actions: {
      add: "Ajouter un projet…",
      clearHistory: "Effacer l’historique des projets",
      switch: "Changer de projet…",
    },
    shortcutGroups: {
      projects: "Projets",
    },
  },
  settings: {
    actions: {
      useDarkTheme: "Utiliser le thème sombre",
      useHighContrastTheme: "Utiliser le thème à contraste élevé",
      useLightTheme: "Utiliser le thème clair",
      useSystemTheme: "Utiliser le thème du système",
    },
    groups: {
      appearance: "Apparence",
      graph: "Graphe",
      keybindings: "Raccourcis clavier",
    },
    fields: {
      theme: { label: "Thème", description: "Choisissez le thème de l’interface." },
      reduceMotion: {
        label: "Réduire les animations",
        description: "Utilisez moins d’animations dans l’interface.",
      },
      activitySectionFolds: {
        label: "Sections d’activité",
        description: "Mémorisez les sections d’activité ouvertes.",
      },
      language: {
        label: "Langue",
        description: "Choisissez la langue de l’interface.",
      },
      defaultGranularity: {
        label: "Niveau de détail par défaut",
        description: "Choisissez le niveau de détail initial du graphe.",
      },
      corpus: {
        label: "Contenu du graphe",
        description: "Choisissez le contenu affiché dans le graphe.",
      },
      timelineDate: {
        label: "Date de la chronologie",
        description: "Choisissez la date qui contrôle la chronologie.",
      },
      confidenceFloor: {
        label: "Certitude minimale des connexions",
        description: "Masquez les connexions sous ce niveau de certitude.",
      },
      labelFilter: {
        label: "Filtre par nom",
        description: "Affichez les éléments dont le nom correspond.",
        placeholder: "Filtrer par nom",
      },
      graphControls: {
        label: "Commandes du graphe",
        description: "Personnalisez la navigation du graphe.",
      },
      shortcuts: {
        label: "Raccourcis clavier",
        description: "Personnalisez les commandes clavier.",
      },
    },
    options: {
      system: "Système",
      light: "Clair",
      dark: "Sombre",
      highContrast: "Contraste élevé",
      english: "Anglais",
    },
  },
  timeline: {
    accessibility: {
      dateField: "Date de la chronologie",
    },
    actions: {
      clearDateRange: "Effacer la période",
      filterByCreationDate: "Filtrer par date de création",
      filterByCreationDateCurrent: "Filtrer par date de création (actuelle)",
      filterByEditDate: "Filtrer par date de modification",
      filterByEditDateCurrent: "Filtrer par date de modification (actuelle)",
      filterByUpdateDate: "Filtrer par date de mise à jour",
      filterByUpdateDateCurrent: "Filtrer par date de mise à jour (actuelle)",
      showLast24Hours: "Afficher les dernières 24 heures",
      showLast7Days: "Afficher les 7 derniers jours",
      showLast30Days: "Afficher les 30 derniers jours",
      showLast90Days: "Afficher les 90 derniers jours",
    },
    criteria: {
      created: "Création",
      modified: "Modification",
      stamped: "Mise à jour",
    },
    descriptions: {
      useCreationDateForRange: "Utiliser la date de création pour la période",
      useEditDateForRange: "Utiliser la date de modification pour la période",
      useUpdateDateForRange: "Utiliser la date de mise à jour pour la période",
    },
    disabledReasons: {
      codeFiles:
        "Choisissez la date de modification. Les fichiers de code utilisent les dates de modification.",
      current: "Choisissez une autre option de date pour modifier la chronologie.",
      modifiedUnavailable:
        "Choisissez la date de création. Les dates de modification ne sont pas disponibles ici.",
      stampedUnavailable:
        "Choisissez la date de création. Les dates de mise à jour ne sont pas disponibles ici.",
    },
    labels: {
      timeline: "Chronologie",
    },
  },
} as const;

export const rtlTestResources = {
  common: {
    accessibility: {
      ...en.common.accessibility,
      back: "رجوع",
      recordShortcut: "تسجيل اختصار لـ {{action}}",
      resizeActivityPanel: "تغيير حجم لوحة النشاط",
      resizeNavigationPanel: "تغيير حجم لوحة التنقل",
      resizeTimeline: "تغيير حجم المخطط الزمني",
      resetShortcut: "إعادة تعيين اختصار {{action}}",
      skipToContent: "التخطي إلى المحتوى",
      switchWorkspace: "تبديل مساحة العمل من {{workspace}}",
    },
    actions: {
      ...en.common.actions,
      cancel: "إلغاء",
      close: "إغلاق",
      collapseNavigationPanel: "طي لوحة التنقل",
      copyCategoryName: "نسخ اسم الفئة",
      copyFeatureTag: "نسخ وسم الميزة",
      hideActivityPanel: "إخفاء لوحة النشاط",
      hideNavigationPanel: "إخفاء لوحة التنقل",
      hideTimeline: "إخفاء المخطط الزمني",
      moveToNextPanel: "الانتقال إلى اللوحة التالية",
      moveToPreviousPanel: "الانتقال إلى اللوحة السابقة",
      openCommandPalette: "فتح لوحة الأوامر…",
      refreshData: "تحديث البيانات",
      reloadPage: "إعادة تحميل الصفحة",
      reset: "إعادة تعيين",
      resetLayout: "إعادة تعيين التخطيط",
      retry: "إعادة المحاولة",
      expandNavigationPanel: "توسيع لوحة التنقل",
      searchDocumentsAndCode: "البحث في المستندات والتعليمات البرمجية…",
      showActivityPanel: "إظهار لوحة النشاط",
      showNavigationPanel: "إظهار لوحة التنقل",
      showTimeline: "إظهار المخطط الزمني",
      showChanges: "إظهار التغييرات",
      showOrHideGraph: "إظهار الرسم البياني أو إخفاؤه",
      showOnCanvas: "إظهار على اللوحة",
      showStatus: "إظهار الحالة",
    },
    activityTabs: {
      changes: "التغييرات",
      status: "الحالة",
    },
    commandFamilies: {
      editing: "التحرير",
      filters: "عوامل التصفية",
      focus: "التركيز",
      general: "عام",
      help: "المساعدة",
      layout: "التخطيط",
      navigation: "التنقل",
      refresh: "التحديث",
      search: "البحث",
      searchMaintenance: "صيانة البحث",
      settings: "الإعدادات",
      workspaceMaintenance: "صيانة مساحة العمل",
    },
    commandPalette: {
      dialogLabel: "لوحة الأوامر",
      inputPlaceholder: "البحث في الأوامر",
      listboxLabel: "الأوامر",
      noMatches: "لا توجد أوامر مطابقة",
      loading: "جارٍ تحميل الأوامر…",
      selectionAnnouncement_few: "{{count, number}} أوامر. {{command}}",
      selectionAnnouncement_many: "{{count, number}} أمرًا. {{command}}",
      selectionAnnouncement_one: "{{count, number}} أمر. {{command}}",
      selectionAnnouncement_other: "{{count, number}} أمر. {{command}}",
      selectionAnnouncement_two: "{{count, number}} أمران. {{command}}",
      selectionAnnouncement_zero: "{{count, number}} أمر. {{command}}",
      footer: {
        navigate: "تنقل",
        open: "فتح",
        close: "إغلاق",
      },
    },
    palette: {
      commandCount_few: "{{count, number}} أوامر",
      commandCount_many: "{{count, number}} أمرًا",
      commandCount_one: "{{count, number}} أمر",
      commandCount_other: "{{count, number}} أمر",
      commandCount_two: "{{count, number}} أمران",
      commandCount_zero: "{{count, number}} أمر",
    },
    disabledReasons: {
      ...en.common.disabledReasons,
      itemUnavailableOnCanvas: "حدّث البيانات، ثم حاول إظهار هذا العنصر على اللوحة.",
    },
    feedback: {
      actionUnavailable: "تعذر إكمال الإجراء. أعد تحميل الصفحة وحاول مرة أخرى.",
      copyFailed: "تعذر النسخ. حاول مرة أخرى.",
      copySucceeded: "تم النسخ.",
    },
    destructiveActions: {
      discardChanges: "تجاهل التغييرات",
    },
    shortcutDialog: en.common.shortcutDialog,
    shortcutSettings: {
      conflict: "هذا الاختصار مخصص بالفعل لـ {{action}}. اختر اختصارًا آخر.",
      empty: "لا توجد اختصارات لوحة مفاتيح متاحة",
      recording: "اضغط على مفتاح…",
    },
    shortcutGroups: {
      general: "عام",
      graph: "الرسم البياني",
      navigation: "التنقل",
      window: "النافذة",
    },
    keycaps: {
      ...en.common.keycaps,
      arrowDown: "سهم للأسفل",
      arrowLeft: "سهم لليسار",
      arrowRight: "سهم لليمين",
      arrowUp: "سهم للأعلى",
      backspace: "مسح للخلف",
      delete: "حذف",
      enter: "إدخال",
      escape: "خروج",
      shift: "تبديل",
      space: "مسافة",
    },
    statuses: en.common.statuses,
  },
  documents: {
    ...en.documents,
    accessibility: {
      browserView: "عرض المتصفح",
      switchReadingAndEditingShortcut: "التبديل بين القراءة والتحرير ({{accelerator}})",
      treeOptionsSortedByLatestActivity: "خيارات شجرة المستندات، مرتبة حسب أحدث نشاط",
      treeOptionsSortedByDocumentCount:
        "خيارات شجرة المستندات، مرتبة حسب عدد المستندات",
      treeOptionsSortedByName: "خيارات شجرة المستندات، مرتبة حسب الاسم",
      treeOptionsSortedByCreationDate: "خيارات شجرة المستندات، مرتبة حسب تاريخ الإنشاء",
      treeOptionsSortedByEditDate: "خيارات شجرة المستندات، مرتبة حسب تاريخ التعديل",
      treeOptionsSortedByLength: "خيارات شجرة المستندات، مرتبة حسب الطول",
      treeOptionsSortedByWorkspaceShare:
        "خيارات شجرة المستندات، مرتبة حسب حصة مساحة العمل",
    },
    actions: {
      ...en.documents.actions,
      browseDocuments: "تصفح المستندات",
      browseFiles: "تصفح الملفات",
      closeAllDocuments: "إغلاق جميع المستندات",
      closeDocument: "إغلاق المستند",
      closeActiveTab: "إغلاق علامة تبويب المستند النشط",
      collapseCategory: "طي الفئة",
      finishEditing: "إنهاء التحرير",
      findByName: "البحث عن مستند بالاسم…",
      expandCategory: "توسيع الفئة",
      keepDocumentOpen: "إبقاء المستند مفتوحًا",
      reloadDocument: "إعادة تحميل المستند",
      nextTab: "الانتقال إلى علامة تبويب المستند التالية",
      previousTab: "الانتقال إلى علامة تبويب المستند السابقة",
      resetSorting: "إعادة تعيين الترتيب",
      save: "حفظ المستند",
      sortByLatestActivity: "الترتيب حسب أحدث نشاط",
      sortByDocumentCount: "الترتيب حسب عدد المستندات",
      sortByName: "الترتيب حسب الاسم",
      sortByCreationDate: "الترتيب حسب تاريخ الإنشاء",
      sortByEditDate: "الترتيب حسب تاريخ التعديل",
      sortByLength: "الترتيب حسب الطول",
      sortByWorkspaceShare: "الترتيب حسب حصة مساحة العمل",
      showOrHideChanges: "إظهار التغييرات أو إخفاؤها",
      filterByDocumentType: "التصفية حسب نوع المستند هذا",
      switchReadingAndEditing: "التبديل بين القراءة والتحرير",
    },
    browserModes: {
      documents: "المستندات",
      files: "الملفات",
    },
    categories: {
      code: "التعليمات البرمجية",
    },
    documentTypes: {
      research: "البحث",
      adr: "القرارات",
      plan: "الخطط",
      exec: "الخطوات",
      audit: "عمليات التدقيق",
      reference: "المراجع",
    },
    disabledReasons: {
      ...en.documents.disabledReasons,
      copyChangesBeforeReopening: "انسخ تغييراتك، ثم أعد فتح المستند قبل الحفظ.",
      openForEditing: "افتح مستندًا لتحريره.",
      openDocument: "افتح مستندًا أولاً.",
      tryAfterSaving: "حاول مرة أخرى بعد اكتمال الحفظ.",
      updateBeforeSaving: "حدّث المستند قبل الحفظ.",
    },
    feedback: {
      alreadyLinked: "هذه المستندات مرتبطة بالفعل.",
      linkConflict: "تغير المستند قبل ربطه. افتحه، ثم حاول مرة أخرى.",
      linkFailed: "تعذر ربط المستندات. حاول مرة أخرى.",
      linkInProgress: "جارٍ ربط المستندات…",
      linkSucceeded: "تم ربط المستندات.",
    },
    labels: {
      document: "مستند",
      vault: "الخزنة",
    },
    sortOptions: {
      latestActivity: "أحدث نشاط",
      documentCount: "عدد المستندات",
      name: "الاسم",
      creationDate: "تاريخ الإنشاء",
      editDate: "تاريخ التعديل",
      length: "الطول",
      workspaceShare: "حصة مساحة العمل",
    },
    shortcutGroups: {
      documents: "المستندات",
      editing: "تحرير المستند",
    },
  },
  errors: {
    fallback: {
      contentUnavailable: "هذا المحتوى غير متاح. أعد تحميل الصفحة وحاول مرة أخرى.",
    },
    unexpectedApplication: {
      message: "أعد تحميل الصفحة وحاول مرة أخرى.",
      title: "حدث خطأ ما",
    },
    unexpectedSection: {
      message: "حاول فتح {{section}} مرة أخرى.",
      title: "تعذر عرض هذا القسم",
    },
  },
  features: {
    ...en.features,
    actions: {
      collapse: "طي الميزة",
      expand: "توسيع الميزة",
      moveToNextFeature: "الانتقال إلى الميزة التالية",
      moveToPreviousFeature: "الانتقال إلى الميزة السابقة",
      filterByFeature: "التصفية حسب هذه الميزة",
    },
    feedback: {
      archiveRejected: "لم تتم أرشفة الميزة. تحقق منها، ثم حاول مرة أخرى.",
      archiveSucceeded: "تمت أرشفة الميزة.",
      archiveUnavailable: "تعذرت أرشفة الميزة. حاول مرة أخرى.",
      repairRejected: "لم يتم إصلاح الميزة. تحقق منها، ثم حاول مرة أخرى.",
      repairSucceeded: "تم إصلاح الميزة.",
      repairUnavailable: "تعذر إصلاح الميزة. حاول مرة أخرى.",
    },
    labels: {
      feature: "الميزات",
    },
  },
  graph: {
    accessibility: {
      selectedItem: "تم تحديد {{item}}.",
      selectedItemGeneric: "تم تحديد العنصر.",
      workingSet: "مجموعة العمل",
      workingSetCount_zero: "{{count, number}} عنصر في مجموعة العمل",
      workingSetCount_one: "{{count, number}} عنصر في مجموعة العمل",
      workingSetCount_two: "{{count, number}} من العناصر في مجموعة العمل",
      workingSetCount_few: "{{count, number}} عناصر في مجموعة العمل",
      workingSetCount_many: "{{count, number}} عنصرًا في مجموعة العمل",
      workingSetCount_other: "{{count, number}} عنصر في مجموعة العمل",
      hiddenByActiveFilter: "مخفي بواسطة عامل التصفية النشط",
      namedWorkingSetItemHidden: "{{item}} مخفي بواسطة عامل التصفية النشط.",
      workingSetItemHidden: "العنصر مخفي بواسطة عامل التصفية النشط.",
    },
    actions: {
      addItemToWorkingSet: "إضافة العنصر إلى مجموعة العمل",
      addSelectedItemToWorkingSet: "إضافة العنصر المحدد إلى مجموعة العمل",
      clearSelection: "مسح تحديد الرسم البياني",
      clearWorkingSet: "مسح مجموعة العمل",
      expandFocusedItem: "توسيع العنصر المحدد ضمن مساحة العمل",
      fitToView: "ملاءمة الرسم البياني للعرض",
      moveToNextConnectedItem: "الانتقال إلى العنصر المتصل التالي",
      moveToPreviousConnectedItem: "الانتقال إلى العنصر المتصل السابق",
      openFocusedItem: "فتح العنصر المحدد",
      pauseMovement: "إيقاف حركة الرسم البياني مؤقتًا",
      pinItem: "تثبيت العنصر",
      resetSettings: "إعادة تعيين إعدادات الرسم البياني",
      resetView: "إعادة تعيين عرض الرسم البياني",
      removeItemFromWorkingSet: "إزالة العنصر من مجموعة العمل",
      removeNamedItemFromWorkingSet: "إزالة {{item}} من مجموعة العمل",
      removeLastItemFromWorkingSet: "إزالة العنصر الأخير من مجموعة العمل",
      resumeMovement: "استئناف حركة الرسم البياني",
      showRelatedItem: "إظهار العنصر المرتبط",
      showStartingItem: "إظهار عنصر البداية",
      unpinItem: "إلغاء تثبيت العنصر",
      zoomIn: "تكبير",
      zoomOut: "تصغير",
    },
    disabledReasons: {
      chooseConnectionWithSummary: "اختر اتصالًا له ملخص لنسخه.",
      chooseItemWithTitle: "اختر عنصرًا له عنوان لنسخه.",
      relatedItemUnavailable: "حدّث البيانات، ثم حاول إظهار العنصر المرتبط مرة أخرى.",
      startingItemUnavailable: "حدّث البيانات، ثم حاول إظهار عنصر البداية مرة أخرى.",
    },
    shortcutGroups: {
      workingSet: "مجموعة العمل",
    },
    labels: {
      item: "عنصر",
    },
  },
  operations: {
    actions: {
      applySearchSettings: "تطبيق إعدادات البحث",
      checkWorkspace: "فحص مساحة العمل",
      disableSearch: "تعطيل البحث",
      enableSearch: "تمكين البحث",
      refreshSearch: "تحديث البحث",
      showWorkspaceDetails: "عرض تفاصيل مساحة العمل",
    },
    feedback: {
      applySearchSettings: {
        failed: "تعذر تطبيق إعدادات البحث. حاول مرة أخرى.",
        running: "جارٍ تطبيق إعدادات البحث…",
        succeeded: "تم تطبيق إعدادات البحث.",
        unavailable: "البحث غير متاح. مكّن البحث، ثم حاول مرة أخرى.",
      },
      checkWorkspace: {
        failed: "تعذر فحص مساحة العمل. حاول مرة أخرى.",
        running: "جارٍ فحص مساحة العمل…",
        succeeded: "اكتمل فحص مساحة العمل.",
      },
      disableSearch: {
        failed: "تعذر تعطيل البحث. حاول مرة أخرى.",
        running: "جارٍ تعطيل البحث…",
        succeeded: "تم تعطيل البحث.",
      },
      enableSearch: {
        failed: "تعذر تمكين البحث. حاول مرة أخرى.",
        running: "جارٍ تمكين البحث…",
        succeeded: "تم تمكين البحث.",
        unavailable: "لا يزال البحث غير متاح. حاول مرة أخرى.",
      },
      refreshSearch: {
        failed: "تعذر تحديث البحث. حاول مرة أخرى.",
        running: "جارٍ تحديث البحث…",
        succeeded: "بدأ تحديث البحث.",
        unavailable: "البحث غير متاح. مكّن البحث، ثم حاول مرة أخرى.",
      },
      showWorkspaceDetails: {
        failed: "تعذر تحميل تفاصيل مساحة العمل. حاول مرة أخرى.",
        running: "جارٍ تحميل تفاصيل مساحة العمل…",
        succeeded: "تم تحميل تفاصيل مساحة العمل.",
      },
    },
  },
  projects: {
    actions: {
      add: "إضافة مشروع…",
      clearHistory: "مسح سجل المشاريع",
      switch: "تبديل المشروع…",
    },
    shortcutGroups: {
      projects: "المشاريع",
    },
  },
  settings: {
    actions: {
      useDarkTheme: "استخدام النسق الداكن",
      useHighContrastTheme: "استخدام نسق عالي التباين",
      useLightTheme: "استخدام النسق الفاتح",
      useSystemTheme: "استخدام نسق النظام",
    },
    groups: {
      appearance: "المظهر",
      graph: "الرسم البياني",
      keybindings: "اختصارات لوحة المفاتيح",
    },
    fields: {
      theme: { label: "النسق", description: "اختر نسق الواجهة." },
      reduceMotion: {
        label: "تقليل الحركة",
        description: "استخدم رسومًا متحركة أقل في الواجهة.",
      },
      activitySectionFolds: {
        label: "أقسام النشاط",
        description: "تذكر أقسام النشاط المفتوحة.",
      },
      language: { label: "اللغة", description: "اختر لغة الواجهة." },
      defaultGranularity: {
        label: "التفصيل الافتراضي",
        description: "اختر مستوى التفاصيل الأولي للرسم البياني.",
      },
      corpus: { label: "محتوى الرسم", description: "اختر المحتوى الذي يظهر في الرسم." },
      timelineDate: {
        label: "تاريخ المخطط الزمني",
        description: "اختر التاريخ الذي يتحكم في المخطط.",
      },
      confidenceFloor: {
        label: "الحد الأدنى ليقين الاتصال",
        description: "أخفِ الاتصالات دون هذا اليقين.",
      },
      labelFilter: {
        label: "تصفية الاسم",
        description: "اعرض العناصر ذات الأسماء المطابقة.",
        placeholder: "تصفية حسب الاسم",
      },
      graphControls: { label: "عناصر تحكم الرسم", description: "خصص التنقل في الرسم." },
      shortcuts: {
        label: "اختصارات لوحة المفاتيح",
        description: "خصص أوامر لوحة المفاتيح.",
      },
    },
    options: {
      system: "النظام",
      light: "فاتح",
      dark: "داكن",
      highContrast: "تباين عالٍ",
      english: "الإنجليزية",
    },
  },
  timeline: {
    accessibility: {
      dateField: "تاريخ المخطط الزمني",
    },
    actions: {
      clearDateRange: "مسح نطاق التاريخ",
      filterByCreationDate: "التصفية حسب تاريخ الإنشاء",
      filterByCreationDateCurrent: "التصفية حسب تاريخ الإنشاء (الحالي)",
      filterByEditDate: "التصفية حسب تاريخ التعديل",
      filterByEditDateCurrent: "التصفية حسب تاريخ التعديل (الحالي)",
      filterByUpdateDate: "التصفية حسب تاريخ التحديث",
      filterByUpdateDateCurrent: "التصفية حسب تاريخ التحديث (الحالي)",
      showLast24Hours: "عرض آخر 24 ساعة",
      showLast7Days: "عرض آخر 7 أيام",
      showLast30Days: "عرض آخر 30 يومًا",
      showLast90Days: "عرض آخر 90 يومًا",
    },
    criteria: {
      created: "الإنشاء",
      modified: "التعديل",
      stamped: "التحديث",
    },
    descriptions: {
      useCreationDateForRange: "استخدام تاريخ الإنشاء للنطاق",
      useEditDateForRange: "استخدام تاريخ التعديل للنطاق",
      useUpdateDateForRange: "استخدام تاريخ التحديث للنطاق",
    },
    disabledReasons: {
      codeFiles: "اختر تاريخ التعديل. تستخدم ملفات التعليمات البرمجية تواريخ التعديل.",
      current: "اختر خيار تاريخ آخر لتغيير المخطط الزمني.",
      modifiedUnavailable: "اختر تاريخ الإنشاء. تواريخ التعديل غير متاحة هنا.",
      stampedUnavailable: "اختر تاريخ الإنشاء. تواريخ التحديث غير متاحة هنا.",
    },
    labels: {
      timeline: "المخطط الزمني",
    },
  },
} as const;

export const testResources = {
  [sourceLocale]: en,
  [ltrTestLocale]: ltrTestResources,
  [rtlTestLocale]: rtlTestResources,
} as const;

export type TestLocale = keyof typeof testResources;
