import { en, sourceLocale } from "../../locales/en";

export const ltrTestLocale = "fr" as const;
export const rtlTestLocale = "ar" as const;

export const ltrTestResources = {
  common: {
    accessibility: {
      ...en.common.accessibility,
      actionsForItem: "Actions pour {{item}}",
      back: "Retour",
      recordShortcut: "Enregistrer un raccourci pour {{action}}",
      resizeActivityPanel: "Redimensionner le panneau d’activité",
      resizeNavigationPanel: "Redimensionner le panneau de navigation",
      resizeTimeline: "Redimensionner la chronologie",
      resetShortcut: "Réinitialiser le raccourci pour {{action}}",
      skipToContent: "Aller au contenu",
      switchWorkspace: "Changer d’espace de travail depuis {{workspace}}",
    },
    actions: {
      ...en.common.actions,
      cancel: "Annuler",
      close: "Fermer",
      collapseNavigationPanel: "Réduire le panneau de navigation",
      copyBranchName: "Copier le nom de la branche",
      copyCategoryName: "Copier le nom de la catégorie",
      copyCommitHash: "Copier l’empreinte de validation",
      copyCommitMessage: "Copier le message de validation",
      copyFeatureTag: "Copier l’étiquette de la fonctionnalité",
      copyPullRequestLink: "Copier le lien de la demande de fusion",
      copyPullRequestNumber: "Copier le numéro de la demande de fusion",
      copyShortCommitHash: "Copier l’empreinte courte de validation",
      hideActivityPanel: "Masquer le panneau d’activité",
      hideNavigationPanel: "Masquer le panneau de navigation",
      hideTimeline: "Masquer la chronologie",
      moveToNextPanel: "Passer au panneau suivant",
      moveToPreviousPanel: "Passer au panneau précédent",
      openCommandPalette: "Ouvrir la palette de commandes…",
      refreshData: "Actualiser les données",
      reloadPage: "Recharger la page",
      reset: "Réinitialiser",
      resetLayout: "Réinitialiser la disposition",
      retry: "Réessayer",
      expandNavigationPanel: "Développer le panneau de navigation",
      searchDocumentsAndCode: "Rechercher dans les documents et le code…",
      showActivityPanel: "Afficher le panneau d’activité",
      showNavigationPanel: "Afficher le panneau de navigation",
      showTimeline: "Afficher la chronologie",
      showChanges: "Afficher les modifications",
      showKeyboardShortcuts: "Afficher les raccourcis clavier",
      showOnCanvas: "Afficher sur le canevas",
      showOrHideGraph: "Afficher ou masquer le graphe",
      showStatus: "Afficher l’état",
    },
    activityTabs: {
      changes: "Modifications",
      status: "État",
    },
    commandFamilies: {
      editing: "Modification",
      filters: "Filtres",
      focus: "Focus",
      general: "Général",
      help: "Aide",
      layout: "Disposition",
      navigation: "Navigation",
      refresh: "Actualisation",
      search: "Recherche",
      searchMaintenance: "Maintenance de la recherche",
      settings: "Paramètres",
      workspaceMaintenance: "Maintenance de l’espace de travail",
    },
    commandPalette: {
      dialogLabel: "Palette de commandes",
      inputPlaceholder: "Rechercher des commandes",
      listboxLabel: "Commandes",
      noMatches: "Aucune commande correspondante",
      loading: "Chargement des commandes…",
      selectionAnnouncement_many: "{{count, number}} commandes. {{command}}",
      selectionAnnouncement_one: "{{count, number}} commande. {{command}}",
      selectionAnnouncement_other: "{{count, number}} commandes. {{command}}",
      footer: {
        navigate: "Naviguer",
        open: "Ouvrir",
        close: "Fermer",
      },
    },
    palette: {
      commandCount_many: "{{count, number}} commandes",
      commandCount_one: "{{count, number}} commande",
      commandCount_other: "{{count, number}} commandes",
    },
    disabledReasons: {
      ...en.common.disabledReasons,
      itemUnavailableOnCanvas:
        "Actualisez les données, puis réessayez d’afficher cet élément sur le canevas.",
    },
    feedback: {
      actionUnavailable:
        "Impossible de terminer l’action. Rechargez la page et réessayez.",
      copyFailed: "Impossible de copier. Réessayez.",
      copySucceeded: "Copié.",
    },
    destructiveActions: {
      discardChanges: "Ignorer les modifications",
    },
    shortcutDialog: {
      description: "Consultez les raccourcis clavier disponibles.",
      title: "Raccourcis clavier",
    },
    shortcutSettings: {
      conflict:
        "Ce raccourci est déjà attribué à {{action}}. Choisissez un autre raccourci.",
      empty: "Aucun raccourci clavier disponible",
      recording: "Appuyez sur une touche…",
    },
    shortcutGroups: {
      general: "Général",
      graph: "Graphe",
      navigation: "Navigation",
      window: "Fenêtre",
    },
    keycaps: {
      ...en.common.keycaps,
      arrowDown: "Flèche vers le bas",
      arrowLeft: "Flèche vers la gauche",
      arrowRight: "Flèche vers la droite",
      arrowUp: "Flèche vers le haut",
      backspace: "Retour arrière",
      delete: "Supprimer",
      escape: "Échap",
      pageDown: "Page suivante",
      pageUp: "Page précédente",
      shift: "Maj",
      space: "Espace",
    },
    statuses: en.common.statuses,
  },
  documents: {
    ...en.documents,
    accessibility: {
      addDocumentToFeature: "Ajouter un document à une fonctionnalité",
      browserView: "Vue du navigateur",
      decisionAccepted: "Décision acceptée",
      decisionDeprecated: "Décision retirée",
      decisionProposed: "Décision proposée",
      decisionRejected: "Décision rejetée",
      decisionSuperseded: "Décision remplacée",
      planComplete: "Plan terminé",
      planInProgress: "Plan en cours",
      planNotStarted: "Plan non commencé",
      treeBrowser: "Arborescence des documents",
      switchReadingAndEditingShortcut:
        "Basculer entre la lecture et la modification ({{accelerator}})",
      treeOptionsSortedByLatestActivity:
        "Options de l’arborescence, triées par activité récente",
      treeOptionsSortedByDocumentCount:
        "Options de l’arborescence, triées par nombre de documents",
      treeOptionsSortedByName: "Options de l’arborescence, triées par nom",
      treeOptionsSortedByCreationDate:
        "Options de l’arborescence, triées par date de création",
      treeOptionsSortedByEditDate:
        "Options de l’arborescence, triées par date de modification",
      treeOptionsSortedByLength: "Options de l’arborescence, triées par longueur",
      treeOptionsSortedByWorkspaceShare:
        "Options de l’arborescence, triées par part de l’espace de travail",
    },
    actions: {
      ...en.documents.actions,
      addComment: "Ajouter un commentaire",
      addToFeature: "Ajouter à une fonctionnalité…",
      browseDocuments: "Parcourir les documents",
      browseFiles: "Parcourir les fichiers",
      closeAllDocuments: "Fermer tous les documents",
      closeDocument: "Fermer le document",
      closeOtherDocuments: "Fermer les autres documents",
      clearFilter: "Effacer le filtre des documents",
      closeActiveTab: "Fermer l’onglet du document actif",
      collapseCategory: "Réduire la catégorie",
      collapseTree: "Réduire l’arborescence des documents",
      expandTree: "Développer l’arborescence des documents",
      expandCategory: "Développer la catégorie",
      findByName: "Rechercher un document par nom…",
      finishEditing: "Terminer la modification",
      focusFilter: "Activer le filtre des documents",
      keepDocumentOpen: "Garder le document ouvert",
      keepTabOpen: "Garder l’onglet ouvert",
      nextTab: "Aller à l’onglet de document suivant",
      openComments: "Ouvrir les commentaires",
      previousTab: "Aller à l’onglet de document précédent",
      resetFilters: "Réinitialiser les filtres",
      resetSorting: "Réinitialiser le tri",
      reloadDocument: "Recharger le document",
      save: "Enregistrer le document",
      sortByLatestActivity: "Trier par activité récente",
      sortByDocumentCount: "Trier par nombre de documents",
      sortByName: "Trier par nom",
      sortByCreationDate: "Trier par date de création",
      sortByEditDate: "Trier par date de modification",
      sortByLength: "Trier par longueur",
      sortByWorkspaceShare: "Trier par part de l’espace de travail",
      showOrHideChanges: "Afficher ou masquer les modifications",
      showOrHideFilterOptions: "Afficher ou masquer les options de filtre",
      filterByDocumentType: "Filtrer par ce type de document",
      switchReadingAndEditing: "Basculer entre la lecture et la modification",
      switchView: "Basculer entre les documents et les fichiers",
    },
    browserModes: {
      documents: "Documents",
      files: "Fichiers",
    },
    categories: {
      code: "Code",
    },
    createDialog: {
      accessibility: {
        addLinkedDocument: "Ajouter un document lié",
        backToFeature: "Retour à la fonctionnalité",
        documentType: "Type de document",
        feature: "Fonctionnalité",
        linkedDocuments: "Documents liés",
        pipelineCoverage: "Progression du processus",
        removeLinkedDocument: "Supprimer {{document}}",
        title: "Titre",
      },
      actions: {
        back: "Retour",
        continue: "Continuer",
        create: "Créer",
        creating: "Création du document…",
      },
      descriptions: {
        documentStage:
          "Choisissez un type de document disponible. Les liens vers les documents associés récents sont ajoutés pour vous.",
        featureStage:
          "Choisissez la fonctionnalité à laquelle appartient ce travail, ou saisissez une nouvelle étiquette de fonctionnalité. Les nouveaux documents sont ajoutés au processus de la fonctionnalité.",
      },
      documentTypes: {
        adr: "Compte rendu de décision",
        audit: "Audit",
        document: "Document",
        exec: "Compte rendu d’étape",
        plan: "Plan",
        reference: "Référence",
        research: "Recherche",
      },
      emptyStates: {
        createFeatureTag: "Saisissez une nouvelle étiquette de fonctionnalité",
        noMatchingDocuments: "Aucun document correspondant",
      },
      errors: {
        createFailed:
          "Le document n’a pas pu être créé. Actualisez l’application, puis réessayez.",
        inFlight:
          "Ce document est toujours en cours de création. Patientez un instant, puis réessayez.",
        pathCollision:
          "Un document de ce type existe déjà aujourd’hui pour cette fonctionnalité. Choisissez un autre type ou réessayez demain.",
        projectChanged:
          "Le projet a changé avant la création du document. Vérifiez vos choix, puis réessayez.",
        scopeChanged:
          "L’emplacement du projet a changé. Rouvrez le projet, puis réessayez.",
      },
      hints: {
        adr: "Consigner une décision",
        audit: "Examiner le travail terminé ou démarrer un processus",
        notAvailable: "Ce type de document n’est pas encore disponible.",
        plan: "Planifier le travail",
        reference: "Relier le travail au code existant",
        requiresDecision: "Ajoutez d’abord un compte rendu de décision.",
        requiresResearchOrReference:
          "Ajoutez d’abord un document de recherche ou de référence.",
        research: "Explorer le problème",
      },
      labels: {
        documentType: "Type de document",
        feature: "Fonctionnalité",
        inThisFeature: "Dans cette fonctionnalité",
        linkedDocuments: "Documents liés",
        title: "Titre",
      },
      placeholders: {
        addLinkedDocument: "Ajouter un document lié",
        documentTitle: "Saisissez un titre de document",
        featureTag: "Saisissez une étiquette de fonctionnalité",
      },
      stages: {
        document: "Étape 2 sur 2 : ajouter un document",
        feature: "Étape 1 sur 2 : ajouter à une fonctionnalité",
      },
      states: {
        checkingCoverage: "Vérification de la progression de la fonctionnalité…",
        chooseFeatureForCoverage:
          "Choisissez ou saisissez une fonctionnalité pour voir sa progression.",
        coverageUnavailable:
          "La progression du projet n’est pas disponible. Actualisez les données du projet, puis réessayez.",
        emptyFeature:
          "Aucun document pour le moment. Ajoutez un document de recherche ou de référence pour démarrer cette fonctionnalité.",
        nextStep: "Étape suivante",
        notYet: "Pas encore",
        present: "Présent",
        selected: "Sélectionné",
      },
      titles: {
        document: "Ajouter un document",
        feature: "Ajouter à une fonctionnalité",
      },
      validation: {
        chooseAvailableDocumentType: "Choisissez un type de document disponible.",
        chooseDocumentType: "Choisissez un type de document.",
        chooseFeature: "Choisissez ou saisissez une fonctionnalité.",
        completeRequiredFields: "Saisissez une fonctionnalité et un titre.",
        requiresDecision: "Ajoutez d’abord un compte rendu de décision.",
        requiresResearchOrReference:
          "Ajoutez d’abord un document de recherche ou de référence.",
      },
    },
    documentTypes: {
      research: "Recherche",
      adr: "Décisions",
      plan: "Plans",
      exec: "Étapes",
      audit: "Audits",
      reference: "Références",
    },
    disabledReasons: {
      ...en.documents.disabledReasons,
      chooseTemporaryTab: "Choisissez un onglet temporaire à garder ouvert.",
      copyChangesBeforeReopening:
        "Copiez vos modifications, puis rouvrez le document avant d’enregistrer.",
      openForEditing: "Ouvrez un document à modifier.",
      openDocument: "Ouvrez d’abord un document.",
      openAnotherDocument: "Ouvrez un autre document, puis réessayez.",
      tryAfterSaving: "Réessayez une fois l’enregistrement terminé.",
      updateBeforeSaving: "Modifiez le document avant d’enregistrer.",
    },
    feedback: {
      alreadyLinked: "Ces documents sont déjà liés.",
      linkConflict:
        "Le document a été modifié avant de pouvoir être lié. Ouvrez-le, puis réessayez.",
      linkFailed: "Impossible de lier les documents. Réessayez.",
      linkInProgress: "Liaison des documents…",
      linkSucceeded: "Documents liés.",
    },
    tree: {
      created: "Créé le {{date}}",
      decisionStatusAccepted: "Acceptée",
      decisionStatusDeprecated: "Retirée",
      decisionStatusProposed: "Proposée",
      decisionStatusRejected: "Rejetée",
      decisionStatusSuperseded: "Remplacée",
      degraded: "Certains documents sont temporairement indisponibles.",
      lastEdited: "Dernière modification le {{date}}",
      emptyWorktree: "Aucun document dans cet arbre de travail pour le moment.",
      loading: "Chargement des documents…",
      noFilterMatches: "Aucun document ne correspond à ce filtre.",
      noFilterMatchesYet:
        "Aucun résultat pour le moment. La liste est toujours en cours de chargement.",
      partialAnnouncement: "Chargement des documents restants.",
      partialCount_one:
        "Chargement de la liste complète. {{count, number}} document disponible pour le moment.",
      partialCount_other:
        "Chargement de la liste complète. {{count, number}} documents disponibles pour le moment.",
      partialCount_many:
        "Chargement de la liste complète. {{count, number}} documents disponibles pour le moment.",
      planProgress: "{{done, number}} sur {{total, number}} terminés",
      sizeSummary_one: "{{count, number}} mot, {{size}}",
      sizeSummary_many: "{{count, number}} mots, {{size}}",
      sizeSummary_other: "{{count, number}} mots, {{size}}",
      unavailable:
        "Les documents sont indisponibles. Actualisez l’application, puis réessayez.",
      updated: "Mis à jour le {{date}}",
      vaultBrowser: "Navigateur du coffre",
      wordCount_one: "{{count, number}} mot",
      wordCount_many: "{{count, number}} mots",
      wordCount_other: "{{count, number}} mots",
      weightBelowThreshold: "Moins de {{threshold}}",
    },
    labels: {
      document: "Document",
      vault: "Coffre",
    },
    sortOptions: {
      latestActivity: "Activité récente",
      documentCount: "Nombre de documents",
      name: "Nom",
      creationDate: "Date de création",
      editDate: "Date de modification",
      length: "Longueur",
      workspaceShare: "Part de l’espace de travail",
    },
    shortcutGroups: {
      documents: "Documents",
      editing: "Modification du document",
    },
  },
  errors: {
    fallback: {
      contentUnavailable:
        "Ce contenu est indisponible. Rechargez la page et réessayez.",
    },
    unexpectedApplication: {
      message: "Rechargez la page et réessayez.",
      title: "Un problème est survenu",
    },
    unexpectedSection: {
      message: "Réessayez {{section}}.",
      title: "Cette section ne peut pas être affichée",
    },
  },
  features: {
    ...en.features,
    actions: {
      collapse: "Réduire la fonctionnalité",
      expand: "Développer la fonctionnalité",
      moveToNextFeature: "Passer à la fonctionnalité suivante",
      moveToPreviousFeature: "Passer à la fonctionnalité précédente",
      filterByFeature: "Filtrer par cette fonctionnalité",
    },
    feedback: {
      archiveRejected:
        "La fonctionnalité n’a pas été archivée. Vérifiez-la, puis réessayez.",
      archiveSucceeded: "Fonctionnalité archivée.",
      archiveUnavailable: "Impossible d’archiver la fonctionnalité. Réessayez.",
      repairRejected:
        "La fonctionnalité n’a pas été réparée. Vérifiez-la, puis réessayez.",
      repairSucceeded: "Fonctionnalité réparée.",
      repairUnavailable: "Impossible de réparer la fonctionnalité. Réessayez.",
    },
    labels: {
      feature: "Fonctionnalités",
    },
  },
  graph: {
    accessibility: {
      selectedItem: "Élément sélectionné : {{item}}.",
      selectedItemGeneric: "Élément sélectionné.",
      workingSet: "Ensemble de travail",
      workingSetCount_many: "{{count, number}} éléments dans l’ensemble de travail",
      workingSetCount_one: "{{count, number}} élément dans l’ensemble de travail",
      workingSetCount_other: "{{count, number}} éléments dans l’ensemble de travail",
      hiddenByActiveFilter: "Masqué par le filtre actif",
      namedWorkingSetItemHidden: "{{item}} est masqué par le filtre actif.",
      workingSetItemHidden: "L’élément est masqué par le filtre actif.",
    },
    actions: {
      addItemToWorkingSet: "Ajouter l’élément à l’ensemble de travail",
      addSelectedItemToWorkingSet:
        "Ajouter l’élément sélectionné à l’ensemble de travail",
      clearSelection: "Effacer la sélection du graphe",
      clearWorkingSet: "Effacer l’ensemble de travail",
      expandFocusedItem: "Développer l’élément actif dans l’espace de travail",
      fitToView: "Adapter le graphe à la vue",
      moveToNextConnectedItem: "Passer à l’élément connecté suivant",
      moveToPreviousConnectedItem: "Passer à l’élément connecté précédent",
      openFocusedItem: "Ouvrir l’élément actif",
      pauseMovement: "Suspendre le mouvement du graphe",
      pinItem: "Épingler l’élément",
      resetSettings: "Réinitialiser les paramètres du graphe",
      resetView: "Réinitialiser la vue du graphe",
      removeItemFromWorkingSet: "Retirer l’élément de l’ensemble de travail",
      removeNamedItemFromWorkingSet: "Retirer {{item}} de l’ensemble de travail",
      removeLastItemFromWorkingSet:
        "Retirer le dernier élément de l’ensemble de travail",
      resumeMovement: "Reprendre le mouvement du graphe",
      showRelatedItem: "Afficher l’élément associé",
      showStartingItem: "Afficher l’élément de départ",
      unpinItem: "Désépingler l’élément",
      zoomIn: "Agrandir",
      zoomOut: "Réduire",
    },
    disabledReasons: {
      chooseConnectionWithSummary: "Choisissez une connexion avec un résumé à copier.",
      chooseItemWithTitle: "Choisissez un élément avec un titre à copier.",
      relatedItemUnavailable:
        "Actualisez les données, puis réessayez d’afficher l’élément associé.",
      startingItemUnavailable:
        "Actualisez les données, puis réessayez d’afficher l’élément de départ.",
    },
    shortcutGroups: {
      workingSet: "Ensemble de travail",
    },
    labels: {
      item: "Élément",
    },
  },
  operations: {
    actions: {
      applySearchSettings: "Appliquer les paramètres de recherche",
      checkWorkspace: "Vérifier l’espace de travail",
      disableSearch: "Désactiver la recherche",
      enableSearch: "Activer la recherche",
      refreshSearch: "Actualiser la recherche",
      showWorkspaceDetails: "Afficher les détails de l’espace de travail",
    },
    feedback: {
      applySearchSettings: {
        failed: "Impossible d’appliquer les paramètres de recherche. Réessayez.",
        running: "Application des paramètres de recherche…",
        succeeded: "Paramètres de recherche appliqués.",
        unavailable: "La recherche est indisponible. Activez-la, puis réessayez.",
      },
      checkWorkspace: {
        failed: "Impossible de vérifier l’espace de travail. Réessayez.",
        running: "Vérification de l’espace de travail…",
        succeeded: "Vérification de l’espace de travail terminée.",
      },
      disableSearch: {
        failed: "Impossible de désactiver la recherche. Réessayez.",
        running: "Désactivation de la recherche…",
        succeeded: "Recherche désactivée.",
      },
      enableSearch: {
        failed: "Impossible d’activer la recherche. Réessayez.",
        running: "Activation de la recherche…",
        succeeded: "Recherche activée.",
        unavailable: "La recherche reste indisponible. Réessayez.",
      },
      refreshSearch: {
        failed: "Impossible d’actualiser la recherche. Réessayez.",
        running: "Actualisation de la recherche…",
        succeeded: "Actualisation de la recherche lancée.",
        unavailable: "La recherche est indisponible. Activez-la, puis réessayez.",
      },
      showWorkspaceDetails: {
        failed: "Impossible de charger les détails de l’espace de travail. Réessayez.",
        running: "Chargement des détails de l’espace de travail…",
        succeeded: "Détails de l’espace de travail chargés.",
      },
    },
  },
  projects: {
    actions: {
      add: "Ajouter un projet…",
      checkProjectStatus: "Vérifier l’état du projet",
      clearHistory: "Effacer l’historique des projets",
      openPullRequest: "Ouvrir la demande de fusion",
      prepareProjectTools: "Configurer les outils du projet",
      setUpProject: "Configurer le projet",
      switch: "Changer de projet…",
      switchWorktree: "Basculer vers l’arbre de travail",
      updateProject: "Mettre à jour le projet",
      updateProjectTools: "Mettre à jour les outils du projet",
    },
    confirmations: {
      replaceSetup: {
        body: "Cette action remplace les fichiers de configuration existants et peut écraser vos modifications. Enregistrez une sauvegarde avant de continuer.",
        title: "Remplacer la configuration du projet ?",
      },
    },
    destructiveActions: {
      replaceSetup: "Remplacer la configuration du projet",
    },
    disabledReasons: {
      chooseWorktreeWithProjectFiles:
        "Choisissez un autre arbre de travail contenant les fichiers du projet.",
      installRequiredProjectTools:
        "Installez les outils de projet requis, puis réessayez.",
      noSetupChangesNeeded: "Revenez au projet pour continuer.",
      prepareFolderAsGitProject:
        "Préparez ce dossier comme projet Git, puis réessayez.",
      refreshProjectForPullRequest: "Actualisez les données du projet, puis réessayez.",
      setUpProjectFirst: "Configurez le projet, puis réessayez.",
      waitForProjectStatus:
        "Attendez le chargement de l’état du projet, puis réessayez.",
    },
    provisioning: {
      description: "Configurez ce projet pour continuer.",
      details: {
        installRequiredProjectTools:
          "Installez les outils de projet requis, puis réessayez.",
        prepareFolderAsGitProject:
          "Préparez ce dossier comme projet Git, puis réessayez.",
      },
      progress: "Configuration du projet…",
      result: {
        completed: "Configuration du projet terminée",
        failed: "Échec de la configuration du projet",
        indeterminate:
          "La configuration est peut-être toujours en cours. Vérifiez l’état du projet avant de réessayer.",
        itemCount_one: "{{count, number}} élément",
        itemCount_many: "{{count, number}} éléments",
        itemCount_other: "{{count, number}} éléments",
        status: {
          created: "Créé",
          failed: "Échec",
          mixed: "Résultats mixtes",
          removed: "Supprimé",
          restored: "Restauré",
          skipped: "Ignoré",
          updated: "Mis à jour",
          upToDate: "Déjà à jour",
        },
      },
      startFailed: "La configuration du projet n’a pas pu démarrer. Réessayez.",
      statusUnavailable: "L’état du projet est indisponible",
      title: "Configuration du projet requise",
    },
    shortcutGroups: {
      projects: "Projets",
    },
  },
  settings: {
    actions: {
      useDarkTheme: "Utiliser le thème sombre",
      useHighContrastTheme: "Utiliser le thème à contraste élevé",
      useLightTheme: "Utiliser le thème clair",
      useSystemTheme: "Utiliser le thème du système",
    },
    groups: {
      appearance: "Apparence",
      graph: "Graphe",
      keybindings: "Raccourcis clavier",
    },
    fields: {
      theme: { label: "Thème", description: "Choisissez le thème de l’interface." },
      reduceMotion: {
        label: "Réduire les animations",
        description: "Utilisez moins d’animations dans l’interface.",
      },
      activitySectionFolds: {
        label: "Sections d’activité",
        description: "Mémorisez les sections d’activité ouvertes.",
      },
      language: {
        label: "Langue",
        description: "Choisissez la langue de l’interface.",
      },
      defaultGranularity: {
        label: "Niveau de détail par défaut",
        description: "Choisissez le niveau de détail initial du graphe.",
      },
      corpus: {
        label: "Contenu du graphe",
        description: "Choisissez le contenu affiché dans le graphe.",
      },
      timelineDate: {
        label: "Date de la chronologie",
        description: "Choisissez la date qui contrôle la chronologie.",
      },
      confidenceFloor: {
        label: "Certitude minimale des connexions",
        description: "Masquez les connexions sous ce niveau de certitude.",
      },
      labelFilter: {
        label: "Filtre par nom",
        description: "Affichez les éléments dont le nom correspond.",
        placeholder: "Filtrer par nom",
      },
      graphControls: {
        label: "Commandes du graphe",
        description: "Personnalisez la navigation du graphe.",
      },
      shortcuts: {
        label: "Raccourcis clavier",
        description: "Personnalisez les commandes clavier.",
      },
    },
    options: {
      system: "Système",
      light: "Clair",
      dark: "Sombre",
      highContrast: "Contraste élevé",
      english: "Anglais",
    },
  },
  timeline: {
    accessibility: {
      dateField: "Date de la chronologie",
    },
    actions: {
      clearDateRange: "Effacer la période",
      filterByCreationDate: "Filtrer par date de création",
      filterByCreationDateCurrent: "Filtrer par date de création (actuelle)",
      filterByEditDate: "Filtrer par date de modification",
      filterByEditDateCurrent: "Filtrer par date de modification (actuelle)",
      filterByUpdateDate: "Filtrer par date de mise à jour",
      filterByUpdateDateCurrent: "Filtrer par date de mise à jour (actuelle)",
      showLast24Hours: "Afficher les dernières 24 heures",
      showLast7Days: "Afficher les 7 derniers jours",
      showLast30Days: "Afficher les 30 derniers jours",
      showLast90Days: "Afficher les 90 derniers jours",
      viewProjectAtVersion: "Afficher le projet dans cette version",
    },
    criteria: {
      created: "Création",
      modified: "Modification",
      stamped: "Mise à jour",
    },
    descriptions: {
      useCreationDateForRange: "Utiliser la date de création pour la période",
      useEditDateForRange: "Utiliser la date de modification pour la période",
      useUpdateDateForRange: "Utiliser la date de mise à jour pour la période",
    },
    disabledReasons: {
      codeFiles:
        "Choisissez la date de modification. Les fichiers de code utilisent les dates de modification.",
      chooseProject: "Choisissez un projet, puis réessayez.",
      current: "Choisissez une autre option de date pour modifier la chronologie.",
      modifiedUnavailable:
        "Choisissez la date de création. Les dates de modification ne sont pas disponibles ici.",
      refreshHistory: "Actualisez l’historique du projet, puis réessayez.",
      stampedUnavailable:
        "Choisissez la date de création. Les dates de mise à jour ne sont pas disponibles ici.",
      switchToDocumentsForHistory:
        "Passez aux documents pour afficher l’historique du projet.",
    },
    labels: {
      timeline: "Chronologie",
    },
  },
} as const;

export const rtlTestResources = {
  common: {
    accessibility: {
      ...en.common.accessibility,
      actionsForItem: "إجراءات {{item}}",
      back: "رجوع",
      recordShortcut: "تسجيل اختصار لـ {{action}}",
      resizeActivityPanel: "تغيير حجم لوحة النشاط",
      resizeNavigationPanel: "تغيير حجم لوحة التنقل",
      resizeTimeline: "تغيير حجم المخطط الزمني",
      resetShortcut: "إعادة تعيين اختصار {{action}}",
      skipToContent: "التخطي إلى المحتوى",
      switchWorkspace: "تبديل مساحة العمل من {{workspace}}",
    },
    actions: {
      ...en.common.actions,
      cancel: "إلغاء",
      close: "إغلاق",
      collapseNavigationPanel: "طي لوحة التنقل",
      copyBranchName: "نسخ اسم الفرع",
      copyCategoryName: "نسخ اسم الفئة",
      copyCommitHash: "نسخ بصمة الالتزام",
      copyCommitMessage: "نسخ رسالة الالتزام",
      copyFeatureTag: "نسخ وسم الميزة",
      copyPullRequestLink: "نسخ رابط طلب الدمج",
      copyPullRequestNumber: "نسخ رقم طلب الدمج",
      copyShortCommitHash: "نسخ بصمة الالتزام المختصرة",
      hideActivityPanel: "إخفاء لوحة النشاط",
      hideNavigationPanel: "إخفاء لوحة التنقل",
      hideTimeline: "إخفاء المخطط الزمني",
      moveToNextPanel: "الانتقال إلى اللوحة التالية",
      moveToPreviousPanel: "الانتقال إلى اللوحة السابقة",
      openCommandPalette: "فتح لوحة الأوامر…",
      refreshData: "تحديث البيانات",
      reloadPage: "إعادة تحميل الصفحة",
      reset: "إعادة تعيين",
      resetLayout: "إعادة تعيين التخطيط",
      retry: "إعادة المحاولة",
      expandNavigationPanel: "توسيع لوحة التنقل",
      searchDocumentsAndCode: "البحث في المستندات والتعليمات البرمجية…",
      showActivityPanel: "إظهار لوحة النشاط",
      showNavigationPanel: "إظهار لوحة التنقل",
      showTimeline: "إظهار المخطط الزمني",
      showChanges: "إظهار التغييرات",
      showOrHideGraph: "إظهار الرسم البياني أو إخفاؤه",
      showOnCanvas: "إظهار على اللوحة",
      showStatus: "إظهار الحالة",
    },
    activityTabs: {
      changes: "التغييرات",
      status: "الحالة",
    },
    commandFamilies: {
      editing: "التحرير",
      filters: "عوامل التصفية",
      focus: "التركيز",
      general: "عام",
      help: "المساعدة",
      layout: "التخطيط",
      navigation: "التنقل",
      refresh: "التحديث",
      search: "البحث",
      searchMaintenance: "صيانة البحث",
      settings: "الإعدادات",
      workspaceMaintenance: "صيانة مساحة العمل",
    },
    commandPalette: {
      dialogLabel: "لوحة الأوامر",
      inputPlaceholder: "البحث في الأوامر",
      listboxLabel: "الأوامر",
      noMatches: "لا توجد أوامر مطابقة",
      loading: "جارٍ تحميل الأوامر…",
      selectionAnnouncement_few: "{{count, number}} أوامر. {{command}}",
      selectionAnnouncement_many: "{{count, number}} أمرًا. {{command}}",
      selectionAnnouncement_one: "{{count, number}} أمر. {{command}}",
      selectionAnnouncement_other: "{{count, number}} أمر. {{command}}",
      selectionAnnouncement_two: "{{count, number}} أمران. {{command}}",
      selectionAnnouncement_zero: "{{count, number}} أمر. {{command}}",
      footer: {
        navigate: "تنقل",
        open: "فتح",
        close: "إغلاق",
      },
    },
    palette: {
      commandCount_few: "{{count, number}} أوامر",
      commandCount_many: "{{count, number}} أمرًا",
      commandCount_one: "{{count, number}} أمر",
      commandCount_other: "{{count, number}} أمر",
      commandCount_two: "{{count, number}} أمران",
      commandCount_zero: "{{count, number}} أمر",
    },
    disabledReasons: {
      ...en.common.disabledReasons,
      itemUnavailableOnCanvas: "حدّث البيانات، ثم حاول إظهار هذا العنصر على اللوحة.",
    },
    feedback: {
      actionUnavailable: "تعذر إكمال الإجراء. أعد تحميل الصفحة وحاول مرة أخرى.",
      copyFailed: "تعذر النسخ. حاول مرة أخرى.",
      copySucceeded: "تم النسخ.",
    },
    destructiveActions: {
      discardChanges: "تجاهل التغييرات",
    },
    shortcutDialog: en.common.shortcutDialog,
    shortcutSettings: {
      conflict: "هذا الاختصار مخصص بالفعل لـ {{action}}. اختر اختصارًا آخر.",
      empty: "لا توجد اختصارات لوحة مفاتيح متاحة",
      recording: "اضغط على مفتاح…",
    },
    shortcutGroups: {
      general: "عام",
      graph: "الرسم البياني",
      navigation: "التنقل",
      window: "النافذة",
    },
    keycaps: {
      ...en.common.keycaps,
      arrowDown: "سهم للأسفل",
      arrowLeft: "سهم لليسار",
      arrowRight: "سهم لليمين",
      arrowUp: "سهم للأعلى",
      backspace: "مسح للخلف",
      delete: "حذف",
      enter: "إدخال",
      escape: "خروج",
      shift: "تبديل",
      space: "مسافة",
    },
    statuses: en.common.statuses,
  },
  documents: {
    ...en.documents,
    accessibility: {
      addDocumentToFeature: "إضافة مستند إلى ميزة",
      browserView: "عرض المتصفح",
      decisionAccepted: "القرار مقبول",
      decisionDeprecated: "تم سحب القرار",
      decisionProposed: "القرار مقترح",
      decisionRejected: "القرار مرفوض",
      decisionSuperseded: "تم استبدال القرار",
      planComplete: "الخطة مكتملة",
      planInProgress: "الخطة قيد التنفيذ",
      planNotStarted: "لم تبدأ الخطة",
      treeBrowser: "شجرة المستندات",
      switchReadingAndEditingShortcut: "التبديل بين القراءة والتحرير ({{accelerator}})",
      treeOptionsSortedByLatestActivity: "خيارات شجرة المستندات، مرتبة حسب أحدث نشاط",
      treeOptionsSortedByDocumentCount:
        "خيارات شجرة المستندات، مرتبة حسب عدد المستندات",
      treeOptionsSortedByName: "خيارات شجرة المستندات، مرتبة حسب الاسم",
      treeOptionsSortedByCreationDate: "خيارات شجرة المستندات، مرتبة حسب تاريخ الإنشاء",
      treeOptionsSortedByEditDate: "خيارات شجرة المستندات، مرتبة حسب تاريخ التعديل",
      treeOptionsSortedByLength: "خيارات شجرة المستندات، مرتبة حسب الطول",
      treeOptionsSortedByWorkspaceShare:
        "خيارات شجرة المستندات، مرتبة حسب حصة مساحة العمل",
    },
    actions: {
      ...en.documents.actions,
      addComment: "إضافة تعليق",
      browseDocuments: "تصفح المستندات",
      browseFiles: "تصفح الملفات",
      closeAllDocuments: "إغلاق جميع المستندات",
      closeDocument: "إغلاق المستند",
      closeOtherDocuments: "إغلاق المستندات الأخرى",
      closeActiveTab: "إغلاق علامة تبويب المستند النشط",
      collapseCategory: "طي الفئة",
      finishEditing: "إنهاء التحرير",
      findByName: "البحث عن مستند بالاسم…",
      expandCategory: "توسيع الفئة",
      keepDocumentOpen: "إبقاء المستند مفتوحًا",
      keepTabOpen: "إبقاء علامة التبويب مفتوحة",
      reloadDocument: "إعادة تحميل المستند",
      nextTab: "الانتقال إلى علامة تبويب المستند التالية",
      openComments: "فتح التعليقات",
      previousTab: "الانتقال إلى علامة تبويب المستند السابقة",
      resetSorting: "إعادة تعيين الترتيب",
      save: "حفظ المستند",
      sortByLatestActivity: "الترتيب حسب أحدث نشاط",
      sortByDocumentCount: "الترتيب حسب عدد المستندات",
      sortByName: "الترتيب حسب الاسم",
      sortByCreationDate: "الترتيب حسب تاريخ الإنشاء",
      sortByEditDate: "الترتيب حسب تاريخ التعديل",
      sortByLength: "الترتيب حسب الطول",
      sortByWorkspaceShare: "الترتيب حسب حصة مساحة العمل",
      showOrHideChanges: "إظهار التغييرات أو إخفاؤها",
      filterByDocumentType: "التصفية حسب نوع المستند هذا",
      switchReadingAndEditing: "التبديل بين القراءة والتحرير",
    },
    browserModes: {
      documents: "المستندات",
      files: "الملفات",
    },
    categories: {
      code: "التعليمات البرمجية",
    },
    createDialog: {
      accessibility: {
        addLinkedDocument: "إضافة مستند مرتبط",
        backToFeature: "الرجوع إلى الميزة",
        documentType: "نوع المستند",
        feature: "الميزة",
        linkedDocuments: "المستندات المرتبطة",
        pipelineCoverage: "تقدم سير العمل",
        removeLinkedDocument: "إزالة {{document}}",
        title: "العنوان",
      },
      actions: {
        back: "رجوع",
        continue: "متابعة",
        create: "إنشاء",
        creating: "جارٍ إنشاء المستند…",
      },
      descriptions: {
        documentStage:
          "اختر نوع مستند متاحًا. ستُضاف لك روابط إلى المستندات الحديثة ذات الصلة.",
        featureStage:
          "اختر الميزة التي ينتمي إليها هذا العمل، أو أدخل وسم ميزة جديدًا. تُضاف المستندات الجديدة إلى سير عمل الميزة.",
      },
      documentTypes: {
        adr: "سجل قرار",
        audit: "تدقيق",
        document: "مستند",
        exec: "سجل خطوة",
        plan: "خطة",
        reference: "مرجع",
        research: "بحث",
      },
      emptyStates: {
        createFeatureTag: "أدخل وسم ميزة جديدًا",
        noMatchingDocuments: "لا توجد مستندات مطابقة",
      },
      errors: {
        createFailed: "تعذر إنشاء المستند. حدّث التطبيق، ثم حاول مرة أخرى.",
        inFlight: "لا يزال هذا المستند قيد الإنشاء. انتظر لحظة، ثم حاول مرة أخرى.",
        pathCollision:
          "يوجد اليوم مستند من هذا النوع لهذه الميزة. اختر نوعًا آخر أو حاول مرة أخرى غدًا.",
        projectChanged:
          "تغيّر المشروع قبل إنشاء المستند. راجع اختياراتك، ثم حاول مرة أخرى.",
        scopeChanged: "تغيّر موقع المشروع. أعد فتح المشروع، ثم حاول مرة أخرى.",
      },
      hints: {
        adr: "تسجيل قرار",
        audit: "مراجعة العمل المكتمل أو بدء سير عمل",
        notAvailable: "نوع المستند هذا غير متاح بعد.",
        plan: "تخطيط العمل",
        reference: "ربط العمل بالتعليمات البرمجية الموجودة",
        requiresDecision: "أضف سجل قرار أولاً.",
        requiresResearchOrReference: "أضف مستند بحث أو مرجع أولاً.",
        research: "استكشاف المشكلة",
      },
      labels: {
        documentType: "نوع المستند",
        feature: "الميزة",
        inThisFeature: "في هذه الميزة",
        linkedDocuments: "المستندات المرتبطة",
        title: "العنوان",
      },
      placeholders: {
        addLinkedDocument: "إضافة مستند مرتبط",
        documentTitle: "أدخل عنوان مستند",
        featureTag: "أدخل وسم ميزة",
      },
      stages: {
        document: "الخطوة 2 من 2: إضافة مستند",
        feature: "الخطوة 1 من 2: الإضافة إلى ميزة",
      },
      states: {
        checkingCoverage: "جارٍ التحقق من تقدم الميزة…",
        chooseFeatureForCoverage: "اختر ميزة أو أدخلها لرؤية تقدمها.",
        coverageUnavailable:
          "تقدم المشروع غير متاح. حدّث بيانات المشروع، ثم حاول مرة أخرى.",
        emptyFeature: "لا توجد مستندات بعد. أضف مستند بحث أو مرجع لبدء هذه الميزة.",
        nextStep: "الخطوة التالية",
        notYet: "ليس بعد",
        present: "موجود",
        selected: "محدد",
      },
      titles: {
        document: "إضافة مستند",
        feature: "الإضافة إلى ميزة",
      },
      validation: {
        chooseAvailableDocumentType: "اختر نوع مستند متاحًا.",
        chooseDocumentType: "اختر نوع مستند.",
        chooseFeature: "اختر ميزة أو أدخلها.",
        completeRequiredFields: "أدخل ميزة وعنوانًا.",
        requiresDecision: "أضف سجل قرار أولاً.",
        requiresResearchOrReference: "أضف مستند بحث أو مرجع أولاً.",
      },
    },
    documentTypes: {
      research: "البحث",
      adr: "القرارات",
      plan: "الخطط",
      exec: "الخطوات",
      audit: "عمليات التدقيق",
      reference: "المراجع",
    },
    disabledReasons: {
      ...en.documents.disabledReasons,
      chooseTemporaryTab: "اختر علامة تبويب مؤقتة لإبقائها مفتوحة.",
      copyChangesBeforeReopening: "انسخ تغييراتك، ثم أعد فتح المستند قبل الحفظ.",
      openForEditing: "افتح مستندًا لتحريره.",
      openDocument: "افتح مستندًا أولاً.",
      openAnotherDocument: "افتح مستندًا آخر، ثم حاول مرة أخرى.",
      tryAfterSaving: "حاول مرة أخرى بعد اكتمال الحفظ.",
      updateBeforeSaving: "حدّث المستند قبل الحفظ.",
    },
    feedback: {
      alreadyLinked: "هذه المستندات مرتبطة بالفعل.",
      linkConflict: "تغير المستند قبل ربطه. افتحه، ثم حاول مرة أخرى.",
      linkFailed: "تعذر ربط المستندات. حاول مرة أخرى.",
      linkInProgress: "جارٍ ربط المستندات…",
      linkSucceeded: "تم ربط المستندات.",
    },
    tree: {
      created: "تم الإنشاء في {{date}}",
      decisionStatusAccepted: "مقبول",
      decisionStatusDeprecated: "مسحوب",
      decisionStatusProposed: "مقترح",
      decisionStatusRejected: "مرفوض",
      decisionStatusSuperseded: "مستبدل",
      degraded: "بعض المستندات غير متاحة مؤقتًا.",
      lastEdited: "آخر تعديل في {{date}}",
      emptyWorktree: "لا توجد مستندات في شجرة العمل هذه حتى الآن.",
      loading: "جارٍ تحميل المستندات…",
      noFilterMatches: "لا توجد مستندات تطابق هذا الفلتر.",
      noFilterMatchesYet: "لا توجد نتائج حتى الآن. ما زال تحميل القائمة جاريًا.",
      partialAnnouncement: "جارٍ تحميل المستندات المتبقية.",
      partialCount_one:
        "جارٍ تحميل القائمة الكاملة. يتوفر {{count, number}} مستند حتى الآن.",
      partialCount_zero:
        "جارٍ تحميل القائمة الكاملة. يتوفر {{count, number}} مستند حتى الآن.",
      partialCount_two:
        "جارٍ تحميل القائمة الكاملة. يتوفر {{count, number}} مستندان حتى الآن.",
      partialCount_few:
        "جارٍ تحميل القائمة الكاملة. تتوفر {{count, number}} مستندات حتى الآن.",
      partialCount_many:
        "جارٍ تحميل القائمة الكاملة. يتوفر {{count, number}} مستندًا حتى الآن.",
      partialCount_other:
        "جارٍ تحميل القائمة الكاملة. يتوفر {{count, number}} مستند حتى الآن.",
      planProgress: "اكتمل {{done, number}} من {{total, number}}",
      sizeSummary_one: "{{count, number}} كلمة، {{size}}",
      sizeSummary_zero: "{{count, number}} كلمة، {{size}}",
      sizeSummary_two: "{{count, number}} كلمتان، {{size}}",
      sizeSummary_few: "{{count, number}} كلمات، {{size}}",
      sizeSummary_many: "{{count, number}} كلمة، {{size}}",
      sizeSummary_other: "{{count, number}} كلمة، {{size}}",
      unavailable: "المستندات غير متاحة. حدّث التطبيق، ثم حاول مرة أخرى.",
      updated: "تاريخ التحديث {{date}}",
      vaultBrowser: "متصفح الخزنة",
      wordCount_one: "{{count, number}} كلمة",
      wordCount_zero: "{{count, number}} كلمة",
      wordCount_two: "{{count, number}} كلمتان",
      wordCount_few: "{{count, number}} كلمات",
      wordCount_many: "{{count, number}} كلمة",
      wordCount_other: "{{count, number}} كلمة",
      weightBelowThreshold: "أقل من {{threshold}}",
    },
    labels: {
      document: "مستند",
      vault: "الخزنة",
    },
    sortOptions: {
      latestActivity: "أحدث نشاط",
      documentCount: "عدد المستندات",
      name: "الاسم",
      creationDate: "تاريخ الإنشاء",
      editDate: "تاريخ التعديل",
      length: "الطول",
      workspaceShare: "حصة مساحة العمل",
    },
    shortcutGroups: {
      documents: "المستندات",
      editing: "تحرير المستند",
    },
  },
  errors: {
    fallback: {
      contentUnavailable: "هذا المحتوى غير متاح. أعد تحميل الصفحة وحاول مرة أخرى.",
    },
    unexpectedApplication: {
      message: "أعد تحميل الصفحة وحاول مرة أخرى.",
      title: "حدث خطأ ما",
    },
    unexpectedSection: {
      message: "حاول فتح {{section}} مرة أخرى.",
      title: "تعذر عرض هذا القسم",
    },
  },
  features: {
    ...en.features,
    actions: {
      collapse: "طي الميزة",
      expand: "توسيع الميزة",
      moveToNextFeature: "الانتقال إلى الميزة التالية",
      moveToPreviousFeature: "الانتقال إلى الميزة السابقة",
      filterByFeature: "التصفية حسب هذه الميزة",
    },
    feedback: {
      archiveRejected: "لم تتم أرشفة الميزة. تحقق منها، ثم حاول مرة أخرى.",
      archiveSucceeded: "تمت أرشفة الميزة.",
      archiveUnavailable: "تعذرت أرشفة الميزة. حاول مرة أخرى.",
      repairRejected: "لم يتم إصلاح الميزة. تحقق منها، ثم حاول مرة أخرى.",
      repairSucceeded: "تم إصلاح الميزة.",
      repairUnavailable: "تعذر إصلاح الميزة. حاول مرة أخرى.",
    },
    labels: {
      feature: "الميزات",
    },
  },
  graph: {
    accessibility: {
      selectedItem: "تم تحديد {{item}}.",
      selectedItemGeneric: "تم تحديد العنصر.",
      workingSet: "مجموعة العمل",
      workingSetCount_zero: "{{count, number}} عنصر في مجموعة العمل",
      workingSetCount_one: "{{count, number}} عنصر في مجموعة العمل",
      workingSetCount_two: "{{count, number}} من العناصر في مجموعة العمل",
      workingSetCount_few: "{{count, number}} عناصر في مجموعة العمل",
      workingSetCount_many: "{{count, number}} عنصرًا في مجموعة العمل",
      workingSetCount_other: "{{count, number}} عنصر في مجموعة العمل",
      hiddenByActiveFilter: "مخفي بواسطة عامل التصفية النشط",
      namedWorkingSetItemHidden: "{{item}} مخفي بواسطة عامل التصفية النشط.",
      workingSetItemHidden: "العنصر مخفي بواسطة عامل التصفية النشط.",
    },
    actions: {
      addItemToWorkingSet: "إضافة العنصر إلى مجموعة العمل",
      addSelectedItemToWorkingSet: "إضافة العنصر المحدد إلى مجموعة العمل",
      clearSelection: "مسح تحديد الرسم البياني",
      clearWorkingSet: "مسح مجموعة العمل",
      expandFocusedItem: "توسيع العنصر المحدد ضمن مساحة العمل",
      fitToView: "ملاءمة الرسم البياني للعرض",
      moveToNextConnectedItem: "الانتقال إلى العنصر المتصل التالي",
      moveToPreviousConnectedItem: "الانتقال إلى العنصر المتصل السابق",
      openFocusedItem: "فتح العنصر المحدد",
      pauseMovement: "إيقاف حركة الرسم البياني مؤقتًا",
      pinItem: "تثبيت العنصر",
      resetSettings: "إعادة تعيين إعدادات الرسم البياني",
      resetView: "إعادة تعيين عرض الرسم البياني",
      removeItemFromWorkingSet: "إزالة العنصر من مجموعة العمل",
      removeNamedItemFromWorkingSet: "إزالة {{item}} من مجموعة العمل",
      removeLastItemFromWorkingSet: "إزالة العنصر الأخير من مجموعة العمل",
      resumeMovement: "استئناف حركة الرسم البياني",
      showRelatedItem: "إظهار العنصر المرتبط",
      showStartingItem: "إظهار عنصر البداية",
      unpinItem: "إلغاء تثبيت العنصر",
      zoomIn: "تكبير",
      zoomOut: "تصغير",
    },
    disabledReasons: {
      chooseConnectionWithSummary: "اختر اتصالًا له ملخص لنسخه.",
      chooseItemWithTitle: "اختر عنصرًا له عنوان لنسخه.",
      relatedItemUnavailable: "حدّث البيانات، ثم حاول إظهار العنصر المرتبط مرة أخرى.",
      startingItemUnavailable: "حدّث البيانات، ثم حاول إظهار عنصر البداية مرة أخرى.",
    },
    shortcutGroups: {
      workingSet: "مجموعة العمل",
    },
    labels: {
      item: "عنصر",
    },
  },
  operations: {
    actions: {
      applySearchSettings: "تطبيق إعدادات البحث",
      checkWorkspace: "فحص مساحة العمل",
      disableSearch: "تعطيل البحث",
      enableSearch: "تمكين البحث",
      refreshSearch: "تحديث البحث",
      showWorkspaceDetails: "عرض تفاصيل مساحة العمل",
    },
    feedback: {
      applySearchSettings: {
        failed: "تعذر تطبيق إعدادات البحث. حاول مرة أخرى.",
        running: "جارٍ تطبيق إعدادات البحث…",
        succeeded: "تم تطبيق إعدادات البحث.",
        unavailable: "البحث غير متاح. مكّن البحث، ثم حاول مرة أخرى.",
      },
      checkWorkspace: {
        failed: "تعذر فحص مساحة العمل. حاول مرة أخرى.",
        running: "جارٍ فحص مساحة العمل…",
        succeeded: "اكتمل فحص مساحة العمل.",
      },
      disableSearch: {
        failed: "تعذر تعطيل البحث. حاول مرة أخرى.",
        running: "جارٍ تعطيل البحث…",
        succeeded: "تم تعطيل البحث.",
      },
      enableSearch: {
        failed: "تعذر تمكين البحث. حاول مرة أخرى.",
        running: "جارٍ تمكين البحث…",
        succeeded: "تم تمكين البحث.",
        unavailable: "لا يزال البحث غير متاح. حاول مرة أخرى.",
      },
      refreshSearch: {
        failed: "تعذر تحديث البحث. حاول مرة أخرى.",
        running: "جارٍ تحديث البحث…",
        succeeded: "بدأ تحديث البحث.",
        unavailable: "البحث غير متاح. مكّن البحث، ثم حاول مرة أخرى.",
      },
      showWorkspaceDetails: {
        failed: "تعذر تحميل تفاصيل مساحة العمل. حاول مرة أخرى.",
        running: "جارٍ تحميل تفاصيل مساحة العمل…",
        succeeded: "تم تحميل تفاصيل مساحة العمل.",
      },
    },
  },
  projects: {
    actions: {
      add: "إضافة مشروع…",
      checkProjectStatus: "التحقق من حالة المشروع",
      clearHistory: "مسح سجل المشاريع",
      openPullRequest: "فتح طلب الدمج",
      prepareProjectTools: "إعداد أدوات المشروع",
      setUpProject: "إعداد المشروع",
      switch: "تبديل المشروع…",
      switchWorktree: "التبديل إلى شجرة العمل",
      updateProject: "تحديث المشروع",
      updateProjectTools: "تحديث أدوات المشروع",
    },
    confirmations: {
      replaceSetup: {
        body: "يستبدل هذا ملفات الإعداد الحالية وقد يستبدل تغييراتك. احفظ نسخة احتياطية قبل المتابعة.",
        title: "استبدال إعداد المشروع؟",
      },
    },
    destructiveActions: {
      replaceSetup: "استبدال إعداد المشروع",
    },
    disabledReasons: {
      chooseWorktreeWithProjectFiles: "اختر شجرة عمل أخرى تحتوي على ملفات المشروع.",
      installRequiredProjectTools: "ثبّت أدوات المشروع المطلوبة، ثم حاول مرة أخرى.",
      noSetupChangesNeeded: "ارجع إلى المشروع للمتابعة.",
      prepareFolderAsGitProject: "جهّز هذا المجلد كمشروع Git، ثم حاول مرة أخرى.",
      refreshProjectForPullRequest: "حدّث بيانات المشروع، ثم حاول مرة أخرى.",
      setUpProjectFirst: "أعدّ المشروع، ثم حاول مرة أخرى.",
      waitForProjectStatus: "انتظر حتى يتم تحميل حالة المشروع، ثم حاول مرة أخرى.",
    },
    provisioning: {
      description: "أعدّ هذا المشروع للمتابعة.",
      details: {
        installRequiredProjectTools: "ثبّت أدوات المشروع المطلوبة، ثم حاول مرة أخرى.",
        prepareFolderAsGitProject: "جهّز هذا المجلد كمشروع Git، ثم حاول مرة أخرى.",
      },
      progress: "جارٍ إعداد المشروع…",
      result: {
        completed: "اكتمل إعداد المشروع",
        failed: "فشل إعداد المشروع",
        indeterminate:
          "قد يكون الإعداد لا يزال قيد التنفيذ. تحقق من حالة المشروع قبل المحاولة مرة أخرى.",
        itemCount_zero: "{{count, number}} عنصر",
        itemCount_one: "{{count, number}} عنصر",
        itemCount_two: "{{count, number}} عنصران",
        itemCount_few: "{{count, number}} عناصر",
        itemCount_many: "{{count, number}} عنصرًا",
        itemCount_other: "{{count, number}} عنصر",
        status: {
          created: "تم الإنشاء",
          failed: "فشل",
          mixed: "نتائج متنوعة",
          removed: "تمت الإزالة",
          restored: "تمت الاستعادة",
          skipped: "تم التجاوز",
          updated: "تم التحديث",
          upToDate: "محدّث بالفعل",
        },
      },
      startFailed: "تعذر بدء إعداد المشروع. حاول مرة أخرى.",
      statusUnavailable: "حالة المشروع غير متاحة",
      title: "إعداد المشروع مطلوب",
    },
    shortcutGroups: {
      projects: "المشاريع",
    },
  },
  settings: {
    actions: {
      useDarkTheme: "استخدام النسق الداكن",
      useHighContrastTheme: "استخدام نسق عالي التباين",
      useLightTheme: "استخدام النسق الفاتح",
      useSystemTheme: "استخدام نسق النظام",
    },
    groups: {
      appearance: "المظهر",
      graph: "الرسم البياني",
      keybindings: "اختصارات لوحة المفاتيح",
    },
    fields: {
      theme: { label: "النسق", description: "اختر نسق الواجهة." },
      reduceMotion: {
        label: "تقليل الحركة",
        description: "استخدم رسومًا متحركة أقل في الواجهة.",
      },
      activitySectionFolds: {
        label: "أقسام النشاط",
        description: "تذكر أقسام النشاط المفتوحة.",
      },
      language: { label: "اللغة", description: "اختر لغة الواجهة." },
      defaultGranularity: {
        label: "التفصيل الافتراضي",
        description: "اختر مستوى التفاصيل الأولي للرسم البياني.",
      },
      corpus: { label: "محتوى الرسم", description: "اختر المحتوى الذي يظهر في الرسم." },
      timelineDate: {
        label: "تاريخ المخطط الزمني",
        description: "اختر التاريخ الذي يتحكم في المخطط.",
      },
      confidenceFloor: {
        label: "الحد الأدنى ليقين الاتصال",
        description: "أخفِ الاتصالات دون هذا اليقين.",
      },
      labelFilter: {
        label: "تصفية الاسم",
        description: "اعرض العناصر ذات الأسماء المطابقة.",
        placeholder: "تصفية حسب الاسم",
      },
      graphControls: { label: "عناصر تحكم الرسم", description: "خصص التنقل في الرسم." },
      shortcuts: {
        label: "اختصارات لوحة المفاتيح",
        description: "خصص أوامر لوحة المفاتيح.",
      },
    },
    options: {
      system: "النظام",
      light: "فاتح",
      dark: "داكن",
      highContrast: "تباين عالٍ",
      english: "الإنجليزية",
    },
  },
  timeline: {
    accessibility: {
      dateField: "تاريخ المخطط الزمني",
    },
    actions: {
      clearDateRange: "مسح نطاق التاريخ",
      filterByCreationDate: "التصفية حسب تاريخ الإنشاء",
      filterByCreationDateCurrent: "التصفية حسب تاريخ الإنشاء (الحالي)",
      filterByEditDate: "التصفية حسب تاريخ التعديل",
      filterByEditDateCurrent: "التصفية حسب تاريخ التعديل (الحالي)",
      filterByUpdateDate: "التصفية حسب تاريخ التحديث",
      filterByUpdateDateCurrent: "التصفية حسب تاريخ التحديث (الحالي)",
      showLast24Hours: "عرض آخر 24 ساعة",
      showLast7Days: "عرض آخر 7 أيام",
      showLast30Days: "عرض آخر 30 يومًا",
      showLast90Days: "عرض آخر 90 يومًا",
      viewProjectAtVersion: "عرض المشروع بهذا الإصدار",
    },
    criteria: {
      created: "الإنشاء",
      modified: "التعديل",
      stamped: "التحديث",
    },
    descriptions: {
      useCreationDateForRange: "استخدام تاريخ الإنشاء للنطاق",
      useEditDateForRange: "استخدام تاريخ التعديل للنطاق",
      useUpdateDateForRange: "استخدام تاريخ التحديث للنطاق",
    },
    disabledReasons: {
      codeFiles: "اختر تاريخ التعديل. تستخدم ملفات التعليمات البرمجية تواريخ التعديل.",
      chooseProject: "اختر مشروعًا، ثم حاول مرة أخرى.",
      current: "اختر خيار تاريخ آخر لتغيير المخطط الزمني.",
      modifiedUnavailable: "اختر تاريخ الإنشاء. تواريخ التعديل غير متاحة هنا.",
      refreshHistory: "حدّث سجل المشروع، ثم حاول مرة أخرى.",
      stampedUnavailable: "اختر تاريخ الإنشاء. تواريخ التحديث غير متاحة هنا.",
      switchToDocumentsForHistory: "انتقل إلى المستندات لعرض سجل المشروع.",
    },
    labels: {
      timeline: "المخطط الزمني",
    },
  },
} as const;

export const testResources = {
  [sourceLocale]: en,
  [ltrTestLocale]: ltrTestResources,
  [rtlTestLocale]: rtlTestResources,
} as const;

export type TestLocale = keyof typeof testResources;
