export const ltrWorkspaceIdentityResources = {
  accessibility: {
    choose: "Choisir un projet ou un arbre de travail",
    currentLocation: "Emplacement actuel : {{worktree}}",
    currentLocationInProject: "Emplacement actuel : {{worktree}} dans {{project}}",
    currentLocationSwitching: "Emplacement actuel : {{worktree}}. Changement en cours.",
    currentLocationSwitchingInProject:
      "Emplacement actuel : {{worktree}} dans {{project}}. Changement en cours.",
    recentProjects: "Projets récents",
    removeRecent: "Retirer {{worktree}} de l’historique",
    rowActions: "Actions pour {{worktree}}",
    switchProject: "Passer au projet {{project}}",
    switchWorktree: "Passer à l’arbre de travail {{worktree}}",
    switchWorktreeInProject: "Passer à {{worktree}} dans {{project}}",
    switchUnnamedWorktreeInProject: "Passer à un arbre de travail dans {{project}}",
    unavailableProject: "Projet indisponible",
    unavailableWorktree: "Impossible d’ouvrir {{worktree}}",
    worktreeList: "Projets et arbres de travail",
  },
  actions: {
    addProject: "Ajouter un projet…",
    clearHistory: "Effacer l’historique",
    collapseNavigation: "Réduire la navigation",
    openProject: "Ouvrir un projet…",
    removeFromHistory: "Retirer de l’historique",
    retry: "Réessayer",
  },
  counts: {
    ahead_many: "{{count, number}} validations en avance",
    ahead_one: "{{count, number}} validation en avance",
    ahead_other: "{{count, number}} validations en avance",
    behind_many: "{{count, number}} validations en retard",
    behind_one: "{{count, number}} validation en retard",
    behind_other: "{{count, number}} validations en retard",
  },
  descriptions: {
    switchProject: "Choisissez un projet ou un arbre de travail récent.",
  },
  labels: {
    current: "Actuel",
    default: "Par défaut",
    noProjectName: "Projet sans nom",
    noWorktreeName: "Arbre de travail",
    noProjectFiles: "Indisponible",
    switching: "Changement…",
    uncommittedChanges: "Modifications non validées",
    thisProjectWorktrees: "Arbres de travail de ce projet",
    unnamedWorktreeInProject: "Arbre de travail dans {{project}}",
    worktreeInProject: "{{worktree}} dans {{project}}",
    worktreesInProject: "Arbres de travail dans {{project}}",
  },
  sections: { projects: "Projets", recent: "Récents", worktrees: "Arbres de travail" },
  states: {
    degraded:
      "Certains arbres de travail sont indisponibles. Les arbres disponibles sont affichés.",
    loading: "Chargement des arbres de travail…",
    noRecent: "Aucun projet récent. Ouvrez un projet pour commencer.",
    noWorktrees: "Aucun arbre de travail disponible. Ajoutez un projet pour continuer.",
    noWorktreesWithProjectFiles:
      "Ces arbres de travail ne peuvent pas être ouverts. Choisissez un autre projet.",
    onlyWorktree: "C’est le seul arbre de travail disponible.",
    switchFailed: "Impossible de changer d’arbre de travail. Réessayez.",
    worktreesFailed: "Impossible de charger les arbres de travail. Réessayez.",
  },
  titles: { switchProject: "Changer de projet", switchWorkspace: "Changer d’espace" },
} as const;

export const rtlWorkspaceIdentityResources = {
  accessibility: {
    choose: "اختيار مشروع أو شجرة عمل",
    currentLocation: "الموقع الحالي: {{worktree}}",
    currentLocationInProject: "الموقع الحالي: {{worktree}} في {{project}}",
    currentLocationSwitching: "الموقع الحالي: {{worktree}}. جارٍ التبديل.",
    currentLocationSwitchingInProject:
      "الموقع الحالي: {{worktree}} في {{project}}. جارٍ التبديل.",
    recentProjects: "المشاريع الأخيرة",
    removeRecent: "إزالة {{worktree}} من السجل",
    rowActions: "إجراءات {{worktree}}",
    switchProject: "التبديل إلى المشروع {{project}}",
    switchWorktree: "التبديل إلى شجرة العمل {{worktree}}",
    switchWorktreeInProject: "التبديل إلى {{worktree}} في {{project}}",
    switchUnnamedWorktreeInProject: "التبديل إلى شجرة عمل في {{project}}",
    unavailableProject: "المشروع غير متاح",
    unavailableWorktree: "لا يمكن فتح {{worktree}}",
    worktreeList: "المشاريع وأشجار العمل",
  },
  actions: {
    addProject: "إضافة مشروع…",
    clearHistory: "مسح السجل",
    collapseNavigation: "طي التنقل",
    openProject: "فتح مشروع…",
    removeFromHistory: "إزالة من السجل",
    retry: "إعادة المحاولة",
  },
  counts: {
    ahead_few: "متقدم بمقدار {{count, number}} التزامات",
    ahead_many: "متقدم بمقدار {{count, number}} التزامًا",
    ahead_one: "متقدم بمقدار التزام واحد ({{count, number}})",
    ahead_other: "متقدم بمقدار {{count, number}} التزام",
    ahead_two: "متقدم بمقدار التزامين ({{count, number}})",
    ahead_zero: "لا توجد التزامات متقدمة ({{count, number}})",
    behind_few: "متأخر بمقدار {{count, number}} التزامات",
    behind_many: "متأخر بمقدار {{count, number}} التزامًا",
    behind_one: "متأخر بمقدار التزام واحد ({{count, number}})",
    behind_other: "متأخر بمقدار {{count, number}} التزام",
    behind_two: "متأخر بمقدار التزامين ({{count, number}})",
    behind_zero: "لا توجد التزامات متأخرة ({{count, number}})",
  },
  descriptions: { switchProject: "اختر مشروعًا أو شجرة عمل حديثة." },
  labels: {
    current: "الحالي",
    default: "الافتراضي",
    noProjectName: "مشروع بلا اسم",
    noWorktreeName: "شجرة عمل",
    noProjectFiles: "غير متاح",
    switching: "جارٍ التبديل…",
    uncommittedChanges: "تغييرات غير ملتزم بها",
    thisProjectWorktrees: "أشجار عمل هذا المشروع",
    unnamedWorktreeInProject: "شجرة عمل في {{project}}",
    worktreeInProject: "{{worktree}} في {{project}}",
    worktreesInProject: "أشجار العمل في {{project}}",
  },
  sections: { projects: "المشاريع", recent: "الأخيرة", worktrees: "أشجار العمل" },
  states: {
    degraded: "بعض أشجار العمل غير متاحة. تظهر أشجار العمل المتاحة.",
    loading: "جارٍ تحميل أشجار العمل…",
    noRecent: "لا توجد مشاريع حديثة. افتح مشروعًا للبدء.",
    noWorktrees: "لا توجد أشجار عمل متاحة. أضف مشروعًا للمتابعة.",
    noWorktreesWithProjectFiles: "لا يمكن فتح أشجار العمل هذه. اختر مشروعًا آخر.",
    onlyWorktree: "هذه هي شجرة العمل الوحيدة المتاحة.",
    switchFailed: "تعذر تبديل أشجار العمل. حاول مرة أخرى.",
    worktreesFailed: "تعذر تحميل أشجار العمل. حاول مرة أخرى.",
  },
  titles: { switchProject: "تبديل المشروع", switchWorkspace: "تبديل مساحة العمل" },
} as const;
