import type {
  EngineEdge,
  EngineNode,
  GraphSlice,
  TiersBlock,
  WireMetaEdge,
} from "../stores/server/engine";

const tiers: TiersBlock = {
  declared: { available: true },
  structural: { available: true },
  temporal: { available: true },
  semantic: { available: true },
};

const nodes: EngineNode[] = [
  {
    id: "feature:graph-interface",
    kind: "feature",
    title: "Graph interface",
    member_count: 8,
    feature_tags: ["graph-interface"],
    authority_class: "roadmap",
    status_value: "in_flight",
    status_class: "provisional",
  },
  {
    id: "feature:live-contract",
    kind: "feature",
    title: "Live contract",
    member_count: 5,
    feature_tags: ["live-contract"],
    authority_class: "roadmap",
    status_value: "in_flight",
    status_class: "provisional",
  },
  {
    id: "feature:renderer-debug",
    kind: "feature",
    title: "Renderer debug",
    member_count: 7,
    feature_tags: ["renderer-debug"],
    authority_class: "roadmap",
    status_value: "accepted",
    status_class: "affirmed",
  },
  {
    id: "doc:research-graph-interface",
    kind: "document",
    doc_type: "research",
    title: "Graph interface research",
    feature_tags: ["graph-interface", "renderer-debug"],
    authority_class: "substrate",
    dates: { created: "2026-06-17", modified: "2026-06-17" },
    degree_by_tier: { semantic: 3, declared: 1 },
    salience: 0.84,
    embedding: [0.12, 0.63, 0.28, 0.91],
  },
  {
    id: "doc:adr-graph-lab",
    kind: "document",
    doc_type: "adr",
    title: "Graph lab interface ADR",
    feature_tags: ["graph-interface"],
    authority_class: "design",
    status_value: "accepted",
    status_class: "affirmed",
    dates: { created: "2026-06-17", modified: "2026-06-17" },
    degree_by_tier: { declared: 4, structural: 2 },
    salience: 1,
    embedding: [0.19, 0.59, 0.22, 0.88],
  },
  {
    id: "doc:plan-graph-lab",
    kind: "document",
    doc_type: "plan",
    title: "Graph lab rollout plan",
    feature_tags: ["graph-interface", "renderer-debug"],
    authority_class: "roadmap",
    lifecycle: { state: "active", progress: { done: 3, total: 6 } },
    status_value: "L2",
    status_class: "tiered",
    dates: { created: "2026-06-17", modified: "2026-06-17" },
    degree_by_tier: { declared: 5, temporal: 1 },
    salience: 0.93,
    embedding: [0.21, 0.57, 0.24, 0.85],
  },
  {
    id: "doc:exec-debug-panel",
    kind: "document",
    doc_type: "exec",
    title: "Expose debug panel controls",
    feature_tags: ["renderer-debug"],
    authority_class: "evidence",
    lifecycle: { state: "running", progress: { done: 4, total: 9 } },
    dates: { created: "2026-06-17", modified: "2026-06-17" },
    degree_by_tier: { structural: 3, temporal: 2 },
    salience: 0.72,
    embedding: [0.38, 0.51, 0.44, 0.79],
  },
  {
    id: "doc:audit-live-graph",
    kind: "document",
    doc_type: "audit",
    title: "Live graph contract audit",
    feature_tags: ["live-contract"],
    authority_class: "judgment",
    status_value: "medium",
    status_class: "graded",
    dates: { created: "2026-06-17", modified: "2026-06-17" },
    degree_by_tier: { declared: 1, structural: 2, semantic: 2 },
    salience: 0.65,
    embedding: [0.74, 0.22, 0.35, 0.42],
  },
  {
    id: "doc:rule-graph-compute",
    kind: "document",
    doc_type: "rule",
    title: "Graph compute stays CPU",
    feature_tags: ["graph-interface", "live-contract"],
    authority_class: "law",
    status_value: "accepted",
    status_class: "affirmed",
    dates: { created: "2026-06-12", modified: "2026-06-17" },
    degree_by_tier: { declared: 3, structural: 2 },
    salience: 0.81,
    embedding: [0.69, 0.31, 0.4, 0.51],
  },
  {
    id: "doc:index-graph",
    kind: "document",
    doc_type: "index",
    title: "Graph interface index",
    feature_tags: ["graph-interface"],
    authority_class: "manifest",
    dates: { created: "2026-06-17", modified: "2026-06-17" },
    degree_by_tier: { structural: 4 },
    salience: 0.38,
  },
  {
    id: "plan:w01",
    kind: "plan-container",
    title: "W01 graph lab wave",
    feature_tags: ["graph-interface", "renderer-debug"],
    authority_class: "roadmap",
    member_count: 4,
    lifecycle: { state: "active", progress: { done: 2, total: 4 } },
  },
];

const edges: EngineEdge[] = [
  {
    id: "edge:research-grounds-adr",
    src: "doc:research-graph-interface",
    dst: "doc:adr-graph-lab",
    relation: "grounds",
    derivation: "grounds",
    tier: "declared",
    confidence: 1,
    state: "resolved",
  },
  {
    id: "edge:adr-authorizes-plan",
    src: "doc:adr-graph-lab",
    dst: "doc:plan-graph-lab",
    relation: "authorizes",
    derivation: "authorizes",
    tier: "declared",
    confidence: 1,
    state: "resolved",
  },
  {
    id: "edge:plan-generates-exec",
    src: "doc:plan-graph-lab",
    dst: "doc:exec-debug-panel",
    relation: "generated-by",
    derivation: "generated-by",
    tier: "declared",
    confidence: 0.98,
    state: "resolved",
  },
  {
    id: "edge:exec-reviewed-by-audit",
    src: "doc:exec-debug-panel",
    dst: "doc:audit-live-graph",
    relation: "reviews",
    derivation: "reviews",
    tier: "temporal",
    confidence: 0.78,
  },
  {
    id: "edge:rule-binds-adr",
    src: "doc:rule-graph-compute",
    dst: "doc:adr-graph-lab",
    relation: "binds",
    derivation: "binds",
    tier: "declared",
    confidence: 1,
    state: "resolved",
  },
  {
    id: "edge:index-aggregates-plan",
    src: "doc:index-graph",
    dst: "doc:plan-graph-lab",
    relation: "aggregates",
    derivation: "aggregates",
    tier: "structural",
    confidence: 0.88,
    state: "resolved",
  },
  {
    id: "edge:plan-wave",
    src: "doc:plan-graph-lab",
    dst: "plan:w01",
    relation: "contains",
    tier: "structural",
    confidence: 0.92,
    state: "resolved",
  },
  {
    id: "edge:semantic-adr-audit",
    src: "doc:adr-graph-lab",
    dst: "doc:audit-live-graph",
    relation: "similar",
    tier: "semantic",
    confidence: 0.74,
  },
  {
    id: "edge:semantic-rule-audit",
    src: "doc:rule-graph-compute",
    dst: "doc:audit-live-graph",
    relation: "similar",
    tier: "semantic",
    confidence: 0.68,
  },
  {
    id: "edge:feature-graph-plan",
    src: "feature:graph-interface",
    dst: "doc:plan-graph-lab",
    relation: "contains",
    tier: "declared",
    confidence: 1,
  },
  {
    id: "edge:feature-debug-exec",
    src: "feature:renderer-debug",
    dst: "doc:exec-debug-panel",
    relation: "contains",
    tier: "declared",
    confidence: 1,
  },
  {
    id: "edge:feature-contract-audit",
    src: "feature:live-contract",
    dst: "doc:audit-live-graph",
    relation: "contains",
    tier: "declared",
    confidence: 1,
  },
];

const meta_edges: WireMetaEdge[] = [
  {
    src: "feature:graph-interface",
    dst: "feature:renderer-debug",
    src_feature: "graph-interface",
    dst_feature: "renderer-debug",
    count: 3,
    breakdown_by_tier: { declared: 2, structural: 0, temporal: 0, semantic: 1 },
  },
  {
    src: "feature:graph-interface",
    dst: "feature:live-contract",
    src_feature: "graph-interface",
    dst_feature: "live-contract",
    count: 3,
    breakdown_by_tier: { declared: 2, structural: 0, temporal: 0, semantic: 1 },
  },
  {
    src: "feature:renderer-debug",
    dst: "feature:live-contract",
    src_feature: "renderer-debug",
    dst_feature: "live-contract",
    count: 2,
    breakdown_by_tier: { declared: 0, structural: 0, temporal: 1, semantic: 1 },
  },
];

export const graphLabDevSlice: GraphSlice = {
  nodes,
  edges,
  meta_edges,
  tiers,
  lens: "status",
  salience_partial: false,
};
