import { describe, expect, it } from "vitest";

import { en, resources, sourceLocale, type EnglishResources } from "../locales/en";
import {
  isMessageKey,
  isPluralMessageKey,
  MESSAGE_KEYS,
  PHYSICAL_MESSAGE_KEYS,
  PLURAL_MESSAGE_KEYS,
  type MessageKey,
  type PhysicalMessageKey,
} from "../platform/localization/message";
import {
  createLocalizationRuntime,
  localizationNamespaces,
  supportedLocales,
} from "../platform/localization/runtime";
import { createTestLocalizationRuntime, ltrTestLocale, rtlTestLocale } from "./testing";
import { EXPECTED_LANGUAGE_DISPLAY_KEYS } from "./catalogLanguageDisplayKeys";
import { EXPECTED_FILTER_KEYS } from "./catalogFilterKeys";
import { EXPECTED_NODE_INTERIOR_KEYS } from "./catalogNodeInteriorKeys";
import { EXPECTED_HOVER_KEYS } from "./catalogHoverKeys";
import { EXPECTED_THREE_LAB_KEYS } from "./catalogThreeLabKeys";
import { EXPECTED_SEARCH_MAINTENANCE_KEYS } from "./catalogSearchMaintenanceKeys";
import { EXPECTED_SHELL_KEYS } from "./catalogShellKeys";

const EXPECTED_SHIPPED_LOCALES = ["en"] as const;
const EXPECTED_NAMESPACES = [
  "common",
  "documents",
  "errors",
  "features",
  "graph",
  "operations",
  "projects",
  "settings",
  "timeline",
] as const;
const EXPECTED_CATALOG_KEYS = [
  ...EXPECTED_SHELL_KEYS,
  ...EXPECTED_FILTER_KEYS,
  ...EXPECTED_NODE_INTERIOR_KEYS,
  ...EXPECTED_HOVER_KEYS,
  ...EXPECTED_THREE_LAB_KEYS,
  ...EXPECTED_SEARCH_MAINTENANCE_KEYS,
  "common:accessibility.actionsForItem",
  "common:accessibility.actionsMenu",
  "common:accessibility.back",
  "common:accessibility.confirmAction",
  "common:accessibility.recordShortcut",
  "common:accessibility.resizeActivityPanel",
  "common:accessibility.resizeAgentPanel",
  "common:accessibility.resizeNavigationPanel",
  "common:accessibility.resizeTimeline",
  "common:accessibility.resetShortcut",
  "common:accessibility.skipToContent",
  "common:accessibility.switchWorkspace",
  "common:actions.cancel",
  "common:actions.close",
  "common:actions.collapseNavigationPanel",
  "common:actions.copy",
  "common:actions.copyBranchName",
  "common:actions.copyCategoryName",
  "common:actions.copyCommitHash",
  "common:actions.copyCommitMessage",
  "common:actions.copyDocumentName",
  "common:actions.copyFeatureTag",
  "common:actions.copyPath",
  "common:actions.copyPullRequestLink",
  "common:actions.copyPullRequestNumber",
  "common:actions.copyShortCommitHash",
  "common:actions.copySummary",
  "common:actions.copyTitle",
  "common:actions.disableFollowMode",
  "common:actions.enableFollowMode",
  "common:actions.expandNavigationPanel",
  "common:actions.hideActivityPanel",
  "common:actions.hideApprovals",
  "common:actions.hideGraph",
  "common:actions.hideNavigationPanel",
  "common:actions.hideProjectHealth",
  "common:actions.hideSearchStatus",
  "common:actions.hideSystemStatus",
  "common:actions.hideTimeline",
  "common:actions.moveToNextPanel",
  "common:actions.moveToPreviousPanel",
  "common:actions.open",
  "common:actions.openCommandPalette",
  "common:actions.openFilters",
  "common:actions.openInEditor",
  "common:actions.openSettings",
  "common:actions.refreshData",
  "common:actions.reloadPage",
  "common:actions.reset",
  "common:actions.resetLayout",
  "common:actions.retry",
  "common:actions.searchDocumentsAndCode",
  "common:actions.showActivityPanel",
  "common:actions.showApprovals",
  "common:actions.showChanges",
  "common:actions.showGraph",
  "common:actions.showNavigationPanel",
  "common:actions.showOrHideGraph",
  "common:actions.showInFileManager",
  "common:actions.showKeyboardShortcuts",
  "common:actions.showOnCanvas",
  "common:actions.showProjectHealth",
  "common:actions.showSearchStatus",
  "common:actions.showStatus",
  "common:actions.showSystemStatus",
  "common:actions.showTimeline",
  "common:activityTabs.changes",
  "common:activityTabs.status",
  "common:commandFamilies.editing",
  "common:commandFamilies.filters",
  "common:commandFamilies.focus",
  "common:commandFamilies.general",
  "common:commandFamilies.help",
  "common:commandFamilies.layout",
  "common:commandFamilies.navigation",
  "common:commandFamilies.refresh",
  "common:commandFamilies.search",
  "common:commandFamilies.searchMaintenance",
  "common:commandFamilies.settings",
  "common:commandFamilies.workspaceMaintenance",
  "common:commandPalette.dialogLabel",
  "common:commandPalette.inputPlaceholder",
  "common:commandPalette.listboxLabel",
  "common:commandPalette.noMatches",
  "common:commandPalette.loading",
  "common:commandPalette.selectionAnnouncement_one",
  "common:commandPalette.selectionAnnouncement_other",
  "common:commandPalette.footer.navigate",
  "common:commandPalette.footer.open",
  "common:commandPalette.footer.close",
  "common:controlPanels.labels.search",
  "common:controlPanels.labels.projectHealth",
  "common:controlPanels.labels.systemStatus",
  "common:controlPanels.labels.approvals",
  "common:controlPanels.actions.showSearch",
  "common:controlPanels.actions.hideSearch",
  "common:controlPanels.actions.showProjectHealth",
  "common:controlPanels.actions.hideProjectHealth",
  "common:controlPanels.actions.showSystemStatus",
  "common:controlPanels.actions.hideSystemStatus",
  "common:controlPanels.actions.showApprovals",
  "common:controlPanels.actions.hideApprovals",
  "common:controlPanels.unavailableTitles.search",
  "common:controlPanels.unavailableTitles.projectHealth",
  "common:controlPanels.unavailableTitles.systemStatus",
  "common:controlPanels.unavailableTitles.approvals",
  "common:controlPanels.accessibility.group",
  "common:controlPanels.accessibility.panelStatus",
  "common:controlPanels.tones.workingNormally",
  "common:controlPanels.tones.needsAttention",
  "common:controlPanels.tones.unavailable",
  "common:controlPanels.tones.checking",
  "common:agent.sendComment",
  "common:agent.autonomy.label",
  "common:agent.autonomy.reviewEach",
  "common:agent.autonomy.applyAutomatically",
  "common:agent.actions.openPanel",
  "common:agent.actions.closePanel",
  "common:agent.actions.togglePanel",
  "common:agent.actions.stopRun",
  "common:agent.actions.newSession",
  "common:agent.panel.region",
  "common:agent.panel.sessionsMenu",
  "common:agent.panel.newSession",
  "common:agent.panel.recentSessions",
  "common:agent.panel.untitledSession",
  "common:agent.panel.close",
  "common:agent.transcript.loading",
  "common:agent.transcript.empty",
  "common:agent.transcript.noSession",
  "common:agent.transcript.error",
  "common:agent.transcript.showingRecent",
  "common:agent.transcript.toolCalls",
  "common:agent.transcript.thinking",
  "common:agent.transcript.thinkingDuration",
  "common:agent.transcript.toolInput",
  "common:agent.transcript.toolResult",
  "common:agent.transcript.toolStatus.done",
  "common:agent.transcript.toolStatus.needsPermission",
  "common:agent.transcript.toolStatus.allowed",
  "common:agent.transcript.toolStatus.denied",
  "common:agent.transcript.toolStatus.notAllowed",
  "common:agent.transcript.turnStatus.working",
  "common:agent.transcript.turnStatus.stopping",
  "common:agent.transcript.turnStatus.done",
  "common:agent.transcript.turnStatus.stopped",
  "common:agent.transcript.turnStatus.failed",
  "common:agent.transcript.permissionQuestion",
  "common:agent.transcript.allow",
  "common:agent.transcript.deny",
  "common:agent.transcript.permissionFailed",
  "common:agent.composer.placeholder",
  "common:agent.composer.steerPlaceholder",
  "common:agent.composer.send",
  "common:agent.composer.sendFailed",
  "common:agent.composer.attachedContext",
  "common:agent.composer.queuedChip",
  "common:agent.composer.removeQueued",
  "common:agent.composer.mentionPlaceholder",
  "common:agent.composer.mentionAria",
  "common:agent.composer.mentionEmpty",
  "common:agent.composer.removeMention",
  "common:agent.composer.commentBatch_one",
  "common:agent.composer.commentBatch_other",
  "common:agent.composer.removeComments",
  "common:agent.composer.slashAria",
  "common:agent.composer.slashEmpty",
  "common:agent.composer.selectorValue",
  "common:agent.composer.selectorDisabled",
  "common:agent.composer.model",
  "common:agent.composer.modelDefault",
  "common:agent.composer.modelUnavailable",
  "common:agent.composer.team",
  "common:agent.composer.teamDefault",
  "common:agent.composer.teamUnavailable",
  "common:agent.chip.working",
  "common:agent.chip.label",
  "common:agent.chip.status.active",
  "common:agent.chip.status.cancelRequested",
  "common:disabledReasons.actionUnavailable",
  "common:disabledReasons.currentVersionRequired",
  "common:disabledReasons.desktopEditorRequired",
  "common:disabledReasons.desktopFileManagerRequired",
  "common:disabledReasons.itemUnavailableOnCanvas",
  "common:disabledReasons.selectItemToOpen",
  "common:feedback.actionUnavailable",
  "common:feedback.copyFailed",
  "common:feedback.copySucceeded",
  "common:destructiveActions.discardChanges",
  "common:shortcutDialog.description",
  "common:shortcutDialog.title",
  "common:shortcutSettings.conflict",
  "common:shortcutSettings.empty",
  "common:shortcutSettings.recording",
  "common:shortcutGroups.navigation",
  "common:shortcutGroups.general",
  "common:shortcutGroups.graph",
  "common:shortcutGroups.window",
  "common:keycaps.alt",
  "common:keycaps.arrowDown",
  "common:keycaps.arrowLeft",
  "common:keycaps.arrowRight",
  "common:keycaps.arrowUp",
  "common:keycaps.backspace",
  "common:keycaps.control",
  "common:keycaps.delete",
  "common:keycaps.end",
  "common:keycaps.enter",
  "common:keycaps.escape",
  "common:keycaps.home",
  "common:keycaps.insert",
  "common:keycaps.pageDown",
  "common:keycaps.pageUp",
  "common:keycaps.shift",
  "common:keycaps.space",
  "common:keycaps.tab",
  "common:palette.commandCount_one",
  "common:palette.commandCount_other",
  "common:searchPalette.accessibility.dialog",
  "common:searchPalette.accessibility.results",
  "common:searchPalette.accessibility.scope",
  "common:searchPalette.accessibility.selectableResult",
  "common:searchPalette.accessibility.unavailableResult",
  "common:searchPalette.actions.cancel",
  "common:searchPalette.actions.close",
  "common:searchPalette.actions.move",
  "common:searchPalette.actions.open",
  "common:searchPalette.actions.previousNext",
  "common:searchPalette.counts.results_one",
  "common:searchPalette.counts.results_other",
  "common:searchPalette.labels.change",
  "common:searchPalette.labels.code",
  "common:searchPalette.labels.document",
  "common:searchPalette.labels.result",
  "common:searchPalette.labels.untitledResult",
  "common:searchPalette.placeholders.query",
  "common:searchPalette.preview.unavailable",
  "common:searchPalette.scopes.all",
  "common:searchPalette.scopes.code",
  "common:searchPalette.scopes.documents",
  "common:searchPalette.states.degraded",
  "common:searchPalette.states.failed",
  "common:searchPalette.states.idle",
  "common:searchPalette.states.incomplete",
  "common:searchPalette.states.noMatches",
  "common:searchPalette.states.searching",
  "common:statuses.noActionsAvailable",
  "documents:accessibility.addDocumentToFeature",
  "documents:accessibility.browserView",
  "documents:accessibility.decisionAccepted",
  "documents:accessibility.decisionDeprecated",
  "documents:accessibility.decisionProposed",
  "documents:accessibility.decisionRejected",
  "documents:accessibility.decisionSuperseded",
  "documents:accessibility.planComplete",
  "documents:accessibility.planInProgress",
  "documents:accessibility.planNotStarted",
  "documents:accessibility.treeBrowser",
  "documents:accessibility.switchReadingAndEditingShortcut",
  "documents:accessibility.treeOptionsSortedByCreationDate",
  "documents:accessibility.treeOptionsSortedByDocumentCount",
  "documents:accessibility.treeOptionsSortedByEditDate",
  "documents:accessibility.treeOptionsSortedByLatestActivity",
  "documents:accessibility.treeOptionsSortedByLength",
  "documents:accessibility.treeOptionsSortedByName",
  "documents:accessibility.treeOptionsSortedByWorkspaceShare",
  "documents:codeTree.accessibility.browser",
  "documents:codeTree.accessibility.linkedToMap",
  "documents:codeTree.errors.childUnavailable",
  "documents:codeTree.errors.unavailable",
  "documents:codeTree.states.childLoading",
  "documents:codeTree.states.degraded",
  "documents:codeTree.states.empty",
  "documents:codeTree.states.loading",
  "documents:codeTree.states.truncated",
  "documents:codeTree.states.truncatedUnknown",
  "documents:documentSearch.accessibility.dialog",
  "documents:documentSearch.accessibility.results",
  "documents:documentSearch.counts.documents_one",
  "documents:documentSearch.counts.documents_other",
  "documents:documentSearch.placeholders.query",
  "documents:documentSearch.states.idle",
  "documents:documentSearch.states.noMatches",
  "documents:documentSearch.states.searching",
  "documents:documentSearch.states.unavailable",
  "documents:confirmations.discardUnsavedChanges.body",
  "documents:confirmations.discardUnsavedChanges.title",
  "documents:editor.accessibility.formattingToolbar",
  "documents:editor.actions.bold",
  "documents:editor.actions.bulletedList",
  "documents:editor.actions.heading",
  "documents:editor.actions.inlineCode",
  "documents:editor.actions.italic",
  "documents:editor.actions.link",
  "documents:editor.actions.linkToDocument",
  "documents:editor.actions.numberedList",
  "documents:editor.actions.quote",
  "documents:viewer.accessibility.documentMode",
  "documents:viewer.accessibility.documentProperties",
  "documents:viewer.accessibility.featureTag",
  ...EXPECTED_LANGUAGE_DISPLAY_KEYS,
  "documents:viewer.codeViewer.accessibility.contents",
  "documents:viewer.codeViewer.errors.loadFailed",
  "documents:viewer.codeViewer.errors.temporarilyUnavailable",
  "documents:viewer.codeViewer.footer.summary_one",
  "documents:viewer.codeViewer.footer.summary_other",
  "documents:viewer.codeViewer.labels.code",
  "documents:viewer.codeViewer.labels.readOnly",
  "documents:viewer.codeViewer.states.empty",
  "documents:viewer.codeViewer.states.loading",
  "documents:viewer.codeViewer.states.missing",
  "documents:viewer.reader.accessibility.document",
  "documents:viewer.reader.errors.loadFailed",
  "documents:viewer.reader.errors.temporarilyUnavailable",
  "documents:viewer.reader.labels.created",
  "documents:viewer.reader.labels.document",
  "documents:viewer.reader.labels.readOnly",
  "documents:viewer.reader.labels.relatedDocuments",
  "documents:viewer.reader.labels.tags",
  "documents:viewer.reader.labels.updated",
  "documents:viewer.reader.metadata.readTime_one",
  "documents:viewer.reader.metadata.readTime_other",
  "documents:viewer.reader.metadata.readTimeStatus_one",
  "documents:viewer.reader.metadata.readTimeStatus_other",
  "documents:viewer.reader.metadata.createdReadTime_one",
  "documents:viewer.reader.metadata.createdReadTime_other",
  "documents:viewer.reader.metadata.createdReadTimeStatus_one",
  "documents:viewer.reader.metadata.createdReadTimeStatus_other",
  "documents:viewer.reader.metadata.updatedReadTime_one",
  "documents:viewer.reader.metadata.updatedReadTime_other",
  "documents:viewer.reader.metadata.updatedReadTimeStatus_one",
  "documents:viewer.reader.metadata.updatedReadTimeStatus_other",
  "documents:viewer.reader.metadata.createdUpdatedReadTime_one",
  "documents:viewer.reader.metadata.createdUpdatedReadTime_other",
  "documents:viewer.reader.metadata.createdUpdatedReadTimeStatus_one",
  "documents:viewer.reader.metadata.createdUpdatedReadTimeStatus_other",
  "documents:viewer.reader.states.empty",
  "documents:viewer.reader.states.loading",
  "documents:viewer.reader.states.missing",
  "documents:viewer.reader.statuses.accepted",
  "documents:viewer.reader.statuses.active",
  "documents:viewer.reader.statuses.complete",
  "documents:viewer.reader.statuses.deprecated",
  "documents:viewer.reader.statuses.proposed",
  "documents:viewer.reader.statuses.rejected",
  "documents:viewer.reader.statuses.superseded",
  "documents:viewer.reader.statuses.unavailable",
  "documents:viewer.reader.truncation.bytes_one",
  "documents:viewer.reader.truncation.bytes_other",
  "documents:viewer.comments.accessibility.commentsToReview",
  "documents:viewer.comments.accessibility.editComment",
  "documents:viewer.comments.accessibility.newComment",
  "documents:viewer.comments.accessibility.sectionComments",
  "documents:viewer.comments.actions.add",
  "documents:viewer.comments.actions.close",
  "documents:viewer.comments.actions.copyLink",
  "documents:viewer.comments.actions.edit",
  "documents:viewer.comments.actions.open",
  "documents:viewer.comments.actions.reopen",
  "documents:viewer.comments.actions.resolve",
  "documents:viewer.comments.actions.save",
  "documents:viewer.comments.actions.tryAgain",
  "documents:viewer.comments.authorKinds.agent",
  "documents:viewer.comments.authorKinds.human",
  "documents:viewer.comments.authorKinds.system",
  "documents:viewer.comments.authorKinds.toolExecutor",
  "documents:viewer.comments.authorKinds.unknown",
  "documents:viewer.comments.confirmations.delete.body",
  "documents:viewer.comments.confirmations.delete.title",
  "documents:viewer.comments.connectionIssues.ambiguous",
  "documents:viewer.comments.connectionIssues.changed",
  "documents:viewer.comments.connectionIssues.malformed",
  "documents:viewer.comments.connectionIssues.missing",
  "documents:viewer.comments.counts.commentsToReview_one",
  "documents:viewer.comments.counts.commentsToReview_other",
  "documents:viewer.comments.counts.days_one",
  "documents:viewer.comments.counts.days_other",
  "documents:viewer.comments.counts.hours_one",
  "documents:viewer.comments.counts.hours_other",
  "documents:viewer.comments.counts.minutes_one",
  "documents:viewer.comments.counts.minutes_other",
  "documents:viewer.comments.counts.months_one",
  "documents:viewer.comments.counts.months_other",
  "documents:viewer.comments.counts.years_one",
  "documents:viewer.comments.counts.years_other",
  "documents:viewer.comments.descriptions.attachedToSection",
  "documents:viewer.comments.disabledReasons.actorPreparing",
  "documents:viewer.comments.disabledReasons.duplicateHeading",
  "documents:viewer.comments.emptyStates.noComments",
  "documents:viewer.comments.emptyStates.noCommentsToReview",
  "documents:viewer.comments.errors.actorUnavailable",
  "documents:viewer.comments.errors.addFailed",
  "documents:viewer.comments.errors.copyLinkFailed",
  "documents:viewer.comments.errors.deleteFailed",
  "documents:viewer.comments.errors.loadFailed",
  "documents:viewer.comments.errors.moveFailed",
  "documents:viewer.comments.errors.reopenFailed",
  "documents:viewer.comments.errors.resolveFailed",
  "documents:viewer.comments.errors.saveFailed",
  "documents:viewer.comments.feedback.added",
  "documents:viewer.comments.feedback.deleted",
  "documents:viewer.comments.feedback.moved",
  "documents:viewer.comments.feedback.reopened",
  "documents:viewer.comments.feedback.resolved",
  "documents:viewer.comments.feedback.saved",
  "documents:viewer.comments.placeholders.newComment",
  "documents:viewer.comments.states.justNow",
  "documents:viewer.comments.states.loading",
  "documents:viewer.comments.states.preparing",
  "documents:viewer.comments.states.resolved",
  "documents:viewer.modes.edit",
  "documents:viewer.modes.view",
  "documents:viewer.properties.actions.rename",
  "documents:viewer.properties.actions.save",
  "documents:viewer.properties.emptyStates.newFeatureTag",
  "documents:viewer.properties.labels.date",
  "documents:viewer.properties.labels.documentName",
  "documents:viewer.properties.labels.documentType",
  "documents:viewer.properties.labels.feature",
  "documents:viewer.properties.labels.relatedDocuments",
  "documents:viewer.properties.placeholders.date",
  "documents:viewer.properties.placeholders.featureTag",
  "documents:viewer.properties.states.notSet",
  "documents:viewer.properties.states.renaming",
  "documents:viewer.properties.states.saving",
  "documents:actions.addComment",
  "documents:actions.addToFeature",
  "documents:actions.browseDocuments",
  "documents:actions.browseFiles",
  "documents:actions.closeActiveTab",
  "documents:actions.closeAllDocuments",
  "documents:actions.closeDocument",
  "documents:actions.closeOtherDocuments",
  "documents:actions.clearFilter",
  "documents:actions.collapseCategory",
  "documents:actions.collapseTree",
  "documents:actions.copyLink",
  "documents:actions.expandTree",
  "documents:actions.expandCategory",
  "documents:actions.findByName",
  "documents:actions.finishEditing",
  "documents:actions.focusFilter",
  "documents:actions.keepDocumentOpen",
  "documents:actions.keepTabOpen",
  "documents:actions.linkToSelectedDocument",
  "documents:actions.nextTab",
  "documents:actions.openComments",
  "documents:actions.previousTab",
  "documents:actions.resetFilters",
  "documents:actions.resetSorting",
  "documents:actions.reloadDocument",
  "documents:actions.save",
  "documents:actions.sortByCreationDate",
  "documents:actions.sortByDocumentCount",
  "documents:actions.sortByEditDate",
  "documents:actions.sortByLatestActivity",
  "documents:actions.sortByLength",
  "documents:actions.sortByName",
  "documents:actions.sortByWorkspaceShare",
  "documents:actions.showOrHideFilterOptions",
  "documents:actions.filterByDocumentType",
  "documents:actions.showOrHideChanges",
  "documents:actions.switchReadingAndEditing",
  "documents:actions.switchView",
  "documents:browserModes.documents",
  "documents:browserModes.files",
  "documents:categories.code",
  "documents:createDialog.accessibility.addLinkedDocument",
  "documents:createDialog.accessibility.backToFeature",
  "documents:createDialog.accessibility.documentType",
  "documents:createDialog.accessibility.feature",
  "documents:createDialog.accessibility.linkedDocuments",
  "documents:createDialog.accessibility.pipelineCoverage",
  "documents:createDialog.accessibility.removeLinkedDocument",
  "documents:createDialog.accessibility.title",
  "documents:createDialog.actions.back",
  "documents:createDialog.actions.continue",
  "documents:createDialog.actions.create",
  "documents:createDialog.actions.creating",
  "documents:createDialog.descriptions.documentStage",
  "documents:createDialog.descriptions.featureStage",
  "documents:createDialog.documentTypes.adr",
  "documents:createDialog.documentTypes.audit",
  "documents:createDialog.documentTypes.document",
  "documents:createDialog.documentTypes.exec",
  "documents:createDialog.documentTypes.plan",
  "documents:createDialog.documentTypes.reference",
  "documents:createDialog.documentTypes.research",
  "documents:createDialog.emptyStates.createFeatureTag",
  "documents:createDialog.emptyStates.noMatchingDocuments",
  "documents:createDialog.errors.createFailed",
  "documents:createDialog.errors.inFlight",
  "documents:createDialog.errors.pathCollision",
  "documents:createDialog.errors.projectChanged",
  "documents:createDialog.errors.scopeChanged",
  "documents:createDialog.hints.adr",
  "documents:createDialog.hints.audit",
  "documents:createDialog.hints.notAvailable",
  "documents:createDialog.hints.plan",
  "documents:createDialog.hints.reference",
  "documents:createDialog.hints.requiresDecision",
  "documents:createDialog.hints.requiresResearchOrReference",
  "documents:createDialog.hints.research",
  "documents:createDialog.labels.documentType",
  "documents:createDialog.labels.feature",
  "documents:createDialog.labels.inThisFeature",
  "documents:createDialog.labels.linkedDocuments",
  "documents:createDialog.labels.title",
  "documents:createDialog.placeholders.addLinkedDocument",
  "documents:createDialog.placeholders.documentTitle",
  "documents:createDialog.placeholders.featureTag",
  "documents:createDialog.stages.document",
  "documents:createDialog.stages.feature",
  "documents:createDialog.states.checkingCoverage",
  "documents:createDialog.states.chooseFeatureForCoverage",
  "documents:createDialog.states.coverageUnavailable",
  "documents:createDialog.states.emptyFeature",
  "documents:createDialog.states.nextStep",
  "documents:createDialog.states.notYet",
  "documents:createDialog.states.present",
  "documents:createDialog.states.selected",
  "documents:createDialog.titles.document",
  "documents:createDialog.titles.feature",
  "documents:createDialog.validation.chooseAvailableDocumentType",
  "documents:createDialog.validation.chooseDocumentType",
  "documents:createDialog.validation.chooseFeature",
  "documents:createDialog.validation.completeRequiredFields",
  "documents:createDialog.validation.requiresDecision",
  "documents:createDialog.validation.requiresResearchOrReference",
  "documents:documentTypes.adr",
  "documents:documentTypes.audit",
  "documents:documentTypes.exec",
  "documents:documentTypes.plan",
  "documents:documentTypes.reference",
  "documents:documentTypes.research",
  "documents:disabledReasons.chooseTemporaryTab",
  "documents:disabledReasons.copyChangesBeforeReopening",
  "documents:disabledReasons.openAnotherDocument",
  "documents:disabledReasons.openDocument",
  "documents:disabledReasons.openForEditing",
  "documents:disabledReasons.selectDifferentDocument",
  "documents:disabledReasons.selectDocument",
  "documents:disabledReasons.tryAfterSaving",
  "documents:disabledReasons.updateBeforeSaving",
  "documents:feedback.alreadyLinked",
  "documents:feedback.linkConflict",
  "documents:feedback.linkFailed",
  "documents:feedback.linkInProgress",
  "documents:feedback.linkSucceeded",
  "documents:tree.created",
  "documents:tree.decisionStatusAccepted",
  "documents:tree.decisionStatusDeprecated",
  "documents:tree.decisionStatusProposed",
  "documents:tree.decisionStatusRejected",
  "documents:tree.decisionStatusSuperseded",
  "documents:tree.degraded",
  "documents:tree.lastEdited",
  "documents:tree.emptyWorktree",
  "documents:tree.loading",
  "documents:tree.noFilterMatches",
  "documents:tree.noFilterMatchesYet",
  "documents:tree.partialAnnouncement",
  "documents:tree.partialCount_one",
  "documents:tree.partialCount_other",
  "documents:tree.planProgress",
  "documents:tree.sizeSummary_one",
  "documents:tree.sizeSummary_other",
  "documents:tree.unavailable",
  "documents:tree.updated",
  "documents:tree.vaultBrowser",
  "documents:tree.wordCount_one",
  "documents:tree.wordCount_other",
  "documents:tree.weightBelowThreshold",
  "documents:labels.document",
  "documents:labels.vault",
  "documents:reviewStation.accessibility.loadingQueue",
  "documents:reviewStation.actions.hideChanges",
  "documents:reviewStation.actions.showChanges",
  "documents:reviewStation.authorKinds.agent",
  "documents:reviewStation.authorKinds.human",
  "documents:reviewStation.authorKinds.system",
  "documents:reviewStation.authorKinds.toolExecutor",
  "documents:reviewStation.authorKinds.unknown",
  "documents:reviewStation.confirmations.apply.body",
  "documents:reviewStation.confirmations.apply.title",
  "documents:reviewStation.confirmations.approve.body",
  "documents:reviewStation.confirmations.approve.title",
  "documents:reviewStation.confirmations.reject.body",
  "documents:reviewStation.confirmations.reject.title",
  "documents:reviewStation.confirmations.rollback.body",
  "documents:reviewStation.confirmations.rollback.title",
  "documents:reviewStation.counts.acknowledgements_one",
  "documents:reviewStation.counts.acknowledgements_other",
  "documents:reviewStation.counts.changes_one",
  "documents:reviewStation.counts.changes_other",
  "documents:destructiveActions.deleteComment",
  "documents:destructiveActions.reviewStationRejectProposal",
  "documents:reviewStation.disabledReasons.actionInProgress",
  "documents:reviewStation.disabledReasons.actionUnavailable",
  "documents:reviewStation.disabledReasons.rollbackUnavailable",
  "documents:reviewStation.errors.actionFailed",
  "documents:reviewStation.errors.conflict",
  "documents:reviewStation.errors.queueUnavailable",
  "documents:reviewStation.feedback.actionAccepted",
  "documents:reviewStation.feedback.actionNotAllowed",
  "documents:reviewStation.feedback.reviewChanged",
  "documents:reviewStation.feedback.reviewerUnavailable",
  "documents:reviewStation.feedback.rollbackUnavailable",
  "documents:guardedActions.moveCommentToThisSection",
  "documents:guardedActions.reviewStationApplyChanges",
  "documents:guardedActions.reviewStationApproveProposal",
  "documents:guardedActions.reviewStationPrepareRollback",
  "documents:reviewStation.actions.submitForReview",
  "documents:reviewStation.labels.actionUnavailable",
  "documents:reviewStation.policy.assistedHumanApproval",
  "documents:reviewStation.policy.assistedSystemApproval",
  "documents:reviewStation.policy.autonomousHumanApproval",
  "documents:reviewStation.policy.autonomousSystemApproval",
  "documents:reviewStation.policy.manualHumanApproval",
  "documents:reviewStation.policy.manualSystemApproval",
  "documents:reviewStation.policy.unavailable",
  "documents:reviewStation.sections.appliedAutomatically",
  "documents:reviewStation.stale.policyChanged",
  "documents:reviewStation.stale.reviewChanged",
  "documents:reviewStation.states.appliedAutomatically",
  "documents:reviewStation.states.empty",
  "documents:reviewStation.states.informationMayBeOutOfDate",
  "documents:reviewStation.states.loading",
  "documents:reviewStation.states.moreAppliedChanges",
  "documents:reviewStation.states.moreProposals",
  "documents:reviewStation.states.untitledProposal",
  "documents:reviewStation.statuses.applied",
  "documents:reviewStation.statuses.applying",
  "documents:reviewStation.statuses.approved",
  "documents:reviewStation.statuses.cancelled",
  "documents:reviewStation.statuses.compensationRequired",
  "documents:reviewStation.statuses.conflicted",
  "documents:reviewStation.statuses.draft",
  "documents:reviewStation.statuses.failed",
  "documents:reviewStation.statuses.generating",
  "documents:reviewStation.statuses.needsReview",
  "documents:reviewStation.statuses.partiallyApplied",
  "documents:reviewStation.statuses.proposed",
  "documents:reviewStation.statuses.rejected",
  "documents:reviewStation.statuses.rollbackProposed",
  "documents:reviewStation.statuses.superseded",
  "documents:reviewStation.statuses.unknown",
  "documents:reviewStation.validation.invalid",
  "documents:reviewStation.validation.stale",
  "documents:reviewStation.validation.unavailable",
  "documents:reviewStation.validation.valid",
  "documents:reviewStation.validation.validWithWarnings",
  "documents:sortOptions.creationDate",
  "documents:sortOptions.documentCount",
  "documents:sortOptions.editDate",
  "documents:sortOptions.latestActivity",
  "documents:sortOptions.length",
  "documents:sortOptions.name",
  "documents:sortOptions.workspaceShare",
  "documents:shortcutGroups.documents",
  "documents:shortcutGroups.editing",
  "errors:fallback.contentUnavailable",
  "errors:unexpectedApplication.message",
  "errors:unexpectedApplication.title",
  "errors:unexpectedSection.message",
  "errors:unexpectedSection.title",
  "features:actions.collapse",
  "features:actions.expand",
  "features:actions.moveToNextFeature",
  "features:actions.moveToPreviousFeature",
  "features:actions.filterByFeature",
  "features:confirmations.archive.body",
  "features:confirmations.archive.title",
  "features:confirmations.repair.body",
  "features:confirmations.repair.title",
  "features:destructiveActions.archive",
  "features:disabledReasons.selectFeature",
  "features:feedback.archiveRejected",
  "features:feedback.archiveSucceeded",
  "features:feedback.archiveUnavailable",
  "features:feedback.repairRejected",
  "features:feedback.repairSucceeded",
  "features:feedback.repairUnavailable",
  "features:guardedActions.repair",
  "features:labels.feature",
  "graph:accessibility.selectedItem",
  "graph:accessibility.selectedItemGeneric",
  "graph:accessibility.workingSet",
  "graph:accessibility.workingSetCount_one",
  "graph:accessibility.workingSetCount_other",
  "graph:accessibility.hiddenByActiveFilter",
  "graph:accessibility.namedWorkingSetItemHidden",
  "graph:accessibility.workingSetItemHidden",
  "graph:actions.addItemToWorkingSet",
  "graph:actions.addSelectedItemToWorkingSet",
  "graph:actions.clearSelection",
  "graph:actions.clearWorkingSet",
  "graph:actions.expandFocusedItem",
  "graph:actions.fitToView",
  "graph:actions.keepInView",
  "graph:actions.moveToNextConnectedItem",
  "graph:actions.moveToPreviousConnectedItem",
  "graph:actions.openFocusedItem",
  "graph:actions.pauseMovement",
  "graph:actions.pinItem",
  "graph:actions.rearrangeAfterFiltering",
  "graph:actions.resetSettings",
  "graph:actions.resetView",
  "graph:actions.removeItemFromWorkingSet",
  "graph:actions.removeNamedItemFromWorkingSet",
  "graph:actions.removeLastItemFromWorkingSet",
  "graph:actions.resumeMovement",
  "graph:actions.showRelatedItem",
  "graph:actions.showStartingItem",
  "graph:actions.unpinItem",
  "graph:actions.zoomIn",
  "graph:actions.zoomOut",
  "graph:canvas.emptyStates.noFilterMatches",
  "graph:canvas.errors.graphicsMessage",
  "graph:canvas.errors.graphicsTitle",
  "graph:canvas.errors.partialUnavailable",
  "graph:canvas.errors.unavailable",
  "graph:canvas.states.loading",
  "graph:canvas.states.loadingDetails",
  "graph:canvas.states.loadingDocumentLinks",
  "graph:canvas.states.refreshing",
  "graph:canvas.states.refreshingDocumentLinks",
  "graph:canvas.states.restoring",
  "graph:canvas.states.truncated",
  "graph:controls.accessibility.edgeColorMode",
  "graph:controls.accessibility.navigation",
  "graph:controls.accessibility.nodeColorMode",
  "graph:controls.accessibility.nodeLevel",
  "graph:controls.accessibility.showNodeIcons",
  "graph:controls.descriptions.charge",
  "graph:controls.descriptions.documentLevel",
  "graph:controls.descriptions.edgeColorMode",
  "graph:controls.descriptions.edgeOpacityMax",
  "graph:controls.descriptions.edgeWidthMax",
  "graph:controls.descriptions.featureLevel",
  "graph:controls.descriptions.granularity",
  "graph:controls.descriptions.keepInView",
  "graph:controls.descriptions.keepLayoutFixed",
  "graph:controls.descriptions.linkDistance",
  "graph:controls.descriptions.linkStrength",
  "graph:controls.descriptions.nodeColorMode",
  "graph:controls.descriptions.nodeIcons",
  "graph:controls.descriptions.nodeSalienceScale",
  "graph:controls.descriptions.nodeSizeScale",
  "graph:controls.descriptions.rearrangeAfterFiltering",
  "graph:controls.descriptions.settingUnavailableInHistory",
  "graph:controls.labels.charge",
  "graph:controls.labels.edgeColorMode",
  "graph:controls.labels.edgeOpacityMax",
  "graph:controls.labels.edgeWidthMax",
  "graph:controls.labels.keepLayoutFixed",
  "graph:controls.labels.linkDistance",
  "graph:controls.labels.linkStrength",
  "graph:controls.labels.nodeColorMode",
  "graph:controls.labels.nodeIcons",
  "graph:controls.labels.nodeSalienceScale",
  "graph:controls.labels.nodeSizeScale",
  "graph:controls.options.blended",
  "graph:controls.options.category",
  "graph:controls.options.documents",
  "graph:controls.options.features",
  "graph:controls.options.recency",
  "graph:controls.options.solid",
  "graph:controls.sections.appearance",
  "graph:controls.sections.layout",
  "graph:controls.sections.show",
  "graph:controls.title",
  "graph:disabledReasons.chooseConnectionWithSummary",
  "graph:disabledReasons.chooseItemWithTitle",
  "graph:disabledReasons.relatedItemUnavailable",
  "graph:disabledReasons.startingItemUnavailable",
  "graph:legend.accessibility.documentTypeFilters",
  "graph:legend.accessibility.moduleColors",
  "graph:legend.accessibility.recencyScale",
  "graph:legend.actions.addDocumentTypeFilter",
  "graph:legend.actions.clearDocumentTypeFilters",
  "graph:legend.actions.hideDocumentTypeLabels",
  "graph:legend.actions.hideModuleLabels",
  "graph:legend.actions.removeDocumentTypeFilter",
  "graph:legend.actions.showDocumentTypeLabels",
  "graph:legend.actions.showModuleLabels",
  "graph:legend.labels.older",
  "graph:legend.labels.recent",
  "graph:shortcutGroups.workingSet",
  "graph:labels.item",
  "operations:actions.applySearchSettings",
  "operations:actions.checkWorkspace",
  "operations:actions.disableSearch",
  "operations:actions.enableSearch",
  "operations:actions.refreshSearch",
  "operations:actions.showWorkspaceDetails",
  "operations:feedback.applySearchSettings.failed",
  "operations:feedback.applySearchSettings.running",
  "operations:feedback.applySearchSettings.succeeded",
  "operations:feedback.applySearchSettings.unavailable",
  "operations:feedback.checkWorkspace.failed",
  "operations:feedback.checkWorkspace.running",
  "operations:feedback.checkWorkspace.succeeded",
  "operations:feedback.disableSearch.failed",
  "operations:feedback.disableSearch.running",
  "operations:feedback.disableSearch.succeeded",
  "operations:feedback.enableSearch.failed",
  "operations:feedback.enableSearch.running",
  "operations:feedback.enableSearch.succeeded",
  "operations:feedback.enableSearch.unavailable",
  "operations:feedback.refreshSearch.failed",
  "operations:feedback.refreshSearch.running",
  "operations:feedback.refreshSearch.succeeded",
  "operations:feedback.refreshSearch.unavailable",
  "operations:feedback.showWorkspaceDetails.failed",
  "operations:feedback.showWorkspaceDetails.running",
  "operations:feedback.showWorkspaceDetails.succeeded",
  "projects:actions.add",
  "projects:actions.checkProjectStatus",
  "projects:actions.clearHistory",
  "projects:actions.openPullRequest",
  "projects:actions.prepareProjectTools",
  "projects:actions.setUpProject",
  "projects:actions.switch",
  "projects:actions.switchWorktree",
  "projects:actions.updateProject",
  "projects:actions.updateProjectTools",
  "projects:addDialog.accessibility.folderPath",
  "projects:addDialog.actions.add",
  "projects:addDialog.actions.adding",
  "projects:addDialog.actions.pickFolder",
  "projects:addDialog.description",
  "projects:addDialog.errors.addFailed",
  "projects:addDialog.errors.alreadyAdded",
  "projects:addDialog.errors.folderUnavailable",
  "projects:addDialog.errors.notGitProject",
  "projects:addDialog.errors.pathRequired",
  "projects:addDialog.fields.folder",
  "projects:addDialog.placeholders.folderPath",
  "projects:addDialog.title",
  "projects:confirmations.replaceSetup.body",
  "projects:confirmations.replaceSetup.title",
  "projects:destructiveActions.replaceSetup",
  "projects:disabledReasons.chooseWorktreeWithProjectFiles",
  "projects:disabledReasons.installRequiredProjectTools",
  "projects:disabledReasons.noSetupChangesNeeded",
  "projects:disabledReasons.prepareFolderAsGitProject",
  "projects:disabledReasons.refreshProjectForPullRequest",
  "projects:disabledReasons.setUpProjectFirst",
  "projects:disabledReasons.waitForProjectStatus",
  "projects:folderBrowser.accessibility.filterFolders",
  "projects:folderBrowser.accessibility.folderOptionGitRepository",
  "projects:folderBrowser.accessibility.folderOptionHidden",
  "projects:folderBrowser.accessibility.folderOptionProject",
  "projects:folderBrowser.accessibility.folderOptionRegistered",
  "projects:folderBrowser.accessibility.folders",
  "projects:folderBrowser.accessibility.showHiddenFolders",
  "projects:folderBrowser.badges.alreadyAdded",
  "projects:folderBrowser.badges.gitRepository",
  "projects:folderBrowser.badges.hidden",
  "projects:folderBrowser.badges.project",
  "projects:folderBrowser.empty.noMatches",
  "projects:folderBrowser.empty.noSubfolders",
  "projects:folderBrowser.errors.readFailed",
  "projects:folderBrowser.errors.readFailedHint",
  "projects:folderBrowser.labels.filterFolders",
  "projects:folderBrowser.labels.hidden",
  "projects:folderBrowser.labels.roots",
  "projects:folderBrowser.states.loading",
  "projects:folderBrowser.states.truncated",
  "projects:placesRail.labels.home",
  "projects:placesRail.labels.places",
  "projects:placesRail.sections.drives",
  "projects:placesRail.sections.projects",
  "projects:placesRail.sections.recent",
  "projects:provisioning.description",
  "projects:provisioning.details.installRequiredProjectTools",
  "projects:provisioning.details.prepareFolderAsGitProject",
  "projects:provisioning.progress",
  "projects:provisioning.result.completed",
  "projects:provisioning.result.failed",
  "projects:provisioning.result.indeterminate",
  "projects:provisioning.result.itemCount_one",
  "projects:provisioning.result.itemCount_other",
  "projects:provisioning.result.status.created",
  "projects:provisioning.result.status.failed",
  "projects:provisioning.result.status.mixed",
  "projects:provisioning.result.status.removed",
  "projects:provisioning.result.status.restored",
  "projects:provisioning.result.status.skipped",
  "projects:provisioning.result.status.updated",
  "projects:provisioning.result.status.upToDate",
  "projects:provisioning.startFailed",
  "projects:provisioning.statusUnavailable",
  "projects:provisioning.title",
  "projects:shortcutGroups.projects",
  "projects:workspaceIdentity.accessibility.choose",
  "projects:workspaceIdentity.accessibility.currentLocation",
  "projects:workspaceIdentity.accessibility.currentLocationInProject",
  "projects:workspaceIdentity.accessibility.currentLocationSwitching",
  "projects:workspaceIdentity.accessibility.currentLocationSwitchingInProject",
  "projects:workspaceIdentity.accessibility.recentProjects",
  "projects:workspaceIdentity.accessibility.removeRecent",
  "projects:workspaceIdentity.accessibility.rowActions",
  "projects:workspaceIdentity.accessibility.switchProject",
  "projects:workspaceIdentity.accessibility.switchUnnamedWorktreeInProject",
  "projects:workspaceIdentity.accessibility.switchWorktree",
  "projects:workspaceIdentity.accessibility.switchWorktreeInProject",
  "projects:workspaceIdentity.accessibility.unavailableProject",
  "projects:workspaceIdentity.accessibility.unavailableWorktree",
  "projects:workspaceIdentity.accessibility.worktreeList",
  "projects:workspaceIdentity.actions.addProject",
  "projects:workspaceIdentity.actions.clearHistory",
  "projects:workspaceIdentity.actions.collapseNavigation",
  "projects:workspaceIdentity.actions.openProject",
  "projects:workspaceIdentity.actions.removeFromHistory",
  "projects:workspaceIdentity.actions.retry",
  "projects:workspaceIdentity.counts.ahead_one",
  "projects:workspaceIdentity.counts.ahead_other",
  "projects:workspaceIdentity.counts.behind_one",
  "projects:workspaceIdentity.counts.behind_other",
  "projects:workspaceIdentity.descriptions.switchProject",
  "projects:workspaceIdentity.labels.current",
  "projects:workspaceIdentity.labels.default",
  "projects:workspaceIdentity.labels.noProjectFiles",
  "projects:workspaceIdentity.labels.noProjectName",
  "projects:workspaceIdentity.labels.noWorktreeName",
  "projects:workspaceIdentity.labels.switching",
  "projects:workspaceIdentity.labels.thisProjectWorktrees",
  "projects:workspaceIdentity.labels.uncommittedChanges",
  "projects:workspaceIdentity.labels.unnamedWorktreeInProject",
  "projects:workspaceIdentity.labels.worktreeInProject",
  "projects:workspaceIdentity.labels.worktreesInProject",
  "projects:workspaceIdentity.sections.projects",
  "projects:workspaceIdentity.sections.recent",
  "projects:workspaceIdentity.sections.worktrees",
  "projects:workspaceIdentity.states.degraded",
  "projects:workspaceIdentity.states.loading",
  "projects:workspaceIdentity.states.noRecent",
  "projects:workspaceIdentity.states.noWorktrees",
  "projects:workspaceIdentity.states.noWorktreesWithProjectFiles",
  "projects:workspaceIdentity.states.onlyWorktree",
  "projects:workspaceIdentity.states.switchFailed",
  "projects:workspaceIdentity.states.worktreesFailed",
  "projects:workspaceIdentity.titles.switchProject",
  "projects:workspaceIdentity.titles.switchWorkspace",
  "settings:actions.useDarkTheme",
  "settings:actions.useHighContrastTheme",
  "settings:actions.useLightTheme",
  "settings:actions.useSystemTheme",
  "settings:fields.activitySectionFolds.description",
  "settings:fields.activitySectionFolds.label",
  "settings:fields.confidenceFloor.description",
  "settings:fields.confidenceFloor.label",
  "settings:fields.corpus.description",
  "settings:fields.corpus.label",
  "settings:fields.defaultGranularity.description",
  "settings:fields.defaultGranularity.label",
  "settings:fields.graphControls.description",
  "settings:fields.graphControls.label",
  "settings:fields.labelFilter.description",
  "settings:fields.labelFilter.label",
  "settings:fields.labelFilter.placeholder",
  "settings:fields.language.description",
  "settings:fields.language.label",
  "settings:fields.reduceMotion.description",
  "settings:fields.reduceMotion.label",
  "settings:fields.shortcuts.description",
  "settings:fields.shortcuts.label",
  "settings:fields.theme.description",
  "settings:fields.theme.label",
  "settings:fields.timelineDate.description",
  "settings:fields.timelineDate.label",
  "settings:groups.appearance",
  "settings:groups.graph",
  "settings:groups.keybindings",
  "settings:options.dark",
  "settings:options.english",
  "settings:options.highContrast",
  "settings:options.light",
  "settings:options.system",
  "timeline:accessibility.dateField",
  "timeline:accessibility.loadingRange",
  "timeline:accessibility.rangeEnd",
  "timeline:accessibility.rangeStart",
  "timeline:accessibility.selectedRange",
  "timeline:actions.clearDateRange",
  "timeline:actions.filterByCreationDate",
  "timeline:actions.filterByCreationDateCurrent",
  "timeline:actions.filterByEditDate",
  "timeline:actions.filterByEditDateCurrent",
  "timeline:actions.filterByUpdateDate",
  "timeline:actions.filterByUpdateDateCurrent",
  "timeline:actions.showLast24Hours",
  "timeline:actions.showLast7Days",
  "timeline:actions.showLast30Days",
  "timeline:actions.showLast90Days",
  "timeline:actions.viewProjectAtVersion",
  "timeline:criteria.created",
  "timeline:criteria.modified",
  "timeline:criteria.stamped",
  "timeline:descriptions.useCreationDateForRange",
  "timeline:descriptions.useEditDateForRange",
  "timeline:descriptions.useUpdateDateForRange",
  "timeline:disabledReasons.codeFiles",
  "timeline:disabledReasons.chooseProject",
  "timeline:disabledReasons.current",
  "timeline:disabledReasons.modifiedUnavailable",
  "timeline:disabledReasons.refreshHistory",
  "timeline:disabledReasons.stampedUnavailable",
  "timeline:disabledReasons.switchToDocumentsForHistory",
  "timeline:labels.timeline",
  "timeline:states.noDatedDocuments",
  "timeline:states.noDatedFiles",
  "timeline:states.rangeUnavailable",
  "timeline:summaries.selectedRange",
] as const satisfies readonly PhysicalMessageKey[];

const EXPECTED_PUBLIC_MESSAGE_KEYS = [
  ...EXPECTED_CATALOG_KEYS.filter(
    (key) =>
      !/^common:kit\.activity\.rowsLoaded_(?:one|other)$/u.test(key) &&
      !/^common:finalWave\.work\.progress_(?:one|other)$/u.test(key) &&
      !/^common:agent\.composer\.commentBatch_(?:one|other)$/u.test(key) &&
      !/^documents:localizationWave\.plan\.(?:completion|phaseCount|stepCount|waveCount)_(?:one|other)$/u.test(
        key,
      ) &&
      !/^operations:searchMaintenance\.(?:jobs\.(?:count|partial)|projects\.(?:live|partial|summary))_(?:zero|one|two|few|many|other)$/u.test(
        key,
      ) &&
      !/^(?:common:(?:palette\.commandCount|commandPalette\.selectionAnnouncement|searchPalette\.counts\.results)|documents:(?:documentSearch\.counts\.documents|reviewStation\.counts\.(?:acknowledgements|changes)|tree\.(?:partialCount|sizeSummary|wordCount)|viewer\.(?:codeViewer\.footer\.summary|comments\.counts\.(?:commentsToReview|days|hours|minutes|months|years)|reader\.(?:metadata\.(?:readTime|readTimeStatus|createdReadTime|createdReadTimeStatus|updatedReadTime|updatedReadTimeStatus|createdUpdatedReadTime|createdUpdatedReadTimeStatus)|truncation\.bytes)))|graph:(?:accessibility\.workingSetCount|hover\.evidence\.(?:codeLocations|commits|documents)|islands\.progress\.stepsComplete|lab\.actions\.loadGenerated)|projects:(?:provisioning\.result\.itemCount|workspaceIdentity\.counts\.(?:ahead|behind)))_(?:one|other)$/u.test(
        key,
      ),
  ),
  "common:agent.composer.commentBatch",
  "common:commandPalette.selectionAnnouncement",
  "common:finalWave.work.progress",
  "common:kit.activity.rowsLoaded",
  "documents:localizationWave.plan.completion",
  "documents:localizationWave.plan.phaseCount",
  "documents:localizationWave.plan.stepCount",
  "documents:localizationWave.plan.waveCount",
  "common:palette.commandCount",
  "common:searchPalette.counts.results",
  "operations:searchMaintenance.jobs.count",
  "operations:searchMaintenance.jobs.partial",
  "operations:searchMaintenance.projects.live",
  "operations:searchMaintenance.projects.partial",
  "operations:searchMaintenance.projects.summary",
  "documents:documentSearch.counts.documents",
  "documents:reviewStation.counts.acknowledgements",
  "documents:reviewStation.counts.changes",
  "documents:viewer.codeViewer.footer.summary",
  "documents:viewer.reader.metadata.readTime",
  "documents:viewer.reader.metadata.readTimeStatus",
  "documents:viewer.reader.metadata.createdReadTime",
  "documents:viewer.reader.metadata.createdReadTimeStatus",
  "documents:viewer.reader.metadata.updatedReadTime",
  "documents:viewer.reader.metadata.updatedReadTimeStatus",
  "documents:viewer.reader.metadata.createdUpdatedReadTime",
  "documents:viewer.reader.metadata.createdUpdatedReadTimeStatus",
  "documents:viewer.reader.truncation.bytes",
  "documents:viewer.comments.counts.commentsToReview",
  "documents:viewer.comments.counts.days",
  "documents:viewer.comments.counts.hours",
  "documents:viewer.comments.counts.minutes",
  "documents:viewer.comments.counts.months",
  "documents:viewer.comments.counts.years",
  "documents:tree.partialCount",
  "documents:tree.sizeSummary",
  "documents:tree.wordCount",
  "graph:accessibility.workingSetCount",
  "graph:islands.progress.stepsComplete",
  "graph:hover.evidence.codeLocations",
  "graph:hover.evidence.commits",
  "graph:hover.evidence.documents",
  "graph:lab.actions.loadGenerated",
  "projects:workspaceIdentity.counts.ahead",
  "projects:workspaceIdentity.counts.behind",
  "projects:provisioning.result.itemCount",
] as readonly MessageKey[];

function splitMessageKey(key: PhysicalMessageKey): {
  namespace: keyof EnglishResources & string;
  path: string;
} {
  const separator = key.indexOf(":");
  return {
    namespace: key.slice(0, separator) as keyof EnglishResources & string,
    path: key.slice(separator + 1),
  };
}

function discoverLeafKeys(catalog: Readonly<Record<string, unknown>>): string[] {
  const keys: string[] = [];

  const visit = (value: unknown, path: string): void => {
    if (typeof value === "string") {
      keys.push(path);
      return;
    }
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
      keys.push(`${path}:invalid-leaf`);
      return;
    }
    for (const [segment, child] of Object.entries(value)) {
      visit(child, path.length === 0 ? segment : `${path}.${segment}`);
    }
  };

  for (const [namespace, bundle] of Object.entries(catalog)) {
    if (bundle === null || typeof bundle !== "object" || Array.isArray(bundle)) {
      keys.push(`${namespace}:invalid-bundle`);
      continue;
    }
    for (const [segment, child] of Object.entries(bundle)) {
      visit(child, `${namespace}:${segment}`);
    }
  }
  return keys.sort();
}

describe("shipped localization catalog keys", () => {
  it("matches the explicit namespace-qualified leaf-key contract", () => {
    expect([...PHYSICAL_MESSAGE_KEYS].sort()).toEqual(
      [...EXPECTED_CATALOG_KEYS].sort(),
    );
    expect([...MESSAGE_KEYS].sort()).toEqual([...EXPECTED_PUBLIC_MESSAGE_KEYS].sort());
    expect(PLURAL_MESSAGE_KEYS).toEqual([
      "common:kit.activity.rowsLoaded",
      "common:commandPalette.selectionAnnouncement",
      "common:searchPalette.counts.results",
      "common:agent.composer.commentBatch",
      "common:palette.commandCount",
      "common:finalWave.work.progress",
      "documents:localizationWave.plan.completion",
      "documents:localizationWave.plan.phaseCount",
      "documents:localizationWave.plan.stepCount",
      "documents:localizationWave.plan.waveCount",
      "documents:documentSearch.counts.documents",
      "documents:reviewStation.counts.acknowledgements",
      "documents:reviewStation.counts.changes",
      "documents:viewer.codeViewer.footer.summary",
      "documents:viewer.reader.metadata.readTime",
      "documents:viewer.reader.metadata.readTimeStatus",
      "documents:viewer.reader.metadata.createdReadTime",
      "documents:viewer.reader.metadata.createdReadTimeStatus",
      "documents:viewer.reader.metadata.updatedReadTime",
      "documents:viewer.reader.metadata.updatedReadTimeStatus",
      "documents:viewer.reader.metadata.createdUpdatedReadTime",
      "documents:viewer.reader.metadata.createdUpdatedReadTimeStatus",
      "documents:viewer.reader.truncation.bytes",
      "documents:viewer.comments.counts.commentsToReview",
      "documents:viewer.comments.counts.days",
      "documents:viewer.comments.counts.hours",
      "documents:viewer.comments.counts.minutes",
      "documents:viewer.comments.counts.months",
      "documents:viewer.comments.counts.years",
      "documents:tree.partialCount",
      "documents:tree.sizeSummary",
      "documents:tree.wordCount",
      "graph:accessibility.workingSetCount",
      "graph:islands.progress.stepsComplete",
      "graph:hover.evidence.codeLocations",
      "graph:hover.evidence.commits",
      "graph:hover.evidence.documents",
      "graph:lab.actions.loadGenerated",
      "operations:searchMaintenance.jobs.count",
      "operations:searchMaintenance.jobs.partial",
      "operations:searchMaintenance.projects.live",
      "operations:searchMaintenance.projects.summary",
      "operations:searchMaintenance.projects.partial",
      "projects:workspaceIdentity.counts.ahead",
      "projects:workspaceIdentity.counts.behind",
      "projects:provisioning.result.itemCount",
    ]);
    expect(isPluralMessageKey("common:palette.commandCount")).toBe(true);
    expect(isPluralMessageKey("projects:provisioning.result.itemCount")).toBe(true);
    expect(isMessageKey("common:palette.commandCount_one")).toBe(false);
    for (const key of EXPECTED_PUBLIC_MESSAGE_KEYS) {
      expect(isMessageKey(key), key).toBe(true);
    }

    for (const [locale, catalog] of Object.entries(resources)) {
      expect(discoverLeafKeys(catalog), locale).toEqual(
        [...EXPECTED_CATALOG_KEYS].sort(),
      );
    }
  });

  it("keeps shipped locale and namespace aggregates aligned with the source catalog", () => {
    expect(resources[sourceLocale]).toBe(en);
    expect([...supportedLocales].sort()).toEqual([...EXPECTED_SHIPPED_LOCALES].sort());
    expect(Object.keys(resources).sort()).toEqual([...EXPECTED_SHIPPED_LOCALES].sort());
    expect([...localizationNamespaces].sort()).toEqual([...EXPECTED_NAMESPACES].sort());
    expect(Object.keys(en).sort()).toEqual([...EXPECTED_NAMESPACES].sort());

    for (const [locale, catalog] of Object.entries(resources)) {
      expect(Object.keys(catalog).sort(), locale).toEqual(
        [...EXPECTED_NAMESPACES].sort(),
      );
    }
  });

  it("provides every required message directly in every shipped locale", () => {
    const runtime = createLocalizationRuntime();

    for (const locale of supportedLocales) {
      for (const key of EXPECTED_CATALOG_KEYS) {
        const { namespace, path } = splitMessageKey(key);
        const value = runtime.getResource(locale, namespace, path);
        expect(typeof value, `${locale}:${key}`).toBe("string");
        expect((value as string).trim().length, `${locale}:${key}`).toBeGreaterThan(0);
      }
    }
  });

  it("initializes the source locale from the exported source catalog", () => {
    const runtime = createLocalizationRuntime();

    for (const namespace of localizationNamespaces) {
      expect(runtime.getResourceBundle(sourceLocale, namespace)).toEqual(en[namespace]);
    }
  });

  it("resolves shell presentation vocabulary in English, French, and Arabic", () => {
    const keys = [
      "common:activityTabs.status",
      "common:activityTabs.changes",
      "common:actions.showStatus",
      "common:actions.showChanges",
      "common:actions.showActivityPanel",
      "common:actions.hideActivityPanel",
      "common:accessibility.resizeNavigationPanel",
      "common:accessibility.resizeActivityPanel",
      "common:accessibility.resizeTimeline",
      "common:accessibility.skipToContent",
      "common:accessibility.back",
      "documents:actions.resetSorting",
      "documents:labels.vault",
      "timeline:labels.timeline",
    ] as const satisfies readonly MessageKey[];
    const englishRuntime = createTestLocalizationRuntime(sourceLocale);
    const frenchRuntime = createTestLocalizationRuntime(ltrTestLocale);
    const arabicRuntime = createTestLocalizationRuntime(rtlTestLocale);

    for (const key of keys) {
      const english = englishRuntime.t(key);
      const french = frenchRuntime.t(key);
      const arabic = arabicRuntime.t(key);
      expect(french, key).not.toBe(english);
      expect(arabic, key).not.toBe(english);
      expect(arabic, key).not.toBe(french);
    }
  });

  it("resolves timeline date vocabulary in English, French, and Arabic", () => {
    const keys = EXPECTED_CATALOG_KEYS.filter((key) => key.startsWith("timeline:"));
    const englishRuntime = createTestLocalizationRuntime(sourceLocale);
    const frenchRuntime = createTestLocalizationRuntime(ltrTestLocale);
    const arabicRuntime = createTestLocalizationRuntime(rtlTestLocale);

    for (const key of keys) {
      const english = englishRuntime.t(key);
      const french = frenchRuntime.t(key);
      const arabic = arabicRuntime.t(key);
      expect(french, key).not.toBe(english);
      expect(arabic, key).not.toBe(english);
      expect(arabic, key).not.toBe(french);
    }
  });

  it("resolves menu filters and canvas recovery copy in English, French, and Arabic", () => {
    const english = createTestLocalizationRuntime(sourceLocale);
    const french = createTestLocalizationRuntime(ltrTestLocale);
    const arabic = createTestLocalizationRuntime(rtlTestLocale);

    expect(english.t("documents:actions.filterByDocumentType")).toBe(
      "Filter by this document type",
    );
    expect(french.t("documents:actions.filterByDocumentType")).toBe(
      "Filtrer par ce type de document",
    );
    expect(arabic.t("documents:actions.filterByDocumentType")).toBe(
      "التصفية حسب نوع المستند هذا",
    );
    expect(english.t("documents:actions.expandCategory")).toBe("Expand category");
    expect(french.t("documents:actions.expandCategory")).toBe(
      "Développer la catégorie",
    );
    expect(arabic.t("documents:actions.expandCategory")).toBe("توسيع الفئة");
    expect(english.t("documents:actions.collapseCategory")).toBe("Collapse category");
    expect(french.t("documents:actions.collapseCategory")).toBe("Réduire la catégorie");
    expect(arabic.t("documents:actions.collapseCategory")).toBe("طي الفئة");
    expect(english.t("features:actions.filterByFeature")).toBe(
      "Filter by this feature",
    );
    expect(french.t("features:actions.filterByFeature")).toBe(
      "Filtrer par cette fonctionnalité",
    );
    expect(arabic.t("features:actions.filterByFeature")).toBe("التصفية حسب هذه الميزة");
    expect(english.t("common:disabledReasons.itemUnavailableOnCanvas")).toBe(
      "Refresh data, then try showing this item on the canvas.",
    );
    expect(french.t("common:disabledReasons.itemUnavailableOnCanvas")).toBe(
      "Actualisez les données, puis réessayez d’afficher cet élément sur le canevas.",
    );
    expect(arabic.t("common:disabledReasons.itemUnavailableOnCanvas")).toBe(
      "حدّث البيانات، ثم حاول إظهار هذا العنصر على اللوحة.",
    );
  });

  it("resolves create-document dialog copy and linked-document interpolation in each language", () => {
    const keys = [
      "documents:createDialog.accessibility.backToFeature",
      "documents:createDialog.actions.create",
      "documents:createDialog.descriptions.featureStage",
      "documents:createDialog.documentTypes.adr",
      "documents:createDialog.emptyStates.createFeatureTag",
      "documents:createDialog.errors.pathCollision",
      "documents:createDialog.hints.reference",
      "documents:createDialog.labels.feature",
      "documents:createDialog.placeholders.documentTitle",
      "documents:createDialog.stages.feature",
      "documents:createDialog.states.coverageUnavailable",
      "documents:createDialog.titles.feature",
      "documents:createDialog.validation.completeRequiredFields",
    ] as const satisfies readonly MessageKey[];
    const runtimes = [
      createTestLocalizationRuntime(sourceLocale),
      createTestLocalizationRuntime(ltrTestLocale),
      createTestLocalizationRuntime(rtlTestLocale),
    ] as const;

    for (const key of keys) {
      expect(new Set(runtimes.map((runtime) => runtime.t(key))).size, key).toBe(3);
    }

    const linkedDocument = "Customer roadmap";
    expect(
      runtimes.map((runtime) =>
        runtime.t("documents:createDialog.accessibility.removeLinkedDocument", {
          document: linkedDocument,
        }),
      ),
    ).toEqual([
      "Remove Customer roadmap",
      "Supprimer Customer roadmap",
      "إزالة Customer roadmap",
    ]);
  });

  it("resolves stage-menu actions and recovery copy independently in each language", () => {
    const keys = [
      "graph:actions.addItemToWorkingSet",
      "graph:actions.pinItem",
      "graph:actions.showRelatedItem",
      "graph:actions.showStartingItem",
      "graph:actions.unpinItem",
      "graph:disabledReasons.chooseConnectionWithSummary",
      "graph:disabledReasons.chooseItemWithTitle",
      "graph:disabledReasons.relatedItemUnavailable",
      "graph:disabledReasons.startingItemUnavailable",
    ] as const satisfies readonly MessageKey[];
    const english = createTestLocalizationRuntime(sourceLocale);
    const french = createTestLocalizationRuntime(ltrTestLocale);
    const arabic = createTestLocalizationRuntime(rtlTestLocale);

    for (const key of keys) {
      const englishMessage = english.t(key);
      const frenchMessage = french.t(key);
      const arabicMessage = arabic.t(key);
      expect(frenchMessage, key).not.toBe(englishMessage);
      expect(arabicMessage, key).not.toBe(englishMessage);
      expect(arabicMessage, key).not.toBe(frenchMessage);
    }
  });

  it("resolves history and pull-request actions independently in each language", () => {
    const keys = [
      "timeline:actions.viewProjectAtVersion",
      "timeline:disabledReasons.chooseProject",
      "timeline:disabledReasons.refreshHistory",
      "timeline:disabledReasons.switchToDocumentsForHistory",
      "projects:actions.openPullRequest",
      "projects:disabledReasons.refreshProjectForPullRequest",
    ] as const satisfies readonly MessageKey[];
    const runtimes = [
      createTestLocalizationRuntime(sourceLocale),
      createTestLocalizationRuntime(ltrTestLocale),
      createTestLocalizationRuntime(rtlTestLocale),
    ] as const;

    for (const key of keys) {
      const messages = runtimes.map((runtime) => runtime.t(key));
      expect(new Set(messages).size, key).toBe(3);
    }
  });
});
