export const DOCUMENT_VIEWER_MESSAGE_POLICY = {
  "documents:viewer.accessibility.documentMode": { role: "accessibility" },
  "documents:viewer.accessibility.documentProperties": { role: "accessibility" },
  "documents:viewer.accessibility.featureTag": { role: "accessibility" },
  "documents:viewer.comments.accessibility.commentsToReview": {
    role: "accessibility",
  },
  "documents:viewer.comments.accessibility.editComment": {
    role: "accessibility",
  },
  "documents:viewer.comments.accessibility.newComment": {
    role: "accessibility",
  },
  "documents:viewer.comments.accessibility.sectionComments": {
    role: "accessibility",
  },
  "documents:viewer.comments.actions.add": { role: "action" },
  "documents:viewer.comments.actions.close": { role: "action" },
  "documents:viewer.comments.actions.copyLink": { role: "action" },
  "documents:viewer.comments.actions.edit": { role: "action" },
  "documents:viewer.comments.actions.open": { role: "action" },
  "documents:viewer.comments.actions.reopen": { role: "action" },
  "documents:viewer.comments.actions.resolve": { role: "action" },
  "documents:viewer.comments.actions.save": { role: "action" },
  "documents:viewer.comments.actions.tryAgain": { role: "action" },
  "documents:viewer.comments.authorKinds.agent": { role: "label" },
  "documents:viewer.comments.authorKinds.human": { role: "label" },
  "documents:viewer.comments.authorKinds.system": { role: "label" },
  "documents:viewer.comments.authorKinds.toolExecutor": { role: "label" },
  "documents:viewer.comments.authorKinds.unknown": { role: "label" },
  "documents:viewer.comments.confirmations.delete.body": {
    role: "confirmation",
  },
  "documents:viewer.comments.confirmations.delete.title": {
    role: "confirmation",
  },
  "documents:viewer.comments.connectionIssues.ambiguous": {
    role: "error-message",
  },
  "documents:viewer.comments.connectionIssues.changed": {
    role: "error-message",
  },
  "documents:viewer.comments.connectionIssues.malformed": {
    role: "error-message",
  },
  "documents:viewer.comments.connectionIssues.missing": {
    role: "error-message",
  },
  "documents:viewer.comments.counts.commentsToReview": { role: "status" },
  "documents:viewer.comments.counts.days": { role: "status" },
  "documents:viewer.comments.counts.hours": { role: "status" },
  "documents:viewer.comments.counts.minutes": { role: "status" },
  "documents:viewer.comments.counts.months": { role: "status" },
  "documents:viewer.comments.counts.years": { role: "status" },
  "documents:viewer.comments.descriptions.attachedToSection": {
    role: "description",
  },
  "documents:viewer.comments.disabledReasons.actorPreparing": {
    role: "disabled-reason",
  },
  "documents:viewer.comments.disabledReasons.duplicateHeading": {
    role: "disabled-reason",
  },
  "documents:viewer.comments.emptyStates.noComments": { role: "status" },
  "documents:viewer.comments.emptyStates.noCommentsToReview": { role: "status" },
  "documents:viewer.comments.errors.actorUnavailable": {
    role: "error-message",
  },
  "documents:viewer.comments.errors.addFailed": { role: "error-message" },
  "documents:viewer.comments.errors.copyLinkFailed": {
    role: "error-message",
  },
  "documents:viewer.comments.errors.deleteFailed": { role: "error-message" },
  "documents:viewer.comments.errors.loadFailed": { role: "error-message" },
  "documents:viewer.comments.errors.moveFailed": { role: "error-message" },
  "documents:viewer.comments.errors.reopenFailed": { role: "error-message" },
  "documents:viewer.comments.errors.resolveFailed": { role: "error-message" },
  "documents:viewer.comments.errors.saveFailed": { role: "error-message" },
  "documents:viewer.comments.feedback.added": { role: "status" },
  "documents:viewer.comments.feedback.deleted": { role: "status" },
  "documents:viewer.comments.feedback.moved": { role: "status" },
  "documents:viewer.comments.feedback.reopened": { role: "status" },
  "documents:viewer.comments.feedback.resolved": { role: "status" },
  "documents:viewer.comments.feedback.saved": { role: "status" },
  "documents:viewer.comments.placeholders.newComment": { role: "label" },
  "documents:viewer.comments.states.justNow": { role: "status" },
  "documents:viewer.comments.states.loading": { role: "status" },
  "documents:viewer.comments.states.preparing": { role: "status" },
  "documents:viewer.comments.states.resolved": { role: "status" },
  "documents:viewer.codeViewer.accessibility.contents": { role: "accessibility" },
  "documents:viewer.codeViewer.errors.loadFailed": { role: "error-message" },
  "documents:viewer.codeViewer.errors.temporarilyUnavailable": {
    role: "error-message",
  },
  "documents:viewer.codeViewer.footer.summary": { role: "status" },
  "documents:viewer.codeViewer.labels.code": { role: "label" },
  "documents:viewer.codeViewer.labels.readOnly": { role: "label" },
  "documents:viewer.codeViewer.states.empty": { role: "status" },
  "documents:viewer.codeViewer.states.loading": { role: "status" },
  "documents:viewer.codeViewer.states.missing": { role: "status" },
  "documents:viewer.reader.accessibility.document": { role: "accessibility" },
  "documents:viewer.reader.errors.loadFailed": { role: "error-message" },
  "documents:viewer.reader.errors.temporarilyUnavailable": {
    role: "error-message",
  },
  "documents:viewer.reader.labels.created": { role: "label" },
  "documents:viewer.reader.labels.document": { role: "label" },
  "documents:viewer.reader.labels.readOnly": { role: "label" },
  "documents:viewer.reader.labels.relatedDocuments": { role: "label" },
  "documents:viewer.reader.labels.tags": { role: "label" },
  "documents:viewer.reader.labels.updated": { role: "label" },
  "documents:viewer.reader.metadata.readTime": { role: "status" },
  "documents:viewer.reader.metadata.readTimeStatus": { role: "status" },
  "documents:viewer.reader.metadata.createdReadTime": { role: "description" },
  "documents:viewer.reader.metadata.createdReadTimeStatus": {
    role: "description",
  },
  "documents:viewer.reader.metadata.updatedReadTime": { role: "description" },
  "documents:viewer.reader.metadata.updatedReadTimeStatus": {
    role: "description",
  },
  "documents:viewer.reader.metadata.createdUpdatedReadTime": {
    role: "description",
  },
  "documents:viewer.reader.metadata.createdUpdatedReadTimeStatus": {
    role: "description",
  },
  "documents:viewer.reader.states.empty": { role: "status" },
  "documents:viewer.reader.states.loading": { role: "status" },
  "documents:viewer.reader.states.missing": { role: "status" },
  "documents:viewer.reader.statuses.accepted": { role: "status" },
  "documents:viewer.reader.statuses.active": { role: "status" },
  "documents:viewer.reader.statuses.complete": { role: "status" },
  "documents:viewer.reader.statuses.deprecated": { role: "status" },
  "documents:viewer.reader.statuses.proposed": { role: "status" },
  "documents:viewer.reader.statuses.rejected": { role: "status" },
  "documents:viewer.reader.statuses.superseded": { role: "status" },
  "documents:viewer.reader.statuses.unavailable": { role: "status" },
  "documents:viewer.reader.truncation.bytes": { role: "description" },
  "documents:viewer.modes.edit": { role: "label" },
  "documents:viewer.modes.view": { role: "label" },
  "documents:viewer.properties.actions.rename": { role: "action" },
  "documents:viewer.properties.actions.save": { role: "action" },
  "documents:viewer.properties.emptyStates.newFeatureTag": { role: "status" },
  "documents:viewer.properties.labels.date": { role: "label" },
  "documents:viewer.properties.labels.documentName": { role: "label" },
  "documents:viewer.properties.labels.documentType": { role: "label" },
  "documents:viewer.properties.labels.feature": { role: "label" },
  "documents:viewer.properties.labels.relatedDocuments": { role: "label" },
  "documents:viewer.properties.placeholders.date": { role: "label" },
  "documents:viewer.properties.placeholders.featureTag": { role: "label" },
  "documents:viewer.properties.states.notSet": { role: "label" },
  "documents:viewer.properties.states.renaming": { role: "status" },
  "documents:viewer.properties.states.saving": { role: "status" },
} as const;
