// The agent-surface slice of the English message policy (panel, transcript,
// composer, footer chip) — spread into `ENGLISH_MESSAGE_POLICY` exactly like the
// sibling domain slices (`messagePolicy.shell`, `messagePolicy.filters`, …).

import type { MessageKey } from "../platform/localization/message";
import type { MessagePolicyEntry } from "./messagePolicy";

export const AGENT_MESSAGE_POLICY = {
  "common:agent.sendComment": { role: "action" },
  // The two segment options name operation MODES (radio-style labels the control
  // selects), not imperative action buttons — classified as labels like the other
  // segmented-toggle option names.
  "common:agent.autonomy.label": { role: "label" },
  "common:agent.autonomy.reviewEach": { role: "label" },
  "common:agent.autonomy.applyAutomatically": { role: "label" },
  "common:agent.actions.openPanel": { role: "action" },
  "common:agent.actions.closePanel": { role: "action" },
  "common:agent.actions.togglePanel": { role: "action" },
  "common:agent.actions.stopRun": { role: "action" },
  "common:agent.actions.newSession": { role: "action" },
  "common:agent.panel.region": { role: "label" },
  "common:agent.panel.sessionsMenu": { role: "accessibility" },
  // "New session" is the Figma-bound noun-phrase menu name (like "New document"),
  // not imperative copy — classified as a label, mirroring that precedent.
  "common:agent.panel.newSession": { role: "label" },
  "common:agent.panel.recentSessions": { role: "label" },
  "common:agent.panel.untitledSession": { role: "label" },
  "common:agent.panel.close": { role: "accessibility" },
  "common:agent.transcript.loading": { role: "status" },
  "common:agent.transcript.empty": { role: "status" },
  "common:agent.transcript.noSession": { role: "status" },
  "common:agent.transcript.error": { role: "error-message" },
  "common:agent.transcript.showingRecent": { role: "status" },
  "common:agent.transcript.toolCalls": { role: "accessibility" },
  "common:agent.transcript.thinking": { role: "label" },
  "common:agent.transcript.thinkingDuration": { role: "label" },
  "common:agent.transcript.toolInput": { role: "label" },
  "common:agent.transcript.toolResult": { role: "label" },
  "common:agent.transcript.toolStatus.done": { role: "status" },
  "common:agent.transcript.toolStatus.needsPermission": { role: "status" },
  "common:agent.transcript.toolStatus.allowed": { role: "status" },
  "common:agent.transcript.toolStatus.denied": { role: "status" },
  "common:agent.transcript.toolStatus.notAllowed": { role: "status" },
  "common:agent.transcript.turnStatus.working": { role: "status" },
  "common:agent.transcript.turnStatus.stopping": { role: "status" },
  "common:agent.transcript.turnStatus.done": { role: "status" },
  "common:agent.transcript.turnStatus.stopped": { role: "status" },
  "common:agent.transcript.turnStatus.failed": { role: "status" },
  "common:agent.transcript.permissionQuestion": { role: "label" },
  "common:agent.transcript.allow": { role: "action" },
  "common:agent.transcript.deny": { role: "action" },
  "common:agent.transcript.permissionFailed": { role: "error-message" },
  "common:agent.composer.placeholder": { role: "label" },
  "common:agent.composer.steerPlaceholder": { role: "label" },
  "common:agent.composer.send": { role: "action" },
  "common:agent.composer.stop": { role: "action" },
  "common:agent.composer.sendFailed": { role: "error-message" },
  "common:agent.composer.attachedContext": { role: "accessibility" },
  "common:agent.composer.queuedChip": { role: "label" },
  "common:agent.composer.removeQueued": { role: "accessibility" },
  "common:agent.composer.mentionPlaceholder": { role: "label" },
  "common:agent.composer.mentionAria": { role: "accessibility" },
  "common:agent.composer.mentionEmpty": { role: "status" },
  "common:agent.composer.removeMention": { role: "accessibility" },
  "common:agent.composer.commentBatch": { role: "label" },
  "common:agent.composer.removeComments": { role: "accessibility" },
  "common:agent.composer.slashAria": { role: "accessibility" },
  "common:agent.composer.slashEmpty": { role: "status" },
  "common:agent.composer.selectorValue": { role: "label" },
  "common:agent.composer.selectorDisabled": { role: "accessibility" },
  "common:agent.composer.model": { role: "label" },
  "common:agent.composer.modelDefault": { role: "label" },
  // Non-actionable unavailability reasons ride the `status` role, mirroring the
  // `common:disabledReasons.*` precedent (nothing the operator can do yet).
  "common:agent.composer.modelUnavailable": { role: "status" },
  "common:agent.composer.team": { role: "label" },
  "common:agent.composer.teamDefault": { role: "label" },
  "common:agent.composer.teamUnavailable": { role: "status" },
  "common:agent.chip.working": { role: "status" },
  "common:agent.chip.label": { role: "accessibility" },
  "common:agent.chip.status.active": { role: "status" },
  "common:agent.chip.status.cancelRequested": { role: "status" },
} as const satisfies Partial<Record<MessageKey, MessagePolicyEntry>>;
