// The agent-surface slice of the English message policy (panel, transcript,
// composer, footer chip) — spread into `ENGLISH_MESSAGE_POLICY` exactly like the
// sibling domain slices (`messagePolicy.shell`, `messagePolicy.filters`, …).

import type { MessageKey } from "../platform/localization/message";
import type { MessagePolicyEntry } from "./messagePolicy";

export const AGENT_MESSAGE_POLICY = {
  "common:agent.sendComment": { role: "action" },
  // The two segment options name operation MODES (radio-style labels the control
  // selects), not imperative action buttons — classified as labels like the other
  // segmented-toggle option names.
  "common:agent.autonomy.label": { role: "label" },
  "common:agent.autonomy.reviewEach": { role: "label" },
  "common:agent.autonomy.applyAutomatically": { role: "label" },
  "common:agent.autonomy.menuAria": { role: "accessibility" },
  "common:agent.actions.openPanel": { role: "action" },
  "common:agent.actions.closePanel": { role: "action" },
  "common:agent.actions.togglePanel": { role: "action" },
  "common:agent.actions.stopRun": { role: "action" },
  "common:agent.actions.newSession": { role: "action" },
  // The rail-footer pending-changes chip, retired out of the "Approvals"/
  // `panel:approvals` vocabulary onto the agent plane it actually opens.
  // The begin idiom (research G1/G2/G4/G11): the headline is a question addressed
  // to the user, the starters are intent verbs, and the seeds are draft text the
  // user continues typing — not commands.
  "common:agent.begin.headline": { role: "label" },
  "common:agent.begin.headlineUnbound": { role: "label" },
  "common:agent.begin.startersLabel": { role: "accessibility" },
  "common:agent.begin.recentsLabel": { role: "accessibility" },
  // The starters NAME an intent the click seeds into the draft; they do not perform
  // it. That makes them option labels, like the segmented-toggle option names above,
  // not imperative command buttons.
  "common:agent.begin.starters.explore": { role: "label" },
  "common:agent.begin.starters.build": { role: "label" },
  "common:agent.begin.starters.review": { role: "label" },
  // Intent-card outcome lines (D7): each states what the lane PRODUCES.
  "common:agent.begin.descriptions.explore": { role: "status" },
  "common:agent.begin.descriptions.build": { role: "status" },
  "common:agent.begin.descriptions.review": { role: "status" },
  "common:agent.begin.seeds.explore": { role: "label" },
  "common:agent.begin.seeds.build": { role: "label" },
  "common:agent.begin.seeds.review": { role: "label" },
  // The standing elevated-autonomy strip (C7). A warning about a live policy, so
  // it is a status, not an error the user caused.
  "common:agent.autonomyBanner.warning": { role: "status" },
  "common:agent.autonomyBanner.dismiss": { role: "action" },
  // The docked run header (C5): a region name, the served phase rendered verbatim,
  // and the roster eyebrow.
  // The mid-run questionnaire (D5). The title states a live condition, the recap
  // eyebrow labels a durable transcript object, and Send answer is the one verb.
  "common:agent.clarification.region": { role: "accessibility" },
  "common:agent.clarification.title": { role: "status" },
  "common:agent.clarification.submit": { role: "action" },
  "common:agent.clarification.optionOrdinal": { role: "label" },
  "common:agent.clarification.required": { role: "label" },
  "common:agent.clarification.answerPlaceholder": { role: "label" },
  "common:agent.clarification.failed": { role: "error-message" },
  "common:agent.clarification.recapTitle": { role: "label" },
  "common:agent.runHeader.region": { role: "accessibility" },
  "common:agent.runHeader.phase": { role: "label" },
  "common:agent.runHeader.elapsed": { role: "label" },
  "common:agent.runHeader.frozenAssignment": { role: "label" },
  "common:agent.runHeader.frozenAssignmentInvalid": { role: "status" },
  "common:agent.runHeader.schemaVersion": { role: "label" },
  "common:agent.runHeader.digest": { role: "label" },
  "common:agent.runHeader.role": { role: "label" },
  "common:agent.runHeader.provider": { role: "label" },
  "common:agent.runHeader.providerIdentity": { role: "label" },
  "common:agent.runHeader.executionMode": { role: "label" },
  "common:agent.runHeader.model": { role: "label" },
  "common:agent.runHeader.modelValue": { role: "label" },
  "common:agent.runHeader.entryId": { role: "label" },
  "common:agent.runHeader.catalogRevision": { role: "label" },
  "common:agent.runHeader.nativeControls": { role: "label" },
  "common:agent.runHeader.controlValue": { role: "label" },
  "common:agent.runHeader.fallbackPlan": { role: "label" },
  "common:agent.runHeader.labeledValue": { role: "label" },
  "common:agent.runHeader.selectionSource": { role: "label" },
  "common:agent.runHeader.teamSelection": { role: "label" },
  "common:agent.runHeader.roleOverride": { role: "label" },
  "common:agent.runHeader.mixedProvider": { role: "label" },
  "common:agent.runHeader.roster": { role: "label" },
  "common:agent.pending.label": { role: "label" },
  "common:agent.pending.show": { role: "action" },
  "common:agent.pending.unavailable": { role: "error-title" },
  "common:agent.panel.region": { role: "label" },
  // The conversation title's own actions menu (the captured title-with-menu
  // idiom, D10) and the History affordance are icon/menu accessible names.
  "common:agent.panel.conversationMenu": { role: "accessibility" },
  "common:agent.panel.history": { role: "accessibility" },
  // "New session" / "Archive conversation" are Figma-bound noun-phrase menu names
  // (like "New document"), not imperative copy — classified as labels.
  "common:agent.panel.newSession": { role: "label" },
  "common:agent.panel.archiveSession": { role: "label" },
  "common:agent.panel.recentSessions": { role: "label" },
  "common:agent.panel.untitledSession": { role: "label" },
  "common:agent.panel.close": { role: "accessibility" },
  "common:agent.transcript.loading": { role: "status" },
  "common:agent.transcript.empty": { role: "status" },
  "common:agent.transcript.error": { role: "error-message" },
  "common:agent.transcript.unavailable": { role: "error-message" },
  "common:agent.transcript.showingRecent": { role: "status" },
  // The one work-stretch disclosure (C2/C3): its label reports elapsed time or the
  // served tool count, and the expanded flat list is named for screen readers.
  "common:agent.transcript.timeline": { role: "accessibility" },
  "common:agent.transcript.usedTools": { role: "label" },
  "common:agent.transcript.workedFor": { role: "label" },
  "common:agent.transcript.thinking": { role: "label" },
  "common:agent.transcript.thinkingDuration": { role: "label" },
  "common:agent.transcript.toolInput": { role: "label" },
  "common:agent.transcript.toolResult": { role: "label" },
  "common:agent.transcript.toolStatus.done": { role: "status" },
  "common:agent.transcript.toolStatus.needsPermission": { role: "status" },
  "common:agent.transcript.toolStatus.allowed": { role: "status" },
  "common:agent.transcript.toolStatus.denied": { role: "status" },
  "common:agent.transcript.toolStatus.notAllowed": { role: "status" },
  "common:agent.transcript.turnStatus.working": { role: "status" },
  "common:agent.transcript.turnStatus.stopping": { role: "status" },
  "common:agent.transcript.turnStatus.done": { role: "status" },
  "common:agent.transcript.turnStatus.stopped": { role: "status" },
  "common:agent.transcript.turnStatus.failed": { role: "status" },
  "common:agent.transcript.permissionQuestion": { role: "label" },
  "common:agent.transcript.allow": { role: "action" },
  "common:agent.transcript.deny": { role: "action" },
  "common:agent.transcript.permissionFailed": { role: "error-message" },
  "common:agent.transcript.team.thinking": { role: "label" },
  "common:agent.transcript.team.thinkingLive": { role: "label" },
  "common:agent.transcript.team.working": { role: "status" },
  "common:agent.transcript.team.workingAgents": { role: "status" },
  "common:agent.transcript.team.callingTool": { role: "label" },
  "common:agent.transcript.team.result": { role: "label" },
  "common:agent.transcript.team.degraded": { role: "status" },
  "common:agent.transcript.team.error": { role: "error-message" },
  "common:agent.composer.placeholder": { role: "label" },
  "common:agent.composer.clarificationParked": { role: "label" },
  "common:agent.composer.steerPlaceholder": { role: "label" },
  // No send button exists (D11 — Enter is the send, per every captured
  // composer); the hint names the verb for assistive tech, and the workspace
  // chip's accessible name states the binding the wire already enforces.
  "common:agent.composer.enterHint": { role: "accessibility" },
  "common:agent.composer.attach": { role: "accessibility" },
  "common:agent.composer.workspace": { role: "accessibility" },
  "common:agent.composer.sendFailed": { role: "error-message" },
  "common:agent.composer.attachContext": { role: "action" },
  "common:agent.composer.attachedContext": { role: "accessibility" },
  "common:agent.composer.evidenceAria": { role: "accessibility" },
  "common:agent.composer.evidencePlaceholder": { role: "label" },
  "common:agent.composer.evidenceEmpty": { role: "status" },
  "common:agent.composer.queuedChip": { role: "label" },
  "common:agent.composer.removeQueued": { role: "accessibility" },
  "common:agent.composer.mentionPlaceholder": { role: "label" },
  "common:agent.composer.mentionAria": { role: "accessibility" },
  "common:agent.composer.mentionEmpty": { role: "status" },
  "common:agent.composer.removeMention": { role: "accessibility" },
  "common:agent.composer.commentBatch": { role: "label" },
  "common:agent.composer.removeComments": { role: "accessibility" },
  "common:agent.composer.slashAria": { role: "accessibility" },
  "common:agent.composer.slashEmpty": { role: "status" },
  "common:agent.composer.selectorValue": { role: "label" },
  "common:agent.composer.selectorDisabled": { role: "accessibility" },
  "common:agent.composer.model": { role: "label" },
  // Non-actionable unavailability reasons ride the `status` role, mirroring the
  // `common:disabledReasons.*` precedent (nothing the operator can do yet).
  "common:agent.composer.modelUnavailable": { role: "status" },
  "common:agent.composer.providerHealth": { role: "label" },
  "common:agent.composer.providerHealthConfigured": { role: "label" },
  "common:agent.composer.providerHealthTransport": { role: "label" },
  "common:agent.composer.providerHealthAuthentication": { role: "label" },
  "common:agent.composer.providerHealthCatalog": { role: "label" },
  "common:agent.composer.providerHealthCatalogFreshness": { role: "label" },
  "common:agent.composer.providerHealthAdmission": { role: "label" },
  "common:agent.composer.providerHealthSelectable": { role: "status" },
  "common:agent.composer.providerHealthNotSelectable": { role: "status" },
  "common:agent.composer.providerHealthHealthCheckedAt": { role: "status" },
  "common:agent.composer.providerHealthCheckedAt": { role: "status" },
  "common:agent.composer.providerHealthExpiresAt": { role: "status" },
  "common:agent.composer.providerHealthReasons": { role: "label" },
  "common:agent.composer.providerHealthStateAvailable": { role: "status" },
  "common:agent.composer.providerHealthStateUnavailable": { role: "status" },
  "common:agent.composer.providerHealthStateUnknown": { role: "status" },
  "common:agent.composer.providerHealthStateAuthenticated": { role: "status" },
  "common:agent.composer.providerHealthStateUnauthenticated": { role: "status" },
  "common:agent.composer.providerHealthStateNotApplicable": { role: "status" },
  "common:agent.composer.providerHealthStateStale": { role: "status" },
  "common:agent.composer.providerHealthStateAdmitted": { role: "status" },
  "common:agent.composer.providerHealthStateNotAdmitted": { role: "status" },
  "common:agent.composer.advancedSelection": { role: "label" },
  "common:agent.composer.advancedSelectionDescription": { role: "description" },
  "common:agent.composer.roleOverrides": { role: "label" },
  "common:agent.composer.roleOverride": { role: "accessibility" },
  "common:agent.composer.noRoleOverrides": { role: "status" },
  "common:agent.composer.roleOrdinal": { role: "label" },
  "common:agent.composer.fallbacks": { role: "label" },
  "common:agent.composer.addFallback": { role: "action" },
  "common:agent.composer.removeFallback": { role: "accessibility" },
  "common:agent.composer.fallbackOrdinal": { role: "label" },
  "common:agent.composer.team": { role: "label" },
  "common:agent.composer.teamDefault": { role: "label" },
  "common:agent.composer.teamUnset": { role: "label" },
  "common:agent.composer.feature": { role: "label" },
  "common:agent.composer.featureUnset": { role: "label" },
  // Actionable: the operator settles this before the run can start (S44).
  "common:agent.composer.featureUnbound": { role: "status" },
  "common:agent.composer.featureFromDocument": { role: "status" },
  "common:agent.composer.featurePlaceholder": { role: "label" },
  "common:agent.composer.featureEmpty": { role: "status" },
  "common:agent.composer.featureMenuAria": { role: "accessibility" },
  "common:agent.composer.modelMenuAria": { role: "accessibility" },
  "common:agent.composer.teamMenuAria": { role: "accessibility" },
  "common:agent.composer.teamPresetUnavailable": { role: "status" },
  "common:agent.composer.cancelTeamRun": { role: "action" },
  "common:agent.composer.teamRunPhase": { role: "status" },
  "common:agent.composer.teamRunRefused": { role: "error-message" },
  "common:agent.composer.teamRunDegraded": { role: "status" },
  "common:agent.composer.teamRunDismiss": { role: "action" },
  "common:agent.composer.teamRunLocked": { role: "status" },
  "common:agent.chip.working": { role: "status" },
  "common:agent.chip.label": { role: "accessibility" },
  "common:agent.chip.status.active": { role: "status" },
  "common:agent.chip.status.cancelRequested": { role: "status" },
  // The bridge affordance's visible text names a COUNT/state of pending changes (a
  // chip-like label), not an imperative action button — classified as a label. The
  // truncated variant drops the numeral honestly.
  "common:agent.pendingBridge.count": { role: "label" },
  "common:agent.pendingBridge.more": { role: "label" },
} as const satisfies Partial<Record<MessageKey, MessagePolicyEntry>>;
